### PR TITLE
issue2699: restore symlinks on windows when run as admin user

### LINKED ISSUE #1078: Symlinks to a directory are not detected in Windows
## Output of `restic version`
    restic 0.7.0
    compiled with go1.8.3 on windows/amd64

## How did you start restic exactly? (Include the complete command line)
    restic backup --repo R:\test_backup R:\test

## What backend/server/service did you use?
Local.

## Expected behavior
The symlink to a directory should be detected just like symlinks to files are.

## Actual behavior
    warning for test\symlinkdir: invalid node type ""

## Steps to reproduce the behavior
    restic init --repo R:\test_backup
    restic backup --repo R:\test_backup R:\test

`R:\test` contains a directory called `realdir` and a symlink to it called `symlinkdir` created with `mklink /D symlinkdir realdir` (you'll need an elevated prompt in order to do that). A junction to the directory (`mklink /J`) behaves the same way (what's the difference? [see end of page 431](https://books.google.com/books?id=3rdCAwAAQBAJ&pg=PA431&lpg=PA431&dq=there+are+no+windows+function+for+creating+reparse+points&source=bl&ots=d7zxxodyqG&sig=D9qYu2h69YJwSkkSpU6GffoWxO4&hl=es&sa=X&redir_esc=y#v=onepage&q=there%20are%20no%20windows%20function%20for%20creating%20reparse%20points&f=false)).

## Do you have any idea what may have caused this?
Somehow `nodeTypeFromFileInfo()` is returning `""` for a symlink to a directory. It might be a bug in the `os` package and this is more like an upstream thing?

### LINKED ISSUE #2699: Windows: Symlinks are not backuped
Output of `restic version`
--------------------------
restic 0.9.6 compiled with go1.13.4 on windows/amd64

How did you run restic exactly?
-------------------------------

```
1. restic -r symlinktest init
2. restic -r symlinktest backup resticsymlinktest
```

This prints
```
repository 17418abd opened successfully, password is correct
created new cache in C:\Users\JsBerbau\AppData\Local\restic

Files:           1 new,     0 changed,     0 unmodified
Dirs:            0 new,     0 changed,     0 unmodified
Added to the repo: 343 B

processed 1 files, 31 B in 0:00
snapshot 5f283900 saved
```

The folder resticsymlinktest contained:
File.txt containing

```
Hallo,
I'm the "real" testfile
```

A symlink to that file, created via
`mklink link File.txt`

Tested restore via
`restic -r symlinktest restore -t resticsymlinkrestoretest latest`
Only 1 file was restored, missing the symlink.

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
Filesystem

Expected behavior
-----------------
The symlink file is included in the backup and restored when restoring.

Actual behavior
---------------
Symlinkfile is not added to backup and thus also not restored.

Steps to reproduce the behavior
-------------------------------
See above

Do you have any idea what may have caused this?
-----------------------------------------------
No

Do you have an idea how to solve the issue?
-------------------------------------------
Include symlink files into backup and restore them

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
Restic is a very great tool and I hope that symlinks are also restored. Then I'm calm that the backup contains all my files and I can recover everything in case of a disaster.

### PR DESCRIPTION
**Pull request by fgma**
What does this PR change? What problem does it solve?
-----------------------------------------------------

Currently symlinks on windows are backed up but not restored. Because of windows restrictions this is only possible with admin privileges. This patch checks if the user running restic has sufficient privileges to restore symlinks and restores them if possible.

For testing the feature you may use the attached demo script: [issue2699.zip](https://github.com/restic/restic/files/5030502/issue2699.zip)

Running demo.bat will do the following:

1. call init.bat: create a demo repository and demo data in the current directory
2. call backup.bat: backup the created data
2. call restore.bat: restore the data to a new folder

Was the change discussed in an issue or in the forum before?
------------------------------------------------------------

Closes #2699
Closes #1078

Checklist
---------

- [x] I have read the [Contribution Guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches)
- [x] I have enabled [maintainer edits for this PR](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)
- [ ] I have added tests for all changes in this PR
- [x] I have added documentation for the changes (in the manual)
- [x] There's a new file in `changelog/unreleased/` that describes the changes for our users (template [here](https://github.com/restic/restic/blob/master/changelog/TEMPLATE))
- [x] I have run `gofmt` on the code in all commits
- [x] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits)
- [x] I'm done, this Pull Request is ready for review

### CODE REVIEW

File: internal/restic/util_windows.go [hunk 1]
```diff
@@ -0,0 +1,39 @@
+package restic
+
+import (
+	"github.com/restic/restic/internal/debug"
+	"golang.org/x/sys/windows"
+)
+
+// IsRunningAsAdminOnWindows is true if the process is running with admin privileges
+var IsRunningAsAdminOnWindows = func() bool {
```
Comment (greatroar) [inline internal/restic/util_windows.go:9]: This runs unconditionally for all commands, even though only recover needs the result. As these hacks accumulate, the startup cost of all commands increases. Also, errors are logged but then ignored. It's better written as a function that reads a variable initialized Once:

```
var windowsAdmin struct {
	sync.Once
	isAdmin bool
	err     error
}

func isWindowsAdmin() (bool, error) {
	windowsAdmin.Do(func() {
		windowsAdmin.isAdmin, windowsAdmin.err = /* whatever */
	})
	return windowsAdmin.isAdmin, windowsAdmin.err
}
```

Note that the function need not be public since it is used only inside this package.

File: internal/restic/node.go [hunk 2]
```diff
@@ -297,11 +298,28 @@ func (node Node) writeNodeContent(ctx context.Context, repo Repository, f *os.Fi
...
+		if !IsRunningAsAdminOnWindows {
+			debug.Log(
+				"can't restore symlink to %v without admin privileges on windows",
+				path,
+			)
+			return nil
+		}
+
+		// fix path so a restore to a different location will produce
+		// consistent data
```
Comment (greatroar) [inline internal/restic/node.go:315]: Is this necessary? It introduces an incompatbility between Windows and Unix.

File: internal/restic/util_windows.go (hunk 1 above)
Comment (fgma) [reply internal/restic/util_windows.go]: Was already there in a uncommited version until I "simplified" it. Added it back in https://github.com/restic/restic/pull/2875/commits/a69924fb41920a49681cf4363e0a82e8a4e02ae5.

File: internal/restic/node.go (hunk 2 above)
Comment (fgma) [reply internal/restic/node.go:321]: For me it was necessary to restore the symlinks properly, otherwise they would point to invalid locations. This might be related to https://github.com/restic/restic/issues/2004. If this one is done I hope to investigate https://github.com/restic/restic/issues/2004.

**Comment by hgraeber** [comment]
Instead of checking for the Admin User it would be more general to check whether the user has the SeCreateSymbolicLinkPrivilege privilege.

Additional there is the possibility to create symlinks without elevation if developer mode is activated for Windows 10 and CreateSymbolicLink is called with the SYMBOLIC_LINK_FLAG_ALLOW_UNPRIVILEGED_CREATE flag.

File: internal/restic/node.go (hunk 2 above)
Comment (greatroar) [reply internal/restic/node.go:321]: On Unix, restore may produce invalid symlinks as well, but I guess the drive letters make this more painful on Windows. I'm not sure what would be the proper behavior here.

**Comment by fgma** [comment]
@hgraeber Implemented in my last commit. Please have a look.

**Comment by hgraeber** [comment]
In principle the check for the check for the privilege looks good to me, but I am a go newbie coming from C/C++.

After thinking more about this, I have doubts whether it is worth making this check to this extent.The only thing it does is getting an error message before creating symlinks. Simply trying to create a symlink an having a error message if it fails should be sufficient. Having the privilege - eg. through an elevated command prompt - is needed in both cases.

So dropping

    // Windows does not allow non-admins to create soft links.
    if runtime.GOOS == "windows" {
        return nil
    }

in `createSymlinkAt` may be enough to solve the issue.

**Comment by fgma** [comment]
@hgraeber A valid option. I'd add some windows specific code to the error handling to give the user a more specific source of the problem inside the error handling block after calling fs.Symlink(). I'm going to wait for some official feedback on how to continue before putting more work into this PR.

File: internal/restic/node.go (hunk 2 above)
Comment (werbes) [reply internal/restic/node.go:324]: > Is this necessary? It introduces an incompatbility between Windows and Unix.

Yes - When doing full system resore of Windows it needs the symbolic links to be restore - else user profiles will not be usable.

**Review by werbes — COMMENTED** [review]
I have done several restore jobs with this new code on Windows and it gets the symbolic links right when restoring now.

**Comment by parasiteoflife** [comment]
Please, implement this. It's been 2 years

**Comment by MichaelEischer** [comment]
> It's pretty clear restic is just unsupported/abandonware on Windows. It's had data loss inducing bugs with both backup and restore containing symlinks/junctions being broken since release, and unmerged fixes sitting for years.

Windows support for restic has always been primarily community driven, AFAIK there's not much/no windows usage among the maintainers. Nevertheless, I try to also fix Windows-specific problems from time to time. But some pull requests get buried under the large pile of other PRs and then it takes quite some time to dig them out again.

Would you care to elaborate which specific bugs you are referring to?

**Comment by fgma** [comment]
I will look into this in a few days. 

@MichaelEischer What about os.Symlink()? Will this be fixed or should this PR keep the workaround for now?

**Comment by MichaelEischer** [comment]
> Will this be fixed or should this PR keep the workaround for now?

Please change `fs.Symlink()` in `internal/fs/file.go` to
```
return os.Symlink(oldname, fixpath(newname))
```
and remove the workaround afterwards.

**Comment by MichaelEischer** [comment]
@fgma Any progress with cleaning up the PR?

**Comment by fgma** [comment]
@MichaelEischer Looking into it right now.

**Comment by MichaelEischer** [comment]
I've rebased the PR to remove the duplicate commits. The changelog now also contains links to all fixed issues and this PR.

**Review by MichaelEischer — APPROVED** [review]
LGTM.
