### PR TITLE
s3: Add warning if key ID or secret is empty

### LINKED ISSUE #2388: S3: Incomplete credentials (supplied from env) not reported
Output of `restic version`
--------------------------
restic 0.9.4 (v0.9.4-0-gcd9b2295) compiled with go1.10.4 on linux/amd64

How did you run restic exactly?
-------------------------------
```
$ export RESTIC_REPOSITORY="s3:https://s3.amazonaws.com/SOMETHING"
$ export AWS_ACCESS_KEY_ID="SOMETHING"
$ export AWS_SECRET_ACCES_KEY="SOMETHING"
### NOTE THE TYPO!
$ export RESTIC_PASSWORD="SOMETHING"
$ restic init
Fatal: create key in repository at s3:https://s3.amazonaws.com/SOMETHING failed: client.PutObject: Access Denied
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
AWS S3

Expected behavior
-----------------
Report on error about incomplete credentials (`AWS_SECRET_ACCESS_KEY` not found) like the aws tool from the awscli package does:

```
aws s3api list-buckets --query Owner.ID 
Partial credentials found in env, missing: AWS_SECRET_ACCESS_KEY
```

Actual behavior
---------------
Misleading error was reported that the authentication fails.

Steps to reproduce the behavior
-------------------------------
Do supply authentication for S3 backend with environment variables, but do not supply `AWS_SECRET_ACCESS_KEY`

Do you have any idea what may have caused this?
-----------------------------------------------
Not checking if the `AWS_SECRET_ACCESS_KEY` is available through any input.

Do you have an idea how to solve the issue?
-------------------------------------------
Check if the AWS_SECRET_ACCESS_KEY has been supplied before querying the server.

Did restic help you or made you happy in any way?
-------------------------------------------------
I greatly appreciate that this software. My duplicity repo got corrupted on a aborted upload and there is no way to fix it. This looks more modern and maintainable.

### PR DESCRIPTION
**Pull request by garrmcnu**
What does this PR change? What problem does it solve?
-----------------------------------------------------

Add warning for S3/GS/Azure if credentials are not set.

Was the change previously discussed in an issue or on the forum?
----------------------------------------------------------------

Closes #2388

Checklist
---------

- [x] I have read the [contribution guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches).
- [x] I have [enabled maintainer edits](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [ ] I have added tests for all code changes.
- [ ] I have added documentation for relevant changes (in the manual).
- [x] There's a new file in `changelog/unreleased/` that describes the changes for our users (see [template](https://github.com/restic/restic/blob/master/changelog/TEMPLATE)).
- [x] I have run `gofmt` on the code in all commits.
- [x] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits).
- [x] I'm done! This pull request is ready for review.

### CODE REVIEW

File: cmd/restic/global.go [hunk 1]
```diff
@@ -550,10 +550,18 @@ func parseConfig(loc location.Location, opts options.Options) (interface{}, erro
 			cfg.KeyID = os.Getenv("AWS_ACCESS_KEY_ID")
 		}
 
+		if cfg.KeyID == "" {
```
Comment (MichaelEischer) [inline cmd/restic/global.go:553]: This is not the right way to implement this check. The S3 backend supports multiple ways to pass credentials, see `internal/backend/s3/s3.go`.

What could work is checking that when a `KeyID` is specified there's also a `Secret` and vice versa.

File: cmd/restic/global.go [hunk 2]
```diff
@@ -571,6 +579,10 @@ func parseConfig(loc location.Location, opts options.Options) (interface{}, erro
 			cfg.ProjectID = os.Getenv("GOOGLE_PROJECT_ID")
 		}
 
+		if cfg.ProjectID == "" {
```
Comment (MichaelEischer) [inline cmd/restic/global.go:582]: Judging from the code the project id is only necessary to initialize a repository. Have there been complaints from people not passing the project id?

File: cmd/restic/global.go [hunk 3]
```diff
@@ -584,10 +596,18 @@ func parseConfig(loc location.Location, opts options.Options) (interface{}, erro
 			cfg.AccountName = os.Getenv("AZURE_ACCOUNT_NAME")
 		}
 
+		if cfg.AccountName == "" {
```
Comment (MichaelEischer) [inline cmd/restic/global.go:599]: The azure storage clients itself already complains if the account name / key are not set (although it can't print the name of the environment variable)

**Review by MichaelEischer — CHANGES_REQUESTED** [review]

**Review by MichaelEischer — APPROVED** [review]
LGTM. Thanks!
