### PR TITLE
Don't retry when "Permission denied" occurs in local backend

### LINKED ISSUE #3180: Don't retry "Permissions denied" error
Output of `restic version`
--------------------------
restic 0.11.0 (v0.11.0-207-gf7c7c2f7) compiled with go1.13.8 on linux/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------
PR #3170 made ENOSPC ("no space left on device") a permanent error in local backend. I suppose permissions errors could be too.

What are you trying to do? What problem would this solve?
---------------------------------------------------------
Restic would fail instantly instead of retrying.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
It's awesome.

### PR DESCRIPTION
**Pull request by tWido**
What does this PR change? What problem does it solve?
-----------------------------------------------------
Make "Permission denied" an permanent error in local backend, so it is not retried by RetryBackend.

Closes #3180

Was the change discussed in an issue or in the forum before?
------------------------------------------------------------
No.

Checklist
---------

- [x] I have read the [Contribution Guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches)
- [x] I have enabled [maintainer edits for this PR](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)
- [ ] I have added tests for all changes in this PR
- [ ] I have added documentation for the changes (in the manual)
- [ ] There's a new file in `changelog/unreleased/` that describes the changes for our users (template [here](https://github.com/restic/restic/blob/master/changelog/TEMPLATE))
- [x] I have run `gofmt` on the code in all commits
- [x] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits)
- [x] I'm done, this Pull Request is ready for review

### CODE REVIEW

File: internal/backend/local/local.go [hunk 1]
```diff
@@ -92,8 +92,8 @@ func (b *Local) Save(ctx context.Context, h restic.Handle, rd restic.RewindReade
 
 	defer func() {
 		// Mark non-retriable errors as such (currently only
-		// "no space left on device").
-		if errors.Is(err, syscall.ENOSPC) {
+		// "no space left on device" and "Permission denied").
+		if errors.Is(err, syscall.ENOSPC) || errors.Is(err, syscall.EACCES) {
```
Comment (greatroar) [inline internal/backend/local/local.go:96]: For permission denied, there's `os.IsPermission`, which checks more cases.

File: internal/backend/local/local.go [hunk 2]
```diff
@@ -92,8 +92,8 @@ func (b *Local) Save(ctx context.Context, h restic.Handle, rd restic.RewindReade
 
 	defer func() {
 		// Mark non-retriable errors as such (currently only
-		// "no space left on device").
-		if errors.Is(err, syscall.ENOSPC) {
+		// "no space left on device" and "Permission denied").
```
Comment (greatroar) [inline internal/backend/local/local.go:95]: Maybe the parenthesized part of the comment can go now. There's no use enumerating the cases in both the code and the comment.

**Comment by MichaelEischer** [comment]
The change itself looks ok. Please add a small note and reference to this PR and the attached issue to the `issue-2453` changelog file.

**Review by MichaelEischer — APPROVED** [review]
LGTM. Thanks!
