### PR TITLE
Avoid panic in duration parsing

### LINKED ISSUE #5485: Panic with incorrect duration
Hi, devs! I found that when trying to run the restic binary with the --keep-within flag (and other flags with duration) with an incorrect value, it panics.

Output of `restic version`
--------------------------
```
restic 0.14.0 compiled with go1.23.2 on linux/amd64
```

Problem description / Steps to reproduce
----------------------------------------
```
// Example of a flag value that causes panic:
$ xxd testcase.txt
00000000: df80

// Restic's output:
$ ./restic forget --keep-within <data_from_testcase.txt>
panic: strconv.Atoi: parsing "߀": invalid syntax

goroutine 1 [running]:
github.com/restic/restic/internal/restic.nextNumber({0x7ffcc7c1b226?, 0x416a45?})
        /home/fuzzuser/fuzz-projects/restic-0.14.0_fuzz/project/internal/restic/duration.go:69 +0x232
github.com/restic/restic/internal/restic.ParseDuration({0x7ffcc7c1b226?, 0xc000156320?})
        /home/fuzzuser/fuzz-projects/restic-0.14.0_fuzz/project/internal/restic/duration.go:90 +0x6c
github.com/restic/restic/internal/restic.(*Duration).Set(0x19b3090, {0x7ffcc7c1b226?, 0x10ac63e?})
        /home/fuzzuser/fuzz-projects/restic-0.14.0_fuzz/project/internal/restic/duration.go:120 +0x25
github.com/spf13/pflag.(*FlagSet).Set(0xc000016800, {0x10ac63e, 0x12}, {0x7ffcc7c1b226, 0x2})
        /home/fuzzuser/go/pkg/mod/github.com/spf13/pflag@v1.0.5/flag.go:463 +0xa2
github.com/spf13/pflag.(*FlagSet).Parse.func1(0xf0b800?, {0x7ffcc7c1b226?, 0x7ffcc7c1b213?})
        /home/fuzzuser/go/pkg/mod/github.com/spf13/pflag@v1.0.5/flag.go:1138 +0x32
github.com/spf13/pflag.(*FlagSet).parseLongArg(0xc000016800, {0x7ffcc7c1b211, 0x14}, {0xc00059c350, 0x1, 0x1}, 0xc000537bf8)
        /home/fuzzuser/go/pkg/mod/github.com/spf13/pflag@v1.0.5/flag.go:1000 +0x24f
github.com/spf13/pflag.(*FlagSet).parseArgs(0xc000016800, {0xc00059c340?, 0x14?, 0x13?}, 0xc000537bf8)
        /home/fuzzuser/go/pkg/mod/github.com/spf13/pflag@v1.0.5/flag.go:1108 +0x1b1
github.com/spf13/pflag.(*FlagSet).Parse(0xc000016800, {0xc00059c340, 0x2, 0x2})
        /home/fuzzuser/go/pkg/mod/github.com/spf13/pflag@v1.0.5/flag.go:1141 +0xd2
github.com/spf13/cobra.(*Command).ParseFlags(0x19a0020, {0xc00059c340, 0x2, 0x2})
        /home/fuzzuser/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:1655 +0xd2
github.com/spf13/cobra.(*Command).execute(0x19a0020, {0xc00059c340, 0x2, 0x2})
        /home/fuzzuser/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:795 +0x12a
github.com/spf13/cobra.(*Command).ExecuteC(0x19a1e20)
        /home/fuzzuser/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x38d
github.com/spf13/cobra.(*Command).Execute(...)
        /home/fuzzuser/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
main.main()
        /home/fuzzuser/fuzz-projects/restic-0.14.0_fuzz/project/cmd/restic/main.go:98 +0x165
```

Expected behavior
-----------------
I suppose that this error should probably be handled separately to avoid causing panic.

Actual behavior
---------------
Restic panics.

Image

### PR DESCRIPTION
**Pull request by greatroar**
What does this PR change? What problem does it solve?
-----------------------------------------------------

Fixes a panic when internal/restic.ParseDuration is fed non-ASCII digits. Also simplifies the function a bit.

Was the change previously discussed in an issue or on the forum?
----------------------------------------------------------------

Fixes #5485.

Checklist
---------

- [x] I have added tests for all code changes.
- [ ] I have added documentation for relevant changes (in the manual).
- [ ] There's a new file in `changelog/unreleased/` that describes the changes for our users (see [template](https://github.com/restic/restic/blob/master/changelog/TEMPLATE)).
- [x] I'm done! This pull request is ready for review.

### CODE REVIEW

File: internal/restic/duration.go [hunk 1]
```diff
@@ -52,12 +51,10 @@ func nextNumber(input string) (num int, rest string, err error) {
 	}
 
 	for i, s := range input {
-		if !unicode.IsNumber(s) {
-			rest = input[i:]
+		if s < '0' || s > '9' {
```
Comment (MichaelEischer) [inline internal/restic/duration.go:54]: This won't correctly handle durations with a missing unit at the end. For example `5` would now yield error `no number found` instead of `no unit found after number ...`.

This is easily visible when adding the (missing) test case `{input: "5", num: 5, rest: "", },` to `TestNextNumber`

**Review by MichaelEischer — CHANGES_REQUESTED** [review]

File: internal/restic/duration.go (hunk 1 above)
Comment (greatroar) [reply internal/restic/duration.go:54]: Good catch. I removed my second commit and added your test case to the PR.

**Review by MichaelEischer — APPROVED** [review]
LGTM. Thanks!
