### PR TITLE
Fix rclone subprocess handling

### LINKED ISSUE #2381: restic does not detect rclone termination
Output of `restic version`
--------------------------
```
restic 0.9.5 compiled with go1.12.4 on linux/arm
```

How did you run restic exactly?
-------------------------------
```
GOGC=20 nice -n 19 ionice -c 3 restic -r rclone:jotta:xxx --password-file xxx.passwd backup --one-file-system -v /mnt/xxx
```

In one case the system had 2 Gbyte of RAM, and the Linux out-of-memory (OOM) killer terminated the rclone process, and in a second case the system had 1 Gbyte of RAM and the OOM killer terminated the rclone process.

In both cases, restic just hung, doing nothing.

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
Jottacloud, but I saw identical behavior using the sftp backend.

Expected behavior
-----------------
restic should detect that rclone has died and exit with an error.

Actual behavior
---------------
restic sat there quietly, doing nothing.

Steps to reproduce the behavior
-------------------------------
It seems like you can get similar results just by killing the rclone process by hand.

Do you have any idea what may have caused this?
-----------------------------------------------
restic ignoring SIGCHLD and/or pipe file descriptor closes.

Do you have an idea how to solve the issue?
-------------------------------------------
Detect the error and exit.

Did restic help you or made you happy in any way?
-------------------------------------------------
restic is awesome. I am nervous to have built all of my backups around it, but so far so good! 😂👍

### PR DESCRIPTION
**Pull request by MichaelEischer**
What is the purpose of this change? What does it change?
--------------------------------------------------------
restic currently does not detect when the rclone subprocess exits and hangs forever (see #2381 and #2797). We also see test failure from time to time which fail with "signal: broken pipe" while closing the rclone backend.

This PR is partially inspired by #2797 and reuses the new test.

restic currently holds on to file descriptors for both the read and write side of the stdin and stdout pipes to the rclone subprocess. That prevents the pipes from closing properly once rclone stops and is also the root cause of not noticing the subprocess exit. Calling `stdioConn.Close()` once the child process has exited is still necessary to free the file descriptors.

Failing rclone tests seems to be caused because for some reason rclone dies due to a SIGPIPE error which is then returned by `cmd.Wait()` and gets printed as `signal: broken pipe`. I have no idea what data rclone writes to the stdio_conn when `Close` is called, maybe some leftover data on the HTTP2 connection? The fix for this is to give rclone time to shut down after stdin was closed, such that stdout is not closed while rclone still write to it.

Was the change discussed in an issue or in the forum before?
------------------------------------------------------------
fixes #2381 
replaces #2797 

Checklist
---------

- [x] I have read the [Contribution Guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches)
- [x] I have enabled [maintainer edits for this PR](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)
- [x] I have added tests for all changes in this PR
- [x] I have added documentation for the changes (in the manual)
- [ ] There's a new file in `changelog/unreleased/` that describes the changes for our users (template [here](https://github.com/restic/restic/blob/master/changelog/TEMPLATE))
- [x] I have run `gofmt` on the code in all commits
- [x] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits)
- [x] I'm done, this Pull Request is ready for review

### CODE REVIEW

File: internal/backend/rclone/stdio_conn.go [hunk 1]
```diff
@@ -28,21 +29,25 @@ func (s *StdioConn) Write(p []byte) (int, error) {
 	return n, err
 }
 
-// Close closes both streams.
+// Close closes the stream to the child process.
```
Comment (greatroar) [inline internal/backend/rclone/stdio_conn.go:32]: Maybe this is the right time to rename stdin/stdout to toRclone/fromRclone. I was about to say that the comment is wrong, until I checked the code and realized I wanted to make that change myself and decided on the smaller patch.

File: internal/backend/rclone/backend.go [hunk 2]
```diff
@@ -73,6 +73,13 @@ func run(command string, args ...string) (*StdioConn, *exec.Cmd, *sync.WaitGroup
 	if err != nil {
 		return nil, nil, nil, nil, err
 	}
+	// close rclone side of pipes
+	if err := r.Close(); err != nil {
+		return nil, nil, nil, nil, err
```
Comment (greatroar) [inline internal/backend/rclone/backend.go:78]: In this case, it looks like w is never closed.

**Comment by greatroar** [comment]
>  I have no idea what data rclone writes to the stdio_conn when Close is called, maybe some leftover data on the HTTP2 connection?

I'm not familiar with HTTP2, but a quick glance at RFC 7540 suggests that it may still send control messages when the connection is in half-open state. Maybe it just acknowledges the close?

In any case, tests pass on my machine.

File: internal/backend/rclone/backend.go (hunk 2 above)
Comment (MichaelEischer) [reply internal/backend/rclone/backend.go]: I have to admit I was too lazy to improve the resource cleanup here after an error. I'm still not sure I've caught everything.

File: internal/backend/rclone/stdio_conn.go (hunk 1 above)
Comment (MichaelEischer) [reply internal/backend/rclone/stdio_conn.go:32]: I've renamed the stream to send and receive

**Comment by MichaelEischer** [comment]
> I'm not familiar with HTTP2, but a quick glance at RFC 7540 suggests that it may still send control messages when the connection is in half-open state. Maybe it just acknowledges the close?

The usual behavior seems to be to explicitly close the substreams, but I haven't seen commands to close the whole connection. At least nothing shows up when logging reads and writes on the stream.

**Review by fd0 — APPROVED** [review]
Great catch! LGTM!
