### PR TITLE
Don't echo authentication passwords (rest backend)

### LINKED ISSUE #2241: Don't echo authentication passwords
Output of `restic version`
--------------------------
`restic 0.9.4 compiled with go1.11.4 on darwin/amd64`

How did you run restic exactly?
-------------------------------

```
export RESTIC_REPOSITORY=rest:https://redacted-username:redacted-password@redacted-host/redacted-path/
export RESTIC_PASSWORD=redacted
restic init -v
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

`rclone serve restic` (via an nginx reverse proxy)

Expected behavior
-----------------

I have chosen to use a remote restic server (actually rclone) over TLS and requiring http authentication. However restic is a little too eager to echo the full repository URL that includes the http password. Needless to say this password is sensitive, since it allows access to push/pull data to the rclone server. It would be better for this not be visible in the output (and therefore logs etc)

Actual behavior
---------------

Full repository url is echoed that includes the remote password.

Steps to reproduce the behavior
-------------------------------

```
$ restic init
created restic repository debc97928d at rest:https://redacted-username:redacted-password@redacted-host/redacted-path/
```
Do you have any idea what may have caused this?
-----------------------------------------------

Not sure, presumably repository URLs are assumed not to be sensitive, but those that include a password are.

Do you have an idea how to solve the issue?
-------------------------------------------

Suggestions:
- Parse the repository url, censor the password portion when echoed
- Allow restic rest protocol credentials to be provided as environment variables (RESTIC_REST_USERNAME / RESTIC_REST_PASSWORD ?)

Did restic help you or made you happy in any way?
-------------------------------------------------

I love the simplicity and flexibility and I'm confident it'll be a really useful part of my backup strategy.

### PR DESCRIPTION
**Pull request by creativeprojects**
What is the purpose of this change? What does it change?
--------------------------------------------------------

Bugfix: Don't echo authentication passwords

When using a password in the URL of a rest backend, in some cases
the password was displayed in the restic log:
- when creating a repository
- when restic failed to open the repository

The URL should now be displayed with "***" in place of the password.

Fixes issue https://github.com/restic/restic/issues/2241

Was the change discussed in an issue or in the forum before?
------------------------------------------------------------

closes #2241 

Checklist
---------

- [x] I have read the [Contribution Guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches)
- [x] I have enabled [maintainer edits for this PR](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)
- [x] I have added tests for all changes in this PR
- ~I have added documentation for the changes (in the manual)~
- [x] There's a new file in `changelog/unreleased/` that describes the changes for our users (template [here](https://github.com/restic/restic/blob/master/changelog/TEMPLATE))
- [x] I have run `gofmt` on the code in all commits
- [x] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits)
- [x] I'm done, this Pull Request is ready for review

Question before ticking the last box:
--------------

Do you know of any other place where the password could be displayed in the log? I cannot find any other place.

### CODE REVIEW

File: changelog/unreleased/issue-2241 [hunk 1]
```diff
@@ -0,0 +1,10 @@
+Bugfix: Don't echo authentication passwords
```
Comment (MichaelEischer) [inline changelog/unreleased/issue-2241:1]: That sounds way to broad, please be a bit more specific.

File: changelog/unreleased/issue-2241 [hunk 2]
```diff
@@ -0,0 +1,10 @@
...
+
+When using a password in the URL of a rest backend, in some cases
+the password was displayed in the restic log:
+- when creating a repository
+- when restic failed to open the repository
+
+The URL should now be displayed with "***" in place of the password.
```
Comment (MichaelEischer) [inline changelog/unreleased/issue-2241:8]: "should" or "is"?

File: cmd/restic/global.go [hunk 3]
```diff
@@ -659,13 +659,13 @@ func open(s string, gopts GlobalOptions, opts options.Options) (restic.Backend,
 	}
 
 	if err != nil {
-		return nil, errors.Fatalf("unable to open repo at %v: %v", s, err)
+		return nil, errors.Fatalf("unable to open repo at %v: %v", location.StripPassword(s), err)
```
Comment (MichaelEischer) [inline cmd/restic/global.go:662]: Please also mask the url in the `debug.Log` call in line 607.

File: internal/backend/rest/config.go [hunk 4]
```diff
@@ -46,3 +43,37 @@ func ParseConfig(s string) (interface{}, error) {
...
+		return scheme + s
+	}
+
+	if _, set := u.User.Password(); !set {
+		return scheme + s
+	}
+
+	// A password was set: we replace the UserInfo and rebuild the string from there
+	u.User = url.UserPassword(u.User.Username(), "***")
+	stripped, err := url.QueryUnescape(u.String())
```
Comment (MichaelEischer) [inline internal/backend/rest/config.go:65]: I'm not sure whether it's a good idea to call `QueryUnescape`?

The go standard library just replaces strings: https://github.com/golang/go/blob/d91d0762c7757c12c7d5f9e2ae3f170d5bd7ba84/src/net/http/client.go#L1004
Or less hacky: Mirror the url.Redacted() method added in go 1.15 (https://golang.org/src/net/url/url.go?s=25219:25250#L852) and replace the password with "xxxxx"

**Comment by MichaelEischer** [comment]
Please rebase the PR onto the current master branch.

**Comment by creativeprojects** [comment]
Sorry, this was my intention but I pushed the wrong branch 😥

**Comment by MichaelEischer** [comment]
> Sorry, this was my intention but I pushed the wrong branch 😥

Do you need help with rebasing?

File: internal/backend/rest/config.go (hunk 4 above)
Comment (creativeprojects) [reply internal/backend/rest/config.go:65]: I remember why I was doing it, it's because the * was converted into an html character. I've changed to an 'x' instead (like in go 1.15 library)

**Comment by creativeprojects** [comment]
I think I managed, it's just something I don't do every day so I forget the git commands 👍 thanks

**Comment by rawtaz** [comment]
Hmm, is this specific to the REST backend, or are there other backends that it affects/fixes too? In other words, is this something that is only worth mentioning for the REST backend?

**Comment by MichaelEischer** [comment]
@rawtaz The PR only affects the REST backend. I'm not aware that other backends have the option to include a password in the repository address.

File: changelog/unreleased/issue-2241 [hunk 5]
```diff
@@ -0,0 +1,10 @@
+Bugfix: Hide URL passwords from logs
+
+When using a password in the URL of a rest backend, in some cases
+the password was displayed in the restic log:
+- when creating a repository
+- when restic failed to open the repository
+
+The URL is now displayed with "***" in place of the password.
```
Comment (rawtaz) [inline changelog/unreleased/issue-2241:8]: Since there is no "log" in restic, only its output, and the changelog generator restic uses doesn't support lists, I think it's better to formulate this as follows:

~~~
Bugfix: Hide password in REST URLs

When using a password in the REST backend repository URL,
the password could in some cases be included in the output
from restic, e.g. when initializing a repo or during an error.

The password is now replaced with "***" where applicable.
~~~

**Comment by rawtaz** [comment]
I noticed that the changelog entry said the password was replaced with "***", which is what I think is most conventional and makes more sense than "xxxxx". Can you please make the code and also the tests use "***" for the obfuscation instead of "xxxxx"?

**Comment by MichaelEischer** [comment]
@creativeprojects Could you also mask the repository URL in the `debug.Log` call in line 607 of `cmd/restic/global.go`?

**Comment by creativeprojects** [comment]
> Could you also mask the repository URL in the `debug.Log` call in line 607 of `cmd/restic/global.go`?

I was a bit puzzled by it, and couldn't find it the other day. But I think I found it now: do you mean the one in line 617?

https://github.com/creativeprojects/restic/blob/issue-2241/cmd/restic/global.go#L617

**Comment by MichaelEischer** [comment]
> I was a bit puzzled by it, and couldn't find it the other day. But I think I found it now: do you mean the one in line 617?
> 
> https://github.com/creativeprojects/restic/blob/issue-2241/cmd/restic/global.go#L617

Oh, sorry for the confusion, apparently the `debug.Log` statement moved in the meantime. I had `debug.Log("parsing location %v", s)` in mind which is now in line 634 on your branch.

**Review by rawtaz — APPROVED** [review]
Looks good to me, thanks a lot for your patience and quick updates after our comments!

**Review by MichaelEischer — APPROVED** [review]
LGTM. Thanks for the PR.
I've made one minor change and added a link to this PR to the changelog.
