### PR TITLE
Fix Azure Container Token Auth

### LINKED ISSUE #4004: azure: Unable to init repo when using container-level SAS (SAT)
Output of `restic version`
--------------------------

`restic 0.14.0 (v0.14.0-234-g9354262b1-dirty) compiled with go1.19 on darwin/amd64`

How did you run restic exactly?
-------------------------------

~~~
export AZURE_ACCOUNT_NAME=storageaccountname
export AZURE_ACCOUNT_SAS='si=containername&spr=https&sv=2021-06-08&sr=c&sig=deadbeef'
export RESTIC_PASSWORD=password
restic -r azure:containername:/backup init
~~~

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

Azure Blob Storage

Expected behavior
-----------------

~~~
created restic repository f2b2e727bb at azure:containername:/backup

Please note that knowledge of your password is required to access
the repository. Losing your password means that your data is
irrecoverably lost.
~~~

Actual behavior
---------------

~~~
Fatal: create repository at azure:containername:/backup failed: container.CreateIfNotExists: storage: service returned error: StatusCode=403, ErrorCode=AuthorizationFailure, ErrorMessage=This request is not authorized to perform this operation.
RequestId:e0f0387b-701e-0037-26e0-efa955000000
Time:2022-11-03T23:57:40.3114536Z, RequestInitiated=Thu, 03 Nov 2022 23:57:39 GMT, RequestId=e0f0387b-701e-0037-26e0-efa955000000, API Version=2021-06-08, QueryParameterName=, QueryParameterValue=
~~~

Steps to reproduce the behavior
-------------------------------

In Azure Blob Storage, create a Storage Account, then in that SA create a Container, and in that *Container* create a Shared Access Token (which is basically the same thing as a Shared Access Signature that you can create on the Storage Account level), then run the commands above.

Do you have any idea what may have caused this?
-----------------------------------------------

This has nothing to do with the `/backup` path in the example - the symptoms are the same even with just `azure:containername:/` as the repository.

The problem seems to be that when using a SAS/SAT on the *container* level, there is no permission to perform actions that have to do with creating the container - the SAS/SAT is only allowed to poke around inside the existing container, which makes sense.

The Azure library restic uses calls `container.CreateIfNotExists` which is where things fail, because it tries to create a container, which is denied.

Do you have an idea how to solve the issue?
-------------------------------------------

In order to support SAS/SAT on a container level we must make the code not attempt to create a container (or similar), and instead just presume that it is there. The entire SAS/SAT can not have been created without the container already existing, in this case.

I guess we have two options to handle this:
- If creation of the *backend* fails (this is what fails here, `create(ctx, repo, gopts.extended)`), ignore this and somehow instantiate a backend anyway, then carry on and try to initialize a repository at that backend (`s.Init(ctx, version, gopts.password, chunkerPolynomial)`). Not sure how feasible and clean this is.
- Inspect the `AZURE_ACCOUNT_SAS` value and determine if it's an account- or container-level SAS/SAT, and depending on that do or skip the backend creation before initializing a repository on the backend. We'd still need to instantiate a backend in the code, so I'm not sure how to do that cleanly either. Perhaps it's simple.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Always 👍

---

EDIT: A workaround is to temporarily use an account-level SAS (or the regular account key, if one fancies that instead) for the `restic init` and after that use the container-level SAS/SAT as usual for the other restic commands (works fine since they won't try to create the container).

### PR DESCRIPTION
**Pull request by Seefin**
What does this PR change? What problem does it solve?
-----------------------------------------------------
This change ignores the Authorization Failed error returned from the Azure Storage Account backend when attempting to use a Shared Access Signature token that was **not** created with the Storage Account key to initalise a new repository.

The issue is caused by the Azure library that we use in the backend. When enumerating the container properties, the library internally calls `container.CreateIfNotExists` which is where things fail, because it tries to create a container, which is denied, as the token doesn'thave permission to create new containers, only poke around in the container it was made for.

Was the change previously discussed in an issue or on the forum?
----------------------------------------------------------------

Closes #4004

Checklist
---------

- [x] I have read the [contribution guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches).
- [x] I have [enabled maintainer edits](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [x] I have added tests for all code changes.
- [ ] I have added documentation for relevant changes (in the manual).
- [x] There's a new file in `changelog/unreleased/` that describes the changes for our users (see [template](https://github.com/restic/restic/blob/master/changelog/TEMPLATE)).
- [x] I have run `gofmt` on the code in all commits.
- [x] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits).
- [x] I'm done! This pull request is ready for review.

### CODE REVIEW

File: internal/backend/azure/azure.go [hunk 1]
```diff
@@ -157,6 +157,13 @@ func Create(ctx context.Context, cfg Config, rt http.RoundTripper) (*Backend, er
 		if err != nil {
 			return nil, errors.Wrap(err, "container.Create")
 		}
+	} else if err != nil && bloberror.HasCode(err, bloberror.AuthorizationFailure) {
+		// We ignore this Auth. Failure, as the failure is related to the type
+		// of SAS/SAT, not an actual real failure. If the token is invalid, we
+		// fail later on anyway.
+		// For details see Issue #4004.
+		debug.Log("Ignoring AuthorizationFailure when calling GetProperties")
+		err = nil
```
Comment (MichaelEischer) [inline internal/backend/azure/azure.go:166]: Assigning `nil` here is actually redundant, so let's remove it to make the linter happy.

File: changelog/unreleased/issue-4004 [hunk 2]
```diff
@@ -0,0 +1,12 @@
+Bugfix: Allow use of container level SAS/SAT tokens with Azure backend.
```
Comment (MichaelEischer) [inline changelog/unreleased/issue-4004:1]: The summary must not end with a punctuation character.

**Review by MichaelEischer — COMMENTED** [review]
I have two small nits, otherwise LGTM.

File: internal/backend/azure/azure.go (hunk 1 above)
Comment (Seefin) [reply internal/backend/azure/azure.go]: Easy, I'll remove

File: changelog/unreleased/issue-4004 (hunk 2 above)
Comment (Seefin) [reply changelog/unreleased/issue-4004]: Easy, I'll remove

**Review by MichaelEischer — APPROVED** [review]
LGTM. Thanks for fixing this issue!

**Comment by MichaelEischer** [comment]
I've slightly squashed the commits, without changing anything: https://github.com/restic/restic/compare/16d0ab6f4e1ceaf35c2bcbf108b3e8f6e7a9ae34..b434f560cc53b074c23f4aad1619014f0f9be465

**Comment by Seefin** [comment]
> I've slightly squashed the commits, without changing anything: https://github.com/restic/restic/compare/16d0ab6f4e1ceaf35c2bcbf108b3e8f6e7a9ae34..b434f560cc53b074c23f4aad1619014f0f9be465

Fair enough! Happy to have been able to be some help.
