### PR TITLE
Json check

### LINKED ISSUE #1378: JSON Output for restic check command
## Output of `restic version`

restic 0.7.3
compiled with go1.9 on linux/amd64

## How did you run restic exactly?
restic -r rest:path check --json

## What backend/server/service did you use?
rest-server

## Expected behavior

A JSON array containing information about the check results, at least something like "errors":0 oder "errors":1 would be sufficient for me

## Actual behavior

no json output given

## Steps to reproduce the behavior
Just use restic with check command and json flag

### PR DESCRIPTION
**Pull request by darkdragon-001**
What does this PR change? What problem does it solve?
-----------------------------------------------------

Add JSON output to the `check` command.

Was the change previously discussed in an issue or on the forum?
----------------------------------------------------------------

Fixes #1378
Closes #4581

Checklist
---------

- [ ] I have added tests for all code changes.
- [x] I have added documentation for relevant changes (in the manual).
- [x] There's a new file in `changelog/unreleased/` that describes the changes for our users (see [template](https://github.com/restic/restic/blob/master/changelog/TEMPLATE)).
- [x] I'm done! This pull request is ready for review.

### CODE REVIEW

**Comment by darkdragon-001** [comment]
I am not sure about the last commit: Do we want to assemble such an extensive summary or are we fine with just wrapping the errors into JSON?

File: cmd/restic/cmd_check.go [hunk 1]
```diff
@@ -479,3 +506,15 @@ func selectRandomPacksByFileSize(allPacks map[restic.ID]int64, subsetSize int64,
...
 	return packs
 }
+
+type checkResult struct {
+	Error           bool     `json:"error"`
+	NumIndexErrors  int      `json:"num_index_errors"`
+	NumPackErrors   int      `json:"num_pack_errors"`
+	NumTreeErrors   int      `json:"num_tree_errors"`
+	NumUnusedBlobs  int      `json:"num_unused_blobs"`
+	NumDataErrors   int      `json:"num_data_errors"`
```
Comment (darkdragon-001) [inline cmd/restic/cmd_check.go:516]: Should we merge these?
```suggestion
	NumErrors       int     `json:"num_errors"`
```

File: cmd/restic/cmd_check.go [hunk 2]
```diff
@@ -479,3 +506,15 @@ func selectRandomPacksByFileSize(allPacks map[restic.ID]int64, subsetSize int64,
...
+	BrokenPacks     []string `json:"broken_packs"`         // run "restic repair packs ID..." and "restic repair snapshots --forget" to remove damaged files
+	HintRepairIndex bool     `json:"suggest_repair_index"` // run "restic repair index"
+	HintPrune       bool     `json:"suggest_prune"`        // run "restic prune"
```
Comment (darkdragon-001) [inline cmd/restic/cmd_check.go:519]: Do we want these hints?

File: cmd/restic/cmd_check.go [hunk 3]
```diff
@@ -479,3 +506,15 @@ func selectRandomPacksByFileSize(allPacks map[restic.ID]int64, subsetSize int64,
...
 }
+
+type checkResult struct {
+	Error           bool     `json:"error"`
+	NumIndexErrors  int      `json:"num_index_errors"`
+	NumPackErrors   int      `json:"num_pack_errors"`
+	NumTreeErrors   int      `json:"num_tree_errors"`
+	NumUnusedBlobs  int      `json:"num_unused_blobs"`
+	NumDataErrors   int      `json:"num_data_errors"`
+	BrokenPacks     []string `json:"broken_packs"`         // run "restic repair packs ID..." and "restic repair snapshots --forget" to remove damaged files
```
Comment (darkdragon-001) [inline cmd/restic/cmd_check.go:517]: Do we want these IDs in the status or does this encourage people to script such destructive commands?

File: cmd/restic/cmd_check.go [hunk 4]
```diff
@@ -346,22 +368,25 @@ func runCheck(ctx context.Context, opts CheckOptions, gopts GlobalOptions, args
 		if err != nil {
 			return err
 		}
+		result.NumUnusedBlobs = len(unused)
```
Comment (MichaelEischer) [inline cmd/restic/cmd_check.go:371]: Checking for unused blobs can only be used by tests. So I don't think we should expose that number via the JSON output.

File: cmd/restic/cmd_check.go [hunk 5]
```diff
@@ -316,16 +336,18 @@ func runCheck(ctx context.Context, opts CheckOptions, gopts GlobalOptions, args
...
+	result.NumTreeErrors = 0
 	for err := range errChan {
 		errorsFound = true
 		if e, ok := err.(*checker.TreeError); ok {
 			printer.E("error for tree %v:\n", e.ID.Str())
 			for _, treeErr := range e.Errors {
+				result.NumTreeErrors++
 				printer.E("  %v\n", treeErr)
 			}
 		} else {
```
Comment (MichaelEischer) [inline cmd/restic/cmd_check.go:353]: The `printer.E` below is not accounted for.

File: cmd/restic/cmd_check.go (hunk 1 above)
Comment (MichaelEischer) [reply cmd/restic/cmd_check.go:516]: There's at least the category of snapshot errors missing. The main question here is what one can do with  knowing that there are 5 data errors in contrast to 5 index errors. In regards to index errors one could run `repair index` but giving you that information is the task of `suggest_repair_index`. So, I'm leaning somewhat towards only keeping the overall number of errors.

Comment (MichaelEischer) [inline cmd/restic/cmd_check.go:516]: What is a `data` error in contrast to a `pack` error? Both refer to pack files.

File: cmd/restic/cmd_check.go (hunk 3 above)
Comment (MichaelEischer) [reply cmd/restic/cmd_check.go:517]: Well, finding the commands in the output is already possible. What I'm more worried about is that the means to repair a repository will likely evolve over time. Although we could just get rid of old JSON fields by stopping to use them once they are no longer relevant.

File: cmd/restic/cmd_check.go [hunk 6]
```diff
@@ -215,7 +222,13 @@ func runCheck(ctx context.Context, opts CheckOptions, gopts GlobalOptions, args
 		return errors.Fatal("the check command expects no arguments, only options - please see `restic help check` for usage and flags")
 	}
 
-	printer := newTerminalProgressPrinter(gopts.verbosity, term)
+	result := checkResult{}
+	var printer Printer
+	if !gopts.JSON {
+		printer = ui.NewMessage(term, gopts.verbosity)
+	} else {
+		printer = &progress.NoopPrinter{}
```
Comment (MichaelEischer) [inline cmd/restic/cmd_check.go:230]: Not printing the error message is not an option. Running check without seeing the errors returned by `check` is useless and prevent us and users from debugging the underlying issue.

**Review by MichaelEischer — CHANGES_REQUESTED** [review]
Letting the `check` command only print a summary just works if a repository is not damaged. For a damaged repository, **all** error messages must also be available in the JSON output, otherwise we'll end up in a situation where all relevant information is missing. The summary by itself is mostly useless when it comes to debug what is wrong with a repository.

I wouldn't be terribly opposed to having an error and warning output message that for now just includes the formatted text output. If necessary, we could introduce an "error_code" field in the future to allow for more automation.

File: cmd/restic/cmd_check.go (hunk 1 above)
Comment (darkdragon-001) [reply cmd/restic/cmd_check.go]: I merged this into a single error count.

File: cmd/restic/cmd_check.go (hunk 3 above)
Comment (darkdragon-001) [reply cmd/restic/cmd_check.go:508]: I interpret your message as "keep this information inside the JSON". Resolving.

File: cmd/restic/cmd_check.go (hunk 2 above)
Comment (darkdragon-001) [reply cmd/restic/cmd_check.go:510]: Same as https://github.com/restic/restic/pull/5194#discussion_r1938346612. Resolving.

File: cmd/restic/cmd_check.go [hunk 7]
```diff
@@ -157,13 +157,20 @@ func parsePercentage(s string) (float64, error) {
 	return p, nil
 }
 
+type Printer interface {
```
[the remark this answers is not in the document]
Comment (darkdragon-001) [reply cmd/restic/cmd_check.go:160]: There is a [`ui.Message` type](https://github.com/restic/restic/blob/536ebefff44a3278fda42550137ac0f15df8d2fe/internal/ui/message.go#L8-L11) but it is not an interface such that one replace the implementation.
There is the [`progress.Printer` interface](https://github.com/restic/restic/blob/536ebefff44a3278fda42550137ac0f15df8d2fe/internal/ui/progress/printer.go#L8-L15) which also requires `NewCounter(description string) *Counter` method. As we don't need the `NewCounter()` method here, I preferred declaring another interface which is compatible with existing types.

File: cmd/restic/cmd_check.go [hunk 8]
```diff
@@ -243,26 +256,26 @@ func runCheck(ctx context.Context, opts CheckOptions, gopts GlobalOptions, args
 	}
 
 	errorsFound := false
-	suggestIndexRebuild := false
-	mixedFound := false
+	result.HintRepairIndex = false
```
[the remark this answers is not in the document]
Comment (darkdragon-001) [reply cmd/restic/cmd_check.go]: Removed this unnecessary initialization.

File: cmd/restic/cmd_check.go (hunk 4 above)
Comment (darkdragon-001) [reply cmd/restic/cmd_check.go]: Removed this field from the JSON output.

File: cmd/restic/cmd_check.go (hunk 5 above)
Comment (darkdragon-001) [reply cmd/restic/cmd_check.go:349]: I now also increment the unified errors count in the `else` clause.

Would this be the "snapshot error" type as mentioned in https://github.com/restic/restic/pull/5194#discussion_r1938346379?

File: doc/075_scripting.rst [hunk 9]
```diff
@@ -245,6 +245,32 @@ are stored in JSON form. Specifying ``--json``  or ``--quiet`` will suppress any
 non-JSON messages the command generates.
 
 
+check
+-----
+
+The ``check`` command outputs JSON messages with the following format:
```
[the remark this answers is not in the document]
Comment (darkdragon-001) [reply doc/075_scripting.rst:251]: I added the `message_type` field.

File: cmd/restic/cmd_check.go (hunk 1 above)
Comment (darkdragon-001) [reply cmd/restic/cmd_check.go]: I unified the error counts per https://github.com/restic/restic/pull/5194#discussion_r1899856559.

File: cmd/restic/cmd_check.go (hunk 6 above)
Comment (darkdragon-001) [reply cmd/restic/cmd_check.go:230]: With the `broken_packs`, `suggest_repair_index` and `suggest_repair_index` fields, the JSON output is actionable without the specific error messages.

As an alternative, in https://github.com/restic/restic/pull/5194#issuecomment-2565986326, I suggested dropping the last commit such that this PR is basically f7d567349b6efc60579e358dc49b52ae53e63311. Please let me know if you prefer to follow this approach.

**Comment by darkdragon-001** [comment]
@MichaelEischer Thanks for your review! I acted upon all threads. Please take another look.

File: cmd/restic/cmd_check.go (hunk 6 above)
Comment (MichaelEischer) [reply cmd/restic/cmd_check.go:230]: > With the `broken_packs`, `suggest_repair_index` and `suggest_repair_index` fields, the JSON output is actionable without the specific error messages.

Only for a few trivial cases. Quite a few of the check errors that show up in forum require manual intervention by the user. But without the detailed error messages that would be impossible to tell. In fact, without the error message, `check` degrades to something that essentially just says that it is broken, but without providing any details. Such settings are incredibly annoying to debug (both for the user themselves and by someone else in the forum). (running `check` as second time without `--json` also isn't an option as errors can be transient)

The `checkError` message from https://github.com/restic/restic/commit/f7d567349b6efc60579e358dc49b52ae53e63311 looks more like what I had in mind. Keeping the more detailed `checkResult` summary message type and such an error message don't exclude each other.

File: cmd/restic/cmd_check.go [hunk 10]
```diff
@@ -271,6 +282,8 @@ func runCheck(ctx context.Context, opts CheckOptions, gopts GlobalOptions, args
 			printer.E("error: %v\n", err)
 		}
 
+		result.NumErrors += len(errs)
+		result.HintRepairIndex = true
 		printer.E("\nThe repository index is damaged and must be repaired. You must run `restic repair index' to correct this.\n\n")
 		return errors.Fatal("repository contains errors")
```
Comment (MichaelEischer) [inline cmd/restic/cmd_check.go:288]: `result` is never printed  in this case.

File: cmd/restic/cmd_check.go [hunk 11]
```diff
@@ -316,7 +333,7 @@ func runCheck(ctx context.Context, opts CheckOptions, gopts GlobalOptions, args
 	wg.Add(1)
 	go func() {
 		defer wg.Done()
-		bar := newTerminalProgressMax(!gopts.Quiet, 0, "snapshots", term)
+		bar := newTerminalProgressMax(!gopts.Quiet && !gopts.JSON, 0, "snapshots", term)
```
Comment (MichaelEischer) [inline cmd/restic/cmd_check.go:336]: should use `bar := printer.NewCounter("snapshots")`. I forgot to convert the progress bars when switching `check` to `printer.Progress`.

File: cmd/restic/cmd_check.go [hunk 12]
```diff
@@ -479,3 +500,11 @@ func selectRandomPacksByFileSize(allPacks map[restic.ID]int64, subsetSize int64,
 	packs := selectRandomPacksByPercentage(allPacks, subsetPercentage)
 	return packs
 }
+
+type checkResult struct {
+	MessageType     string   `json:"message_type"`
```
Comment (MichaelEischer) [inline cmd/restic/cmd_check.go:505]: Add a comment that the expected message type is `summary`.

File: cmd/restic/cmd_check.go (hunk 5 above)
Comment (MichaelEischer) [reply cmd/restic/cmd_check.go:349]: Those error include the "snapshot error" type, but probably also some other errors.

**Review by MichaelEischer — CHANGES_REQUESTED** [review]
Thanks for the changes so far! I have a few more comments.

File: cmd/restic/cmd_check.go (hunk 7 above)
[the remark this answers is not in the document]
Comment (darkdragon-001) [reply cmd/restic/cmd_check.go:160]: Using `ui.NewMessage()` seems more appropriate and lightweight if we don't need a progress printer.

In f7d567349b6efc60579e358dc49b52ae53e63311 I also added a custom printer type to collect the error messages. I can use a no-op `NewCounter()` method there if you prefer.

File: cmd/restic/cmd_check.go (hunk 6 above)
Comment (darkdragon-001) [reply cmd/restic/cmd_check.go:230]: If it requires manual intervention, running the check manually without `--json` seems appropriate (if the errors are transient, there shouldn't be the need for manual intervention).

File: cmd/restic/cmd_check.go (hunk 12 above)
Comment (darkdragon-001) [reply cmd/restic/cmd_check.go:505]: Done

File: cmd/restic/cmd_check.go (hunk 11 above)
Comment (darkdragon-001) [reply cmd/restic/cmd_check.go]: Done in 2b1686d6694cb0c5f676b9dadbb6c6c443c704f8.

File: cmd/restic/cmd_check.go (hunk 7 above)
[the remark this answers is not in the document]
Comment (darkdragon-001) [reply cmd/restic/cmd_check.go]: I switched to using the `progress.Printer` interface.

File: cmd/restic/cmd_check.go (hunk 10 above)
Comment (darkdragon-001) [reply cmd/restic/cmd_check.go]: The summary wasn't printed in any of the early returns. I added 1a2b9ba37ed0309d42b2cede8836fe99cf9f9d56 to always print the summary JSON.

File: cmd/restic/cmd_check.go (hunk 6 above)
Comment (darkdragon-001) [reply cmd/restic/cmd_check.go]: I now keep printing the error messages in JSON as well.

File: cmd/restic/cmd_check.go (hunk 11 above)
Comment (darkdragon-001) [reply cmd/restic/cmd_check.go]: FYI: I cannot use this approach for "packs" as this uses `packCount` instead of `0`.

**Comment by darkdragon-001** [comment]
@MichaelEischer I addressed all remaining comments. Could you please take another look?

File: doc/075_scripting.rst [hunk 13]
```diff
@@ -245,6 +245,38 @@ are stored in JSON form. Specifying ``--json``  or ``--quiet`` will suppress any
...
+
+Error
+^^^^^
+
+These errors are printed on ``stderr``.
+
++----------------------+-------------------------------------------+
+| ``message_type``     | Always "error"                            |
++----------------------+-------------------------------------------+
+| ``message``          | Error message                             |
```
Comment (MichaelEischer) [inline doc/075_scripting.rst:276]: Please add a warning that the message `May change in arbitrary ways across restic versions`.

File: cmd/restic/cmd_check.go [hunk 14]
```diff
@@ -355,13 +372,14 @@ func runCheck(ctx context.Context, opts CheckOptions, gopts GlobalOptions, args
 	doReadData := func(packs map[restic.ID]int64) {
 		packCount := uint64(len(packs))
 
-		p := newTerminalProgressMax(!gopts.Quiet, packCount, "packs", term)
+		p := newTerminalProgressMax(!gopts.Quiet && !gopts.JSON, packCount, "packs", term)
```
Comment (MichaelEischer) [inline cmd/restic/cmd_check.go:375]:
```suggestion
		p := printer.NewCounter("packs")
		p.SetMax(uint64(len(packs)))
```

File: cmd/restic/cmd_check.go [hunk 15]
```diff
@@ -45,7 +46,11 @@ Exit status is 12 if the password is incorrect.
 	RunE: func(cmd *cobra.Command, args []string) error {
 		term, cancel := setupTermstatus()
 		defer cancel()
-		return runCheck(cmd.Context(), checkOptions, globalOptions, args, term)
+		summary, err := runCheck(cmd.Context(), checkOptions, globalOptions, args, term)
+		if globalOptions.JSON {
+			term.Print(ui.ToJSONString(summary))
```
Comment (MichaelEischer) [inline cmd/restic/cmd_check.go:51]: If check fails, then the summary should IMHO always return a non-zero number of errors. I'm pretty sure that everyone is going to check the exit code even though that's absolutely necessary.
```suggestion
			if err != nil && summary.NumErrors == 0 {
				summary.NumErrors = 1
			}
			term.Print(ui.ToJSONString(summary))
```

**Review by MichaelEischer — CHANGES_REQUESTED** [review]
I have a few more small nits, but then we should be done.

File: doc/075_scripting.rst (hunk 13 above)
Comment (darkdragon-001) [reply doc/075_scripting.rst]: Done.

_FYI: I previously just copied it from other commands which do not have this addition._

File: cmd/restic/cmd_check.go (hunk 15 above)
Comment (darkdragon-001) [reply cmd/restic/cmd_check.go:54]: Done.

_FYI: I had this in a previous version but then decided against it and only count errors arising from a broken repository but not from a failing check action._

File: cmd/restic/cmd_check.go (hunk 14 above)
Comment (MichaelEischer) [reply cmd/restic/cmd_check.go:378]: passing the maximum value to `newTerminalProgressMax` or setting it via `SetMax` is equivalent

File: cmd/restic/cmd_check.go (hunk 15 above)
Comment (MichaelEischer) [reply cmd/restic/cmd_check.go:54]: I'm aware it isn't ideal. But making sure that users noticed failed check runs has priority

File: cmd/restic/cmd_check.go (hunk 14 above)
Comment (darkdragon-001) [reply cmd/restic/cmd_check.go]: I only now noticed the `p.SetMax()` call and fixed it. Done.

**Review by MichaelEischer — APPROVED** [review]
LGTM. Thanks!
