### PR TITLE
Make `restic mount` faster and consume less memory

### LINKED ISSUE #1680: Horrible fuse mount performance on large repo with many small files
## Output of `restic version`
```
restic 0.8.3 (a05bd98)
compiled with go1.10 on linux/amd64
```

## How did you run restic exactly?
`restic -r sftp:HOSTNAME:/path/to/restic/repo -p PASSWORD_FILE mount /path/to/mnt/point`
And
`restic -r sftp:HOSTNAME:/path/to/restic/repo -p PASSWORD_FILE --no-cache mount /path/to/mnt/point`

## What backend/server/service did you use to store the repository?
SFTP over Internet with high speed (100 Mbps, ping <25ms) access between the client and server

## Expected behavior
Randomly read small files with a reasonable latency (e.g. within a few seconds), and consumes reasonable amount of RAM and CPU resource.

## Actual behavior
With the cache, random reading small files (e.g.: `cat mountpoint/snapshots/latest/path/to/small/file.ext`) between a few bytes to a few MB takes many minutes because restic downloads entire pack file(s) (size between a few MB to many hundred MB) to the cache directory before serving the read request.
Without the cache, random reading small files in small directory is a lot faster. However when the directory contains millions of small files, the latency goes up to many minutes per file regardless of the files size.

Either way, the memory consummation and CPU usage are crappy, it uses all of the available memory on the client side (12.3GB out of 16GB physical RAM, the remaining memory are used by other applications), and the CPU usage often goes up to and stays at 100% for more than half a minute. The CPU usage is worse when `--no-cache` is given.

In addition to above, the disk usage with cache enabled is also concerning me, randomly access a few files resulted in a multi GB cache directory. I'm not sure if the cache size will go up linearly when more files are accessed.

## Steps to reproduce the behavior
Backup a 12TB directory with 65 million files spread in nearly 700 subdirectories. Then use `restic mount` from a different server, and randomly access the files in the mount point.

This is to simulate a disaster recovery scenario, where the main server which hosts the multi TB of data fails, and to keep the business going, we use a new server to do fuse mount and temporarily serve the files from it while we are restoring files to a different server.

## Do you have any idea what may have caused this?
For the memory issue, probably the golang GC? this is just a wild guess.
For the CPU issue, I think restic is decrypting (and then discarding?) extremely large amount of data.
For the latency, my guess is, with the cache restic spend time to download the entire pack files instead of only the needed part; without the cache restic spend time to download the index and decrypt it over and over again.

## Do you have an idea how to solve the issue?
With cache enabled, only download (and cache) the required data for accessing a file, not the whole pack file. This is certainly doable, but will require the local cache structure change (but this does not break the backward compatibility, it's only a cache)
Without cache, do we really need to download the index over and over again? And is it necessary to download and decrypt whole index files? Can we download only part of it? (Sorry, I haven't read the code or doc about the index structure)

Also we will need a proper cache management. For example, cache eviction policy, size limit, disk full handling (which is filled up by the cache in my case, nearly 30GB cache on a 40GB root partition).

## Did restic help you or made you happy in any way?
I'm not sure about this yet, we are currently looking for solutions allow us to backup more than 50TB of data with ~32% of duplications, data size increasing a few hundred GB daily (new files only, existing files are never changed). We will need to be able to recover from the main storage server failure fast enough to not affect users badly.
We've looked at a lots of different software solutions, and have only tested restic yet, because it is the only one supports B2 backend (cheap and faster retrieval time than Glacier) AND has deduplication AND allows mount.

### PR DESCRIPTION
**Pull request by aawsome**
What is the purpose of this change? What does it change?
--------------------------------------------------------

In the FUSE implementation restic data structure have been read (meaning loading blobs from the repository) and internal data structures have been created when a FUSE "node" was created. This was the case, for instance, for all item within a dir when this dir was accessed. This lead to quite some memory usage and made the FUSE filesystem "unresponsive". 

This PR changes this behavior and only reads restic data structure when the information is really needed. Moreover, the internal data structure have been optimized. Also concurrent operation within FUSE should now work correctly. (FUSE documentation says that access should be synced which wasn't)

Was the change discussed in an issue or in the forum before?
------------------------------------------------------------
closes #1680 

Thanks @greatroar for issuing #2585 which makes me think about whether the bottleneck really is only reading tree blobs.

Checklist
---------

- [X] I have read the [Contribution Guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches)
- I have not added tests for all changes in this PR
- I have not added documentation for the changes (in the manual)
- [X] There's a new file in `changelog/unreleased/` that describes the changes for our users (template [here](https://github.com/restic/restic/blob/master/changelog/TEMPLATE))
- [X] I have run `gofmt` on the code in all commits
- [X] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits)
- [X] I'm done, this Pull Request is ready for review

### CODE REVIEW

File: internal/fuse/file.go [hunk 1]
```diff
@@ -111,6 +90,27 @@ func (f *file) Read(ctx context.Context, req *fuse.ReadRequest, resp *fuse.ReadR
 	debug.Log("Read(%v, %v, %v), file size %v", f.node.Name, req.Size, req.Offset, f.node.Size)
 	offset := req.Offset
 
+	if !f.hasSizes {
```
Comment (greatroar) [inline internal/fuse/file.go]: Shouldn't this be protected by a lock? Or does FUSE handle that?

Comment (greatroar) [reply internal/fuse/file.go]: Never mind. FUSE calls Lookup, and Lookup returns a fresh *file every time. So this is safe.

Comment (aawsome) [reply internal/fuse/file.go]: Thanks for researching! I wasn't sure about how FUSE handles concurrency, but `getBlobAt` also seems not to be concurrency-safe, so I assumed it would be handled by FUSE...

Comment (greatroar) [reply internal/fuse/file.go]: Actually, I failed to spot that the bazil.org/fuse package stores the node it gets from Lookup in a cache, and it's concurrent. So there really should be locks all over internal/fuse.

Comment (greatroar) [reply internal/fuse/file.go]: False alarm. It looks like the kernel driver will synchronize access, as long as you don't set the AsyncRead MountOption. I've empirically verified this by setting minSnapshotsReloadTime to 0, running restic mount with the race detector on, reading the snapshots directory concurrently in two loops and adding snapshots.

Comment (MichaelEischer) [reply internal/fuse/file.go]: The documentation of bazil/fuse actually says that synchronization is required (see https://godoc.org/bazil.org/fuse#hdr-Service_Methods):

> Multiple goroutines may call service methods simultaneously; the methods being called are responsible for appropriate synchronization.

I'd assume that some caching in the kernel effectively synchronizes access, but it probably not a good idea to rely on it.

**Comment by MichaelEischer** [comment]
It might be an option to implement the `NodeOpener` which is called when a file is opened. That way the chunk size collection would happen immediately when opening a file and is not delayed until reading the first bytes.

The main difference is the point in time when the user would be notified in case some blobs are missing. The current implementation in restic probably fails with an error before providing any details on the file node, with the change this is delayed until the first bytes are read. I think that the new semantic is actually what a user would expect: Reading a damaged file fails, but usually you are able to see the metadata.

File: internal/fuse/file.go (hunk 1 above)
Comment (aawsome) [reply internal/fuse/file.go]: I added a Mutex to synchronize access

**Comment by aawsome** [comment]
@MichaelEischer Thanks for searching the manual and offering the NodeOpener option which I'm using now.
I tried to do performance tests of this new version but did not really succeed to see differences when comparing this to. In fact it seems that there a lot of variation w.r.t. performance when using FUSE (maybe some kernel caching?)...
Is there anyone who can help out with testing this change?

Memory footprint is however clearly reduced.

**Comment by ProactiveServices** [comment]
@aawsome Happy to help, do you have any specific tests you'd like to perform? I have several hundred-gig repos I can test with.

**Comment by aawsome** [comment]
@ProactiveServices Thank you very much! I'm especially interested in response times and CPU usage and comparison between "plain" restic and a version including this PR.
The code changes should apply for listing and reading files, e.g. `ls file` or `cat file`/`cp file somewhere`.

I used `/usr/bin/time restic mount` to get CPU timings and a simple `time` before the commands, e.g. `time ls file` to get response times.

**Comment by aawsome** [comment]
With the last commit, also dir operations should be faster (and a bit less memory consuming)...

File: internal/fuse/file.go [hunk 2]
```diff
@@ -20,47 +21,31 @@ import (
 const blockSize = 512
 
 // Statically ensure that *file implements the given interface
```
Comment (greatroar) [inline internal/fuse/file.go]: This comment is now stale because one of the checks is for *openFile. You could update it, but removing it may be easier.

File: internal/fuse/file.go [hunk 3]
```diff
@@ -136,9 +138,20 @@ func (f *file) Read(ctx context.Context, req *fuse.ReadRequest, resp *fuse.ReadR
...
+
+	// The documentation of bazil/fuse actually says that synchronization is
+	// required (see https://godoc.org/bazil.org/fuse#hdr-Service_Methods):
+	//
+	// Multiple goroutines may call service methods simultaneously;
+	// the methods being called are responsible for appropriate synchronization.
+	//
+	// Hence Lock to ensure operation on blobs is not done concurrently
+	// (doesn't work with cached blob in getBlobAt)
+	f.m.Lock()
```
Comment (greatroar) [inline internal/fuse/file.go]: defer f.m.Unlock()? There are multiple exits, and lack of memory can cause a panic.

**Comment by aawsome** [comment]
rebased to master and added the changes suggested by @greatroar

File: internal/fuse/file.go (hunk 2 above)
Comment (aawsome) [reply internal/fuse/file.go]: the comment is now updated.

File: internal/fuse/file.go (hunk 3 above)
Comment (aawsome) [reply internal/fuse/file.go:146]: is changed.

**Comment by aawsome** [comment]
Rebased this PR after #2790 has been merged.

**Comment by aawsome** [comment]
Noticed that the new blob cache by @greatroar already implements locking; hence I removed the locks from `file.go` and just left a comment there.

**Comment by aawsome** [comment]
rebased after #2787 has been merged.

File: internal/fuse/dir.go [hunk 4]
```diff
@@ -20,10 +21,12 @@ var _ = fs.NodeStringLookuper(&dir{})
 
 type dir struct {
 	root        *Root
-	items       map[string]*restic.Node
 	inode       uint64
 	parentInode uint64
 	node        *restic.Node
+	isOpen      bool
```
Comment (MichaelEischer) [inline internal/fuse/dir.go:27]: `isOpen` seems redundant. Afaict `isOpen` == `items != nil`

File: internal/fuse/dir.go [hunk 5]
```diff
@@ -72,35 +65,48 @@ func replaceSpecialNodes(ctx context.Context, repo restic.Repository, node *rest
...
+			ModTime:    snapshot.Time,
+			ChangeTime: snapshot.Time,
+			Mode:       os.ModeDir | 0555,
+			Subtree:    snapshot.Tree,
+		},
+		inode: inode,
+	}, nil
+}
+
+func (d *dir) Open() error {
```
Comment (MichaelEischer) [inline internal/fuse/dir.go:81]: Is this `Open` method used by any external caller or just internally by ReadDirAll and Lookup? In the latter case please change the signature to `func (d *dir) open(ctx context.Context) error`. That avoid also the problematic use of `context.TODO()`

File: internal/fuse/dir.go [hunk 6]
```diff
@@ -133,6 +139,11 @@ func (d *dir) calcNumberOfLinks() uint32 {
 
 func (d *dir) ReadDirAll(ctx context.Context) ([]fuse.Dirent, error) {
 	debug.Log("ReadDirAll()")
+	err := d.Open()
+	if err != nil {
+		return nil, err
+	}
+	debug.Log("called")
```
Comment (MichaelEischer) [inline internal/fuse/dir.go:146]: I think we can remove that `debug.Log` call

File: internal/fuse/dir.go [hunk 7]
```diff
@@ -170,6 +181,10 @@ func (d *dir) ReadDirAll(ctx context.Context) ([]fuse.Dirent, error) {
 }
 
 func (d *dir) Lookup(ctx context.Context, name string) (fs.Node, error) {
+	err := d.Open()
+	if err != nil {
+		return nil, err
+	}
 	debug.Log("Lookup(%v)", name)
```
Comment (MichaelEischer) [inline internal/fuse/dir.go:188]: please move the `debug.Log` call above `d.Open()`

File: changelog/unreleased/issue-1680 [hunk 8]
```diff
@@ -0,0 +1,7 @@
+Enhancement: Optimize `restic mount`
+
+We've optimized the FUSE implementation used within restic.
+`restic mount` is now more responsive and uses less memory.
+
+https://github.com/restic/restic/issues/1680
+https://github.com/restic/restic/pull/2587
```
[the remark this answers is not in the document]
Comment (aawsome) [reply changelog/unreleased/issue-1680:7]: is added.

File: internal/fuse/dir.go [hunk 9]
```diff
@@ -20,10 +21,12 @@ var _ = fs.NodeStringLookuper(&dir{})
 
 type dir struct {
 	root        *Root
-	items       map[string]*restic.Node
 	inode       uint64
 	parentInode uint64
 	node        *restic.Node
+	isOpen      bool
+	m           sync.Mutex
+	items       map[string]*restic.Node
```
[the remark this answers is not in the document]
Comment (aawsome) [reply internal/fuse/dir.go]: changed.

File: internal/fuse/dir.go (hunk 4 above)
Comment (aawsome) [reply internal/fuse/dir.go]: Ah - thanks for the hint! Changed it.

File: internal/fuse/dir.go (hunk 5 above)
Comment (aawsome) [reply internal/fuse/dir.go]: changed it to `open(context.Context)`

File: internal/fuse/dir.go (hunk 6 above)
Comment (aawsome) [reply internal/fuse/dir.go]: yes - this was just to debug; is removed.

File: internal/fuse/dir.go (hunk 7 above)
Comment (aawsome) [reply internal/fuse/dir.go]: is changed.

**Review by MichaelEischer — APPROVED** [review]
LGTM. I've force-pushed the branch to retrigger the CI. Seems like the flaky rclone test error has changed into a flaky rclone test crash, after #2855.
