### PR TITLE
backup: Fix reporting of directory count in summary

### LINKED ISSUE #1863: backup statistics: wrong number of Dirs!
## Output of `restic version`
restic 0.9.1 compiled with go1.10.3 on linux/amd64

## How did you run restic exactly?
`restic -r restictest backup oxygen`

## What backend/server/service did you use to store the repository?
local folder

## Expected behavior
```
$ restic -r restictest init
$ restic -r restictest backup oxygen
 Files:       45629 new,     0 changed,     0 unmodified
 Dirs:     12549 new,     0 changed,     0 unmodified
 Added:      140.442 MiB
$ find oxygen -type d | wc -l
 12549
$ mkdir oxygen/testdir
$ echo "test" > oxygen/testdir/test.txt
$ find oxygen -type d | wc -l
 12550
$ restic -r restictest backup oxygen
Files:           1 new,     0 changed, 45629 unmodified
Dirs:            1 new,     0 changed, 12549 unmodified
Added:      376 B
```

## Actual behavior
```
$ restic -r restictest init
$ restic -r restictest backup oxygen
 Files:       45629 new,     0 changed,     0 unmodified
 Dirs:            0 new,     0 changed,     0 unmodified
 Added:      140.442 MiB
$ find oxygen -type d | wc -l
 12549
$ mkdir oxygen/testdir
$ echo "test" > oxygen/testdir/test.txt
$ find oxygen -type d | wc -l
 12550
$ restic -r restictest backup oxygen
Files:           1 new,     0 changed, 45629 unmodified
Dirs:            0 new,     0 changed,     0 unmodified
Added:      376 B
```

## Steps to reproduce the behavior
see above

## Do you have any idea what may have caused this?
Not really. Also not sure if it was different before since i started using restic only recently.

According to the docs, I assume it was working before:
http://restic.readthedocs.io/en/latest/040_backup.html

## Do you have an idea how to solve the issue?
Maybe some bug introduced with the new archiver?

## Did restic help you or made you happy in any way?
restic is super!

### PR DESCRIPTION
**Pull request by MichaelEischer**
What is the purpose of this change? What does it change?
--------------------------------------------------------
A backup run always reported that zero directories were backed-up.

Previously the directory stats were reported immediately after calling `SaveDir`. However, as the latter method saves the tree asynchronously the stats were still initialized to their nil value. The stats are now reported via a callback similar to the one used for the fileSaver.

Was the change discussed in an issue or in the forum before?
------------------------------------------------------------
Fixes #1863

Checklist
---------

- [x] I have read the [Contribution Guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches)
- [x] I have enabled [maintainer edits for this PR](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)
- [x] I have added tests for all changes in this PR
- ~~[ ] I have added documentation for the changes (in the manual)~~
- [x] There's a new file in `changelog/unreleased/` that describes the changes for our users (template [here](https://github.com/restic/restic/blob/master/changelog/TEMPLATE))
- [x] I have run `gofmt` on the code in all commits
- [x] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits)
- [x] I'm done, this Pull Request is ready for review

### CODE REVIEW

File: changelog/unreleased/issue-1863 [hunk 1]
```diff
@@ -0,0 +1,6 @@
+Fix: Report correct amount of directories processed by backup
```
Comment (rawtaz) [inline changelog/unreleased/issue-1863:1]: This must be "Bugfix" instead of "Fix".

Comment (rawtaz) [reply changelog/unreleased/issue-1863:1]: Also s/amount/number/

File: changelog/unreleased/issue-1863 [hunk 2]
```diff
@@ -0,0 +1,6 @@
...
+
+We have fixed the directory statistics calculation to report the actual amount
```
Comment (rawtaz) [inline changelog/unreleased/issue-1863:3]: s/amount/number/

File: internal/archiver/archiver_test.go [hunk 3]
```diff
@@ -959,6 +959,14 @@ func TestArchiverSaveDirIncremental(t *testing.T) {
 	}
 }
 
+// Equals fails the test if exp is not equal to act.
```
Comment (greatroar) [inline internal/archiver/archiver_test.go:962]: Copy-pasted comment?

File: internal/archiver/archiver_test.go [hunk 4]
```diff
@@ -959,6 +959,14 @@ func TestArchiverSaveDirIncremental(t *testing.T) {
...
+func bothNonZeroOrNot(tb testing.TB, exp, act uint64) {
+	if (exp == 0 && act != 0) || (exp != 0 && act == 0) {
+		_, file, line, _ := runtime.Caller(1)
+		tb.Fatalf("\033[31m%s:%d:\n\n\texp: %#v\n\n\tgot: %#v\033[39m\n\n", filepath.Base(file), line, exp, act)
+	}
+}
+
```
Comment (greatroar) [inline internal/archiver/archiver_test.go:969]: Isn't this just Equals(exp > 0, act > 0)?

File: changelog/unreleased/issue-1863 (hunk 1 above)
Comment (MichaelEischer) [reply changelog/unreleased/issue-1863]: Thanks

File: internal/archiver/archiver_test.go (hunk 4 above)
Comment (MichaelEischer) [reply internal/archiver/archiver_test.go:969]: Basically yes, however, the error message contains the full values of exp and act and not just true/false.

File: internal/archiver/archiver_test.go (hunk 3 above)
Comment (MichaelEischer) [reply internal/archiver/archiver_test.go]: Fixed.

File: internal/archiver/archiver_test.go (hunk 4 above)
Comment (greatroar) [reply internal/archiver/archiver_test.go:969]: Ok. I think a more obvious function name would be `notBothZero`. The comment could then be "notBothZero fails the test if only one of exp, act is zero" (the current comment has a grammatical error).

File: internal/archiver/archiver.go [hunk 5]
```diff
@@ -208,7 +208,7 @@ func (arch *Archiver) loadSubtree(ctx context.Context, node *restic.Node) *resti
 
 // SaveDir stores a directory in the repo and returns the node. snPath is the
 // path within the current snapshot.
-func (arch *Archiver) SaveDir(ctx context.Context, snPath string, fi os.FileInfo, dir string, previous *restic.Tree) (d FutureTree, err error) {
+func (arch *Archiver) SaveDir(ctx context.Context, snPath string, fi os.FileInfo, dir string, previous *restic.Tree, complete CompleteFunc) (d FutureTree, err error) {
```
Comment (greatroar) [inline internal/archiver/archiver.go:211]: Could the callback be a field on the Archiver instead?

Comment (MichaelEischer) [reply internal/archiver/archiver.go:211]: SaveDir misses two parameters used in the callback: `previous` and `time.Since(start)` these are captured in the function closure. The inspiration for the callback was the call to `arch.fileSaver.Save` which also uses a callback of the same type.

File: internal/archiver/archiver_test.go (hunk 4 above)
Comment (MichaelEischer) [reply internal/archiver/archiver_test.go:969]: Thanks for the suggestions.

File: changelog/unreleased/issue-1863 [hunk 6]
```diff
@@ -0,0 +1,6 @@
+Bugfix: Report correct number of directories processed by backup
+
+We have fixed the directory statistics calculation to report the actual number
+of processed directories instead of always zero.
```
Comment (rawtaz) [inline changelog/unreleased/issue-1863:4]: Keeping things neutral, I think adjusting this to the following would be a good idea:

~~~
The directory statistics calculation was fixed to report the actual number
of processed directories instead of always zero.
~~~

**Comment by rawtaz** [comment]
Is there anything left to do with this PR? Do you want it reviewed or is it fine to merge it?

File: changelog/unreleased/issue-1863 (hunk 6 above)
Comment (MichaelEischer) [reply changelog/unreleased/issue-1863]: Is changed.

**Comment by MichaelEischer** [comment]
@rawtaz As the PR only slightly delays a statistics callback and beyond that is nearly 90% boilerplate, it should be fine to merge.

**Review by fd0 — APPROVED** [review]
LGTM, thanks a lot for tackling this long-standing issue!
