### PR TITLE
Don't read password for generate, help or self-update

### LINKED ISSUE #2951: non-repo subcommands that don't need passwords still try to run RESTIC_PASSWORD_COMMAND
Output of `restic version`
--------------------------
restic 0.10.0 compiled with go1.15.2 on linux/amd64

How did you run restic exactly?
-------------------------------

This was my initial scenario -- I store my restic password in a password-store file which requires a hardware token to decrypt.  The token was not plugged in at the time that I was running the help command because I had no intention of performing any backup/restore operations at the time.  Had just updated to v0.10.0 and thought I'd look at the help output and update bash completions.
```
$ export RESTIC_PASSWORD_COMMAND='pass show my-restic-password'
$ restic help
Resolving password failed: exit status 1
```
This is easily reproduced with any password-command that fails, not specifically related to pass
```
$ export RESTIC_PASSWORD_COMMAND=/bin/false
$ restic help
Resolving password failed: exit status 1
```
Same behaviour for other commands that are unrelated to using a repository that might need a password for decryption
```
$ export RESTIC_PASSWORD_COMMAND=/bin/false
$ restic generate --bash-completion ~/.local/etc/bash_completion.d/restic.bash-completion
Resolving password failed: exit status 1
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
Not storing a repository at all yet, just trying to run `help` or `generate`.

Expected behavior
-----------------
I expected to be able to see the help output in the first command and to generate the tab-completions for bash in the second command.

The RESTIC_PASSWORD_COMMAND feature is really nice and works really well with password-store but it doesn't need to be evaluated for commands that don't require the password.

Actual behavior
---------------
I get an error about resolving passwords instead of seeing the output from `help` or `generate` -- non repo commands.

Steps to reproduce the behavior
-------------------------------

```
$ RESTIC_PASSWORD_COMMAND=/bin/false restic help
Resolving password failed: exit status 1
```

Do you have any idea what may have caused this?
-----------------------------------------------

Even though I was running subcommands that have no need for a password, code inspection shows that [main.go](https://github.com/restic/restic/blob/master/cmd/restic/main.go#L57) evaluates resolvePassword() for all subcommands (except version).  resolvePassword() tries to execute the RESTIC_PASSWORD_COMMAND.  This command fails due to a no hardware token being plugged in.

Do you have an idea how to solve the issue?
-------------------------------------------

One of these will solve the issue
* Move execution of resolvePassword() into each subcommand that needs a password
* Add a list of subcommands to main.go for which you skip running resolvePassword() 

It's easy enough to unset the env var as a workaround but it's not that initially obvious what's failing or why it even needs a password for `help`.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
Restic is awesome.  It works very well and is an important part of my backup strategy.  Thanks for all the work you put into this!

### PR DESCRIPTION
**Pull request by greatroar**
What does this PR change? What problem does it solve?
-----------------------------------------------------

restic generate, help and self-update don't touch any repo, so they don't need to check passwords (let alone run $RESTIC_PASSWORD_COMMAND). This extends the special handling of restic version to also work for those commands.

Was the change discussed in an issue or in the forum before?
------------------------------------------------------------

Fixes #2951.

Checklist
---------

- [x] I have read the [Contribution Guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches)
- [x] I have enabled [maintainer edits for this PR](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)
- [ ] I have added tests for all changes in this PR
- [ ] I have added documentation for the changes (in the manual)
- [x] There's a new file in `changelog/unreleased/` that describes the changes for our users (template [here](https://github.com/restic/restic/blob/master/changelog/TEMPLATE))
- [x] I have run `gofmt` on the code in all commits
- [x] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits)
- [x] I'm done, this Pull Request is ready for review

### CODE REVIEW

File: cmd/restic/main.go [hunk 1]
```diff
@@ -71,6 +71,17 @@ directories in an encrypted repository stored on different backends.
 	},
 }
 
+// Distinguish commands that need the password from those that work without
+// (#2951).
```
Comment (MichaelEischer) [inline cmd/restic/main.go:75]: I don't think we need a reference to the original issue here.

File: cmd/restic/main.go [hunk 2]
```diff
@@ -71,6 +71,17 @@ directories in an encrypted repository stored on different backends.
...
+func needsPassword(cmd string) bool {
+	switch cmd {
+	case "generate", "help", "self-update", "version":
```
Comment (MichaelEischer) [inline cmd/restic/main.go:78]: Please also add the "cache" and the (hidden) "options" command here.

File: changelog/unreleased/issue-2951 [hunk 3]
```diff
@@ -0,0 +1,9 @@
+Bugfix: restic generate, help and self-update no longer check passwords
+
+The commands restic generate, restic help and restic self-update don't need
```
Comment (MichaelEischer) [inline changelog/unreleased/issue-2951:3]: I think we don't need to repeat `restic` here multiple times. I'd also enclose the command names in backticks \` to highlight them in the changelog.

File: changelog/unreleased/issue-2951 [hunk 4]
```diff
@@ -0,0 +1,9 @@
...
+passwords, but they previously did run the RESTIC_PASSWORD_COMMAND (if set in
+the environment), prompting users to authenticate for no reason. They now skip
+the password command.
```
Comment (MichaelEischer) [inline changelog/unreleased/issue-2951:6]: s/the/running the/

**Review by MichaelEischer — CHANGES_REQUESTED** [review]

File: cmd/restic/main.go (hunk 1 above)
Comment (greatroar) [reply cmd/restic/main.go]: Replaced by something more of an explanation.

File: changelog/unreleased/issue-2951 (hunk 3 above)
Comment (greatroar) [reply changelog/unreleased/issue-2951]: Done.

File: changelog/unreleased/issue-2951 (hunk 4 above)
Comment (greatroar) [reply changelog/unreleased/issue-2951]: Done.

**Review by MichaelEischer — APPROVED** [review]
LGTM. Thanks!
