### PR TITLE
Make `key list` command honor `--no-lock`

### LINKED ISSUE #4513: `restic key --no-lock list` acquires a lock
Output of `restic version`
--------------------------

restic 0.16.0 compiled with go1.20.8 on freebsd/amd64

How did you run restic exactly?
-------------------------------

```
restic key list --no-lock
Save(<lock/807df3d3ba>) returned error, retrying after 305.705679ms: OpenFile: permission denied
Save(<lock/807df3d3ba>) returned error, retrying after 394.709517ms: OpenFile: permission denied
Save(<lock/807df3d3ba>) returned error, retrying after 1.424932044s: OpenFile: permission denied
Save(<lock/807df3d3ba>) returned error, retrying after 1.789063058s: OpenFile: permission denied
Save(<lock/807df3d3ba>) returned error, retrying after 3.022910059s: OpenFile: permission denied
Save(<lock/807df3d3ba>) returned error, retrying after 5.295456214s: OpenFile: permission denied
Save(<lock/807df3d3ba>) returned error, retrying after 3.19014686s: OpenFile: permission denied
  signal interrupt received, cleaning up
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

sftp

Expected behavior
-----------------

We use read-only users on the SFTP storage to allow certain recurring administrative tasks (like `snapshots`, `check`, etc.). The idea is that there is no risk to interfere with actual backups and also the ability to do this on file system snapshots (which are read-only by nature). In the specific case, we want to check if all necessary systems and users have access to the backup to ensure it's configured correctly (this is on top of doing actual restore checks, which happen separately and less frequently).

That said, the expected behavior would be to get a list of keys that have access to the repo.

Actual behavior
---------------

restic tries to acquire a lock and fails.

Steps to reproduce the behavior
-------------------------------

```
restic -r myrepo init
restic -r myrepo key list
find myrepo -type d -exec chmod 500 {} \;
restic -r myrepo key list
restic -r myrepo key --no-lock list
```

Do you have any idea what may have caused this?
-----------------------------------------------

Either a bug or a design decision.

Do you have an idea how to solve the issue?
-------------------------------------------

Make `key list` honour the `--no-lock` flag. This is the first time I would need to take a look a restic's source code.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Restic makes me smile every time I use it.

### PR DESCRIPTION
**Pull request by grembo**
Fixes #4513

What does this PR change? What problem does it solve?
-----------------------------------------------------

Don't lock repo if `--no-lock` flag was used as in `restic key list --no-list`

Was the change previously discussed in an issue or on the forum?
----------------------------------------------------------------

#4513

Checklist
---------

- [x] I have read the [contribution guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches).
- [x] I have [enabled maintainer edits](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [ ] ~~I have added tests for all code changes.~~

It seems like there are no unit tests for --no-lock besides TestCheckRestoreNoLock anywhere, so I think this should be part of a bigger effort to add such tests.

- [ ] ~~I have added documentation for relevant changes (in the manual).~~
- [x] There's a new file in `changelog/unreleased/` that describes the changes for our users (see [template](https://github.com/restic/restic/blob/master/changelog/TEMPLATE)).
- [x] I have run `gofmt` on the code in all commits.
- [x] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits).
- [x] I'm done! This pull request is ready for review.

### CODE REVIEW

File: changelog/unreleased/issue-4513 [hunk 1]
```diff
@@ -0,0 +1,8 @@
+Bugfix: Make `key list` command honor `--no-lock`
+
+This allows to determine which keys a repo can be accessed by without the
+need for having write access (e.g., read-only sftp access, filesystem
+snapshot).
+
+https://github.com/restic/restic/issues/4514
```
Comment (MichaelEischer) [inline changelog/unreleased/issue-4513:7]: 4514 is the pull request, not the issue

File: cmd/restic/cmd_key.go [hunk 2]
```diff
@@ -212,6 +212,10 @@ func runKey(ctx context.Context, gopts GlobalOptions, args []string) error {
 
 	switch args[0] {
 	case "list":
+		if gopts.NoLock {
+			return listKeys(ctx, repo, gopts)
```
Comment (MichaelEischer) [inline cmd/restic/cmd_key.go:216]: I'd prefer to just wrap the `lockRepo` and `unlockRepo` call into an if block, in order to not duplicate the `listKeys` call.

**Review by MichaelEischer — CHANGES_REQUESTED** [review]

**Comment by MichaelEischer** [comment]
> It seems like there are no unit tests for --no-lock besides TestCheckRestoreNoLock anywhere, so I think this should be part of a bigger effort to add such tests.

Yeah, the CLI methods have fairly little test coverage. I think we can skip adding a test, just make sure to manually test that `key list` works with and without `--no-lock`.

File: changelog/unreleased/issue-4513 (hunk 1 above)
Comment (grembo) [reply changelog/unreleased/issue-4513]: Duh! :) Thanks

File: cmd/restic/cmd_key.go (hunk 2 above)
Comment (grembo) [reply cmd/restic/cmd_key.go]: ok

**Review by MichaelEischer — APPROVED** [review]
LGTM.

I've rebased the PR and squashed the commits.
