### PR TITLE
fix panic in fs_reader

### LINKED ISSUE #4975: panic while using --stdin-from-command
Output of `restic version`
--------------------------
restic 0.17.0 compiled with go1.22.5 on linux/amd64

What backend/service did you use to store the repository?
---------------------------------------------------------
local file system

Problem description / Steps to reproduce
----------------------------------------
restic init -r /tmp/test
restic backup -r /tmp/test --stdin-from-command

Expected behavior
-----------------
no panic, a nice error message instead

Actual behavior
---------------
enter password for repository: 
repository 5a50c088 opened (version 2, compression level auto)
created new cache in /home/xxx/.cache/restic
found 1 old cache directories in /home/xxx/.cache/restic, run `restic cache --cleanup` to remove them
no parent snapshot found, will read all files
[0:00]          0 index files loaded
panic: runtime error: slice bounds out of range [1:0]

goroutine 1 [running]:
github.com/restic/restic/internal/fs.NewCommandReader({0x1468450?, 0xc00003e550?}, {0xc0004020c0?, 0x0?, 0x0?}, {0x7b38a7fd9f38?, 0xc0004021e0?})
	/restic/internal/fs/fs_reader_command.go:33 +0x26a
main.runBackup({_, _}, {{{0x0, 0x0, 0x0}, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...}, ...}, ...)
	/restic/cmd/restic/cmd_backup.go:585 +0xa73
main.init.func3(0x1cac9e0, {0xc0004020c0, 0x0, 0x3})
	/restic/cmd/restic/cmd_backup.go:61 +0x116
github.com/spf13/cobra.(*Command).execute(0x1cac9e0, {0xc000402060, 0x3, 0x3})
	/home/build/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:985 +0xaca
github.com/spf13/cobra.(*Command).ExecuteC(0x1cb2300)
	/home/build/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
	/home/build/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	/home/build/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1034
main.main()
	/restic/cmd/restic/main.go:125 +0x265

Do you have any idea what may have caused this?
-----------------------------------------------
I didn't specify any command after the --stdin-from-command flag

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
restic is an pretty stable piece of software - it's awesome

### PR DESCRIPTION
**Pull request by textaligncenter**
What does this PR change? What problem does it solve?
-----------------------------------------------------
It prevent's panic on using the restic backup --stdin-from-command without a command at the end

Was the change previously discussed in an issue or on the forum?
----------------------------------------------------------------
no

Closes #4975

Checklist
---------

- [x] I have read the [contribution guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches).
- [x] I have [enabled maintainer edits](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [x] I have added tests for all code changes.
- [ ] I have added documentation for relevant changes (in the manual).
- [x] There's a new file in `changelog/unreleased/` that describes the changes for our users (see [template](https://github.com/restic/restic/blob/master/changelog/TEMPLATE)).
- [x] I have run `gofmt` on the code in all commits.
- [x] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits).
- [x] I'm done! This pull request is ready for review.

### CODE REVIEW

File: internal/fs/fs_reader_command.go [hunk 1]
```diff
@@ -29,6 +29,10 @@ type CommandReader struct {
 }
 
 func NewCommandReader(ctx context.Context, args []string, logOutput io.Writer) (*CommandReader, error) {
+	if len(args) == 0 {
+		return nil, fmt.Errorf("please specify command as argument")
```
Comment (MichaelEischer) [inline internal/fs/fs_reader_command.go:33]: I'd prefer to call  this `no command was specified as argument`

**Review by MichaelEischer — COMMENTED** [review]
Good catch, thanks! I have one minor nitpick, see below.

**Review by MichaelEischer — APPROVED** [review]
LGTM. Thanks!
