### PR TITLE
sftp: Implement atomic uploads

### LINKED ISSUE #3003: Cannot remove broken snapshot
Output of `restic version`
--------------------------
restic 0.10.0 compiled with go1.15.2 on linux/amd64

How did you run restic exactly?
-------------------------------

```
$ restic --repo=sftp:...:... --password-file=... check
using temporary cache in /tmp/restic-check-cache-308261100
repository 7ab848e2 opened successfully, password is correct
created new cache in /tmp/restic-check-cache-308261100
create exclusive lock for repository
load indexes
check all packs
check snapshots, trees and blobs
error: load <snapshot/56c17514f8>: invalid data returned
Fatal: repository contains errors
$ restic --repo=sftp:...:... --password-file=... forget 56c17514f8
repository 7ab848e2 opened successfully, password is correct
Ignoring "56c17514f8ad85451bb4be440a1aac375260eb66b02abe6bda9345de32a20f68", could not load snapshot: load <snapshot/56c17514f8>: invalid data returned
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
SFTP

Expected behavior
-----------------
1. Snapshots should ideally not break.
2. There should be some way to recover easily from a broken snapshot.

Actual behavior
---------------
- Unable to `forget` a broken snapshot.

The respective snapshot file is empty (0B).

Steps to reproduce the behavior / Do you have any idea what may have caused this?
-------------------------------
- No real clue. The error was maybe caused by killing restic during backup or by unreliable network connection. Data corruption cannot be excluded.

Do you have an idea how to solve the issue?
-------------------------------------------
- Manually removing the affected snapshot file (that worked).

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
- Being able to efficiently back up a 300GB HDD on a Raspberry Pi 3. (Not related to this issue)

### PR DESCRIPTION
**Pull request by MichaelEischer**
What does this PR change? What problem does it solve?
-----------------------------------------------------
Most backends except sftp (and to some extent rclone) upload files atomically. This has two benefits: an interrupted upload won't leave incomplete files behind and additionally files that are still uploading are not visible to other processes.

This PR implements atomic upload for SFTP. The idea is to create a file with a sufficiently random temporary name that the chance of collisions is essentially zero and then rename the file to its final name once the upload is complete.

Was the change previously discussed in an issue or on the forum?
----------------------------------------------------------------
Fixes #3003

Checklist
---------
- [x] I have read the [contribution guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches).
- [x] I have [enabled maintainer edits](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [ ] I have added tests for all code changes.
- ~~[ ] I have added documentation for relevant changes (in the manual).~~
- [ ] There's a new file in `changelog/unreleased/` that describes the changes for our users (see [template](https://github.com/restic/restic/blob/master/changelog/TEMPLATE)).
- [x] I have run `gofmt` on the code in all commits.
- [x] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits).
- [ ] I'm done! This pull request is ready for review.

### CODE REVIEW

File: internal/backend/sftp/sftp.go [hunk 1]
```diff
@@ -318,7 +332,12 @@ func (r *SFTP) Save(ctx context.Context, h restic.Handle, rd restic.RewindReader
 	}
 
 	err = f.Close()
-	return errors.Wrap(err, "Close")
+	if err != nil {
+		return errors.Wrap(err, "Close")
+	}
+
+	err = r.c.Rename(tmpFilename, filename)
```
Comment (greatroar) [inline internal/backend/sftp/sftp.go:339]: Rename in SFTP fails when the target file exists. Maybe use PosixRename?

```suggestion
	// PosixRename overwrites an existing directory entry (such as a broken file), but isn't always available.
	if r.c.HasExtension("posix-rename@openssh.com") {
		err = r.c.PosixRename(tmpFilename, filename)
	} else {
		err = r.c.Rename(tmpFilename, filename)
	}
```

Comment (MichaelEischer) [reply internal/backend/sftp/sftp.go:339]: Hmm, I'm not completely sure its worth the trouble. File collisions should be rather rare as two independent restic processes will likely never end up uploading the same file. And after a failed upload the `RetryBackend` first tries to delete the file and then upload the file again.

Comment (greatroar) [reply internal/backend/sftp/sftp.go:339]: Fair enough.

**Review by fd0 — APPROVED** [review]
LGTM!
