### PR TITLE
Remove tests for directories

### LINKED ISSUE #279: using an empty password on initial creation will create an unusable repository
# how to reproduce

init a new repository and enter an empty password

```
$ ./restic -r foo  backup ~/tmp
enter password for repository: 
an empty password is not a password
```

So just try it again, this time willing to enter a non-empty password

# expected result

Can do this again and enter a password this time.

# actual result

```
$ ./restic -r ~/tmp  init
creating backend at /Users/mirko/tmp failed: dir /Users/mirko/tmp/data already exists
```

I can do nothing except deleting ```~/tmp```. This maybe a problem with other backends.

# proposal

Do the *i want a non empty password* check before initializing the repository.

### PR DESCRIPTION
**Pull request by fd0**
For testing whether a repository already exists it is sufficient to test if the config file (and therefore the master key) exists.

Closes #279

### CODE REVIEW

File: backend/local/local.go [hunk 1]
```diff
@@ -57,18 +57,11 @@ func Create(dir string) (*Local, error) {
 	}
 
 	// test if config file already exists
-	_, err := os.Lstat(backend.Paths.Config)
+	_, err := os.Lstat(filepath.Join(dir, backend.Paths.Config))
```
Comment (fw42) [inline backend/local/local.go]: why was this join not necessary before?

Comment (fd0) [inline backend/local/local.go]: It was necessary before, that's why this change fixes a bug ;)
