### PR TITLE
Make restic cat respect --no-lock

### LINKED ISSUE #2739: `restic cat` does not respect `--no-lock` flag
Output of `restic version`
--------------------------
restic 0.9.6 compiled with go1.13.4 on linux/amd64

How did you run restic exactly?
-------------------------------
`restic --no-lock --json cat lock <LOCK_ID>`

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
S3 (minio)

Expected behavior
-----------------
restic should ignore the exclusive lock in the repo (due to an ongoing check operation) and output the details of the lock.

Actual behavior
---------------
restic fails with an error message:  
`Fatal: unable to create lock in backend: repository is already locked exclusively by PID XXX on YYY by root (UID 0, GID 0)`

Steps to reproduce the behavior
-------------------------------
1. Start an operation that requires an exclusive lock (e.g. check, forget, prune)
1. List the locks:
   `$ restic --no-lock --json list locks`
   `<LOCK_ID>`
1. Attempt to cat a lock:
   `$ restic --no-lock --json cat lock <LOCK_ID>`
   `Fatal: unable to create lock in backend: repository is already locked exclusively by PID XXX on YYY by root (UID 0, GID 0)`

Do you have any idea what may have caused this?
-----------------------------------------------
The code in `restic/cmd/restic/cmd_cat.go` does not check the `opts.NoLock` before acquiring a lock:

```golang
	lock, err := lockRepo(repo)
	defer unlockRepo(lock)
	if err != nil {
		return err
	}
```

Do you have an idea how to solve the issue?
-------------------------------------------
Adding an if around the lock code in `restic/cmd/restic/cmd_cat.go` should solve the issue:

```golang
	if !opts.NoLock {
		lock, err := lockRepo(repo)
		defer unlockRepo(lock)
		if err != nil {
			return err
		}
	}
```

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
In general I'm very happy with restic and especially the speed and space savings it provides!

### PR DESCRIPTION
**Pull request by metalsp0rk**
What does this PR change? What problem does it solve?
-----------------------------------------------------

Makes the cat command respect the --no-lock global flag

Was the change discussed in an issue or in the forum before?
------------------------------------------------------------

Closes #2739 

Checklist
---------

- [x] I have read the [Contribution Guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches)
- [x] I have enabled [maintainer edits for this PR](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)
- [x] There's a new file in `changelog/unreleased/` that describes the changes for our users (template [here](https://github.com/restic/restic/blob/master/changelog/TEMPLATE))
- [x] I have run `gofmt` on the code in all commits
- [x] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits)
- [x] I'm done, this Pull Request is ready for review

### CODE REVIEW

**Comment by metalsp0rk** [comment]
Briefly tested, no issues.  This is a tiny change, so I don't expect it to do anything particularly crazy.

**Comment by metalsp0rk** [comment]
Lint failure:

> Error: Error return value of `unlockRepo` is not checked (errcheck)

File: cmd/restic/cmd_cat.go [hunk 1]
```diff
@@ -42,10 +42,12 @@ func runCat(gopts GlobalOptions, args []string) error {
 		return err
 	}
 
-	lock, err := lockRepo(gopts.ctx, repo)
-	defer unlockRepo(lock)
-	if err != nil {
-		return err
+	if !gopts.NoLock {
+		lock, err := lockRepo(gopts.ctx, repo)
+		defer unlockRepo(lock)
```
Comment (greatroar) [inline cmd/restic/cmd_cat.go:47]: The lint failure can be solved by doing

    defer func() { _ = unlockRepo(lock) }()

Though honestly, I think this check should be disabled. It leads to lots of "explicit error ignoring", which IMHO just hurts readability rather than improving the codebase.

File: changelog/unreleased/issue-2739 [hunk 2]
```diff
@@ -0,0 +1,5 @@
+Bugfix: Make cat command respect --no-lock
+
+Restic cat would not respect the --no-lock flag, this change fixes that issue.
```
Comment (greatroar) [inline changelog/unreleased/issue-2739:3]: ", this change fixes that issue" => ". It now does". The reader of the changelog is not looking at the commit log.

File: cmd/restic/cmd_cat.go (hunk 1 above)
Comment (metalsp0rk) [reply cmd/restic/cmd_cat.go:47]: I looked around and the way I have it above is how it's replicated in all other instances of repo locking.

I agree that this check is not helpful.

File: changelog/unreleased/issue-2739 (hunk 2 above)
Comment (metalsp0rk) [reply changelog/unreleased/issue-2739]: Fixed.

File: cmd/restic/cmd_cat.go (hunk 1 above)
Comment (greatroar) [reply cmd/restic/cmd_cat.go:47]: Alternatively, unlockRepo could print the error (with Warnf) instead of returning it.

Comment (aawsome) [reply cmd/restic/cmd_cat.go:47]: I also got the same error in #2876. I also vote for the `Warnf` solution!

Comment (metalsp0rk) [reply cmd/restic/cmd_cat.go:47]: I think warnf would be a preferable solution.

File: cmd/restic/cmd_cat.go [hunk 3]
```diff
@@ -42,10 +42,13 @@ func runCat(gopts GlobalOptions, args []string) error {
...
 
-	lock, err := lockRepo(gopts.ctx, repo)
-	defer unlockRepo(lock)
-	if err != nil {
-		return err
+	if !gopts.NoLock {
+		lock, err := lockRepo(gopts.ctx, repo)
+		// Make the linter happy
+		defer func() { _ = unlockRepo(lock) }()
+		if err != nil {
```
Comment (fd0) [inline cmd/restic/cmd_cat.go:49]: The error check should happen before the `defer unlock()`, apart from that it's fine.

**Review by fd0 — CHANGES_REQUESTED** [review]

**Comment by fd0** [comment]
By the way: we've only recently started running the linter which complained about the error check. With a non-trivial amount of code it's not possible to fix every issue at once, so for now it'll only complain about code changed in a PR. I hope that over time the codebase improves :)

File: cmd/restic/cmd_cat.go (hunk 3 above)
Comment (metalsp0rk) [reply cmd/restic/cmd_cat.go:48]: Done.

**Comment by metalsp0rk** [comment]
Yeah, I assumed that's what happened there.

From what I've seen so far, the codebase is fairly solid.  I'll echo that hope for improvement though.  :+1:

**Comment by fd0** [comment]
I've squash the commits and added code which warns when the unlock fails. We should fix that everywhere, but I don't have the time to do that right now.

**Review by fd0 — APPROVED** [review]
