### PR TITLE
backup: return exit code 3 if not all targets are available

### LINKED ISSUE #4467: Exit code 0 instead of 3 when directory given by --files-from is not readable
Output of `restic version`
--------------------------
restic 0.16.0 compiled with go1.20.6 on linux/amd64

I used 0.14 on the same infrastructure before which had the same problem.

How did you run restic exactly?
-------------------------------
The command was used to reproduce the problem:

/usr/bin/restic -r rclone:storagebox:Backups/BigNas -p /home/jb/Documents/restic-storagebox-bignas-pwd.txt backup --files-from /home/jb/Documents/test-dir-list.txt

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
rclone

Expected behavior
-----------------
echo $? returns 3

Reason:

The text file test-dir-list.txt (parameter for --files-from listing the dirs to backup) contains the following line:

/mnt/Daten/Backups/Gogs-not-there

This dir does not exist. This is done to simulate a non reachable NFS share.

https://restic.readthedocs.io/en/latest/040_backup.html#exit-status-codes states:

Restic returns one of the following exit status codes after the backup command is run:

0 when the backup was successful (snapshot with all source files created)
1 when there was a fatal error (no snapshot created)
3 when some source files could not be read (incomplete snapshot with remaining files created)

Program output: 

repository e8bb90c9 opened (version 2, compression level auto)
using parent snapshot 58fa48ca

Files:           0 new,     0 changed,  2270 unmodified
Dirs:            0 new,     0 changed,    16 unmodified
Added to the repository: 0 B   (0 B   stored)

processed 2270 files, 711.119 MiB in 0:03
snapshot 6a5fa242 saved

Actual behavior: 
echo $? returns 0

Expected behavior: 
echo $? returns 3

I hope I did not understand anything wrong and waste your time with this bug report. If I am correct though this bug is critical IMHO since it allows incomplete backups without notice. 

The actual backup in my case is done by a golang progam I wrote. The important lines are:

cmd := exec.Command(program, repo, repoParam, pwd, pwdParam, command, files, filesParam, tls, cacert, cacertParam)
if err := cmd.Run(); err != nil {
	return fmt.Sprintf("Error creating restic snapshot into repo:%s: %s\n", repoName, err.Error())
}

This did not catch a NFS share disconnect.

Steps to reproduce the behavior
-------------------------------
Use restic with --files-from that contains a non reachable dir.

Do you have any idea what may have caused this?
-----------------------------------------------
No

Do you have an idea how to solve the issue?
-------------------------------------------
No

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
Yes, it helps me every day. I am glad restic exists and I am impressed with the work the restic team is doing over such a long period of time.

### PR DESCRIPTION
**Pull request by konidev20**
What does this PR change? What problem does it solve?
-----------------------------------------------------
Restic `backup` command will also exit with code 3 if any one of the targets selected for backup are inaccessible. Previously, the `backup` command would exit with code 3 only if a child directory or file was inaccessible.

I have modified the `collectTargets` function in the `cmd_backup.go` command to check if all the targets collected from command line args, `--files-from`, `--files-from-verbatim` and `--files-from-raw` are accessible. If any of the targets are inaccessible then, we return the `ErrInvalidSourceData` towards the end; this will result in a exit code `3` (partial snapshot)

Was the change previously discussed in an issue or on the forum?
----------------------------------------------------------------
Closes #4467 

Checklist
---------
- [x] I have added tests for all code changes.
- [ ] I have added documentation for relevant changes (in the manual).
- [x] There's a new file in `changelog/unreleased/` that describes the changes for our users (see [template](https://github.com/restic/restic/blob/master/changelog/TEMPLATE)).
- [x] I'm done! This pull request is ready for review.

### CODE REVIEW

**Comment by konidev20** [comment]
Hi @MichaelEischer, bubbling this PR up since I see you are reviewing some PRs.

File: cmd/restic/cmd_backup.go [hunk 1]
```diff
@@ -438,11 +438,19 @@ func collectTargets(opts BackupOptions, args []string, warnf func(msg string, ar
 		return nil, errors.Fatal("nothing to backup, please specify source files/dirs")
 	}
 
+	countTargets := len(targets)
+
 	targets, err = filterExisting(targets, warnf)
```
Comment (MichaelEischer) [inline cmd/restic/cmd_backup.go]: Please move those checks into `filterExisting`, which already checks that the result array is not empty. So the new check also belongs there.

File: changelog/unreleased/issue-4467 [hunk 2]
```diff
@@ -0,0 +1,11 @@
+Bugfix: Exit with code 3 when some targets do not exist
```
Comment (MichaelEischer) [inline changelog/unreleased/issue-4467]:
```suggestion
Bugfix: Exit with code 3 when some `backup` source files do not exist
```

The terminology has change to refer to the backup data as `source directories/files` instead of `targets`, which was  rather confusing. The internal naming in the code unfortunately still uses the old naming. Please update that in the changelog

**Review by MichaelEischer — CHANGES_REQUESTED** [review]
Thanks, see below for comments and sorry for yet another merge conflict :see_no_evil:  .

File: changelog/unreleased/issue-4467 (hunk 2 above)
Comment (konidev20) [reply changelog/unreleased/issue-4467]: Completed and Committed

File: cmd/restic/cmd_backup.go (hunk 1 above)
Comment (konidev20) [reply cmd/restic/cmd_backup.go]: Completed. Moved the check in to the `filterExisting` function.

File: changelog/unreleased/issue-4467 [hunk 3]
```diff
@@ -0,0 +1,11 @@
+Bugfix: Exit with code 3 when some `backup` source files do not exist
+
+Restic used to exit with code 0 even when some targets did not exist. Restic
```
Comment (MichaelEischer) [inline changelog/unreleased/issue-4467]:
```suggestion
Restic used to exit with code 0 even when some backup sources did not exist. Restic
```

File: changelog/unreleased/issue-4467 [hunk 4]
```diff
@@ -0,0 +1,11 @@
+Bugfix: Exit with code 3 when some `backup` source files do not exist
+
+Restic used to exit with code 0 even when some targets did not exist. Restic 
+would exit with code 3 only when child directories or files did not exist. This
+could cause confusion and unexpected behavior in scripts that relied on the exit
+code to determine if the backup was successful.
+
+Restic now exits with code 3 when some targets do not exist.
```
Comment (MichaelEischer) [inline changelog/unreleased/issue-4467]:
```suggestion
Restic now exits with code 3 when some backup sources do not exist.
```

File: cmd/restic/cmd_backup.go [hunk 5]
```diff
@@ -160,6 +160,8 @@ var ErrInvalidSourceData = errors.New("at least one source file could not be rea
 // filterExisting returns a slice of all existing items, or an error if no
```
Comment (MichaelEischer) [inline cmd/restic/cmd_backup.go:163]:
```suggestion
// ErrNoSourceData is used to report that no source data was found
var ErrNoSourceData = errors.Fatal("all source directories/files do not exist")

// filterExisting returns a slice of all existing items, or an error if no
```

File: cmd/restic/cmd_backup.go [hunk 6]
```diff
@@ -160,6 +160,8 @@ var ErrInvalidSourceData = errors.New("at least one source file could not be rea
...
 // items exist at all.
 func filterExisting(items []string, warnf func(msg string, args ...interface{})) (result []string, err error) {
+	countTargets := len(items)
+
```
Comment (MichaelEischer) [inline cmd/restic/cmd_backup.go]:
```suggestion
```

File: cmd/restic/cmd_backup.go [hunk 7]
```diff
@@ -170,6 +172,12 @@ func filterExisting(items []string, warnf func(msg string, args ...interface{}))
...
 
+	countExisting := len(result)
+
+	if countExisting < countTargets {
+		return nil, ErrInvalidSourceData
+	}
+
 	if len(result) == 0 {
 		return nil, errors.Fatal("all source directories/files do not exist")
 	}
```
Comment (MichaelEischer) [inline cmd/restic/cmd_backup.go]:
```suggestion
        if len(result) == 0 {
                return nil, ErrNoSourceData
        } else if len(result) < len(items) {
                return result, ErrInvalidSourceData
        }
```

File: cmd/restic/cmd_backup.go [hunk 8]
```diff
@@ -160,6 +160,8 @@ var ErrInvalidSourceData = errors.New("at least one source file could not be rea
 // filterExisting returns a slice of all existing items, or an error if no
 // items exist at all.
 func filterExisting(items []string, warnf func(msg string, args ...interface{})) (result []string, err error) {
```
Comment (MichaelEischer) [inline cmd/restic/cmd_backup.go:165]: The callsite of `filterExisting` must be changed to:
```
return filterExisting(targets, warnf)
```

File: cmd/restic/cmd_backup_integration_test.go [hunk 9]
```diff
@@ -271,7 +272,9 @@ func TestBackupNonExistingFile(t *testing.T) {
 
 	opts := BackupOptions{}
 
-	testRunBackup(t, "", dirs, opts, env.gopts)
+	err := testRunBackupAssumeFailure(t, "", dirs, opts, env.gopts)
+	rtest.Assert(t, err != nil, "expected error for non-existing file")
+	rtest.Assert(t, !errors.Is(err, ErrInvalidSourceData), "expected ErrInvalidSourceData; got %v", err)
```
Comment (MichaelEischer) [inline cmd/restic/cmd_backup_integration_test.go]:
```suggestion
        rtest.Assert(t, errors.Is(err, ErrInvalidSourceData), "expected ErrInvalidSourceData; got %v", err)

        // only non-existing file
        dirs = []string{
                filepath.Join(p, "nonexisting"),
        }
        err = testRunBackupAssumeFailure(t, "", dirs, opts, env.gopts)
        rtest.Assert(t, err != nil, "expected error for non-existing file")
        rtest.Assert(t, errors.Is(err, ErrNoSourceData), "expected ErrNoSourceData; got %v", err)
```

File: cmd/restic/cmd_backup_integration_test.go [hunk 10]
```diff
@@ -271,7 +272,9 @@ func TestBackupNonExistingFile(t *testing.T) {
 
 	opts := BackupOptions{}
 
-	testRunBackup(t, "", dirs, opts, env.gopts)
+	err := testRunBackupAssumeFailure(t, "", dirs, opts, env.gopts)
```
Comment (MichaelEischer) [inline cmd/restic/cmd_backup_integration_test.go:276]:
```suggestion
 // mix of existing and non-existing files
	err := testRunBackupAssumeFailure(t, "", dirs, opts, env.gopts)
```

File: cmd/restic/cmd_backup_test.go [hunk 11]
```diff
@@ -71,6 +71,9 @@ func TestCollectTargets(t *testing.T) {
 	rtest.OK(t, err)
 	sort.Strings(targets)
 	rtest.Equals(t, expect, targets)
+
+	_, err = collectTargets(opts, []string{filepath.Join(dir, "cmdline arg"), filepath.Join(dir, "non-existing-file")}, t.Logf, nil)
```
Comment (MichaelEischer) [inline cmd/restic/cmd_backup_test.go:75]: Check that the valid targets are still returned

**Review by MichaelEischer — CHANGES_REQUESTED** [review]
The PR in its current form is completely broken, see comments and suggestions below.

**Review by MichaelEischer — APPROVED** [review]
LGTM.
