### PR TITLE
local: mark repository files as read-only and handle chmod errors

### LINKED ISSUE #1756: lockfile operation fails at setting permissions. (NFS mount)
## Output of `restic version`
```
restic 0.8.3
compiled with go1.10 on linux/amd64
```

## How did you run restic exactly?
```
bri@sarek:~$ ls /net/backup/bri/restic/locks/
bri@sarek:~$ restic -r /net/backup/bri/restic key list
enter password for repository: 
password is correct
Save(<lock/d434e4c7e1>) returned error, retrying after 601.488169ms: chmod /net/backup/bri/restic/locks/d434e4c7e166c913466c935c261e56367242e52b3f05a469b117b9c9f84bc286: permission denied
Save(<lock/d434e4c7e1>) returned error, retrying after 731.008682ms: OpenFile: open /net/backup/bri/restic/locks/d434e4c7e166c913466c935c261e56367242e52b3f05a469b117b9c9f84bc286: file exists
Save(<lock/d434e4c7e1>) returned error, retrying after 595.949861ms: OpenFile: open /net/backup/bri/restic/locks/d434e4c7e166c913466c935c261e56367242e52b3f05a469b117b9c9f84bc286: file exists
Save(<lock/d434e4c7e1>) returned error, retrying after 1.848142058s: OpenFile: open /net/backup/bri/restic/locks/d434e4c7e166c913466c935c261e56367242e52b3f05a469b117b9c9f84bc286: file exists
Save(<lock/d434e4c7e1>) returned error, retrying after 2.627967632s: OpenFile: open /net/backup/bri/restic/locks/d434e4c7e166c913466c935c261e56367242e52b3f05a469b117b9c9f84bc286: file exists
Save(<lock/d434e4c7e1>) returned error, retrying after 2.032559039s: OpenFile: open /net/backup/bri/restic/locks/d434e4c7e166c913466c935c261e56367242e52b3f05a469b117b9c9f84bc286: file exists
Save(<lock/d434e4c7e1>) returned error, retrying after 3.202257262s: OpenFile: open /net/backup/bri/restic/locks/d434e4c7e166c913466c935c261e56367242e52b3f05a469b117b9c9f84bc286: file exists
Save(<lock/d434e4c7e1>) returned error, retrying after 8.641994852s: OpenFile: open /net/backup/bri/restic/locks/d434e4c7e166c913466c935c261e56367242e52b3f05a469b117b9c9f84bc286: file exists
Save(<lock/d434e4c7e1>) returned error, retrying after 7.618848686s: OpenFile: open /net/backup/bri/restic/locks/d434e4c7e166c913466c935c261e56367242e52b3f05a469b117b9c9f84bc286: file exists
Save(<lock/d434e4c7e1>) returned error, retrying after 13.385748834s: OpenFile: open /net/backup/bri/restic/locks/d434e4c7e166c913466c935c261e56367242e52b3f05a469b117b9c9f84bc286: file exists
Fatal: unable to create lock in backend: OpenFile: open /net/backup/bri/restic/locks/d434e4c7e166c913466c935c261e56367242e52b3f05a469b117b9c9f84bc286: file exists
bri@sarek:~$ ls /net/backup/bri/restic/locks/
d434e4c7e166c913466c935c261e56367242e52b3f05a469b117b9c9f84bc286
bri@sarek:~$ restic -r /net/backup/bri/restic --no-lock snapshots
enter password for repository: 
password is correct
ID        Date                 Host        Tags        Directory
----------------------------------------------------------------------
6904b641  2018-05-02 17:10:27  bri-x260                /etc
----------------------------------------------------------------------
1 snapshots
bri@sarek:~$ restic -r /net/backup/bri/restic --no-lock key list
enter password for repository: 
password is correct
Save(<lock/4762fb4913>) returned error, retrying after 569.926934ms: chmod /net/backup/bri/restic/locks/4762fb49130a4806d4a21756dc7841a9eb2f342b61385ace4385b7dceff4f081: permission denied
Save(<lock/4762fb4913>) returned error, retrying after 551.506659ms: OpenFile: open /net/backup/bri/restic/locks/4762fb49130a4806d4a21756dc7841a9eb2f342b61385ace4385b7dceff4f081: file exists
Save(<lock/4762fb4913>) returned error, retrying after 994.629372ms: OpenFile: open /net/backup/bri/restic/locks/4762fb49130a4806d4a21756dc7841a9eb2f342b61385ace4385b7dceff4f081: file exists
Save(<lock/4762fb4913>) returned error, retrying after 1.66420665s: OpenFile: open /net/backup/bri/restic/locks/4762fb49130a4806d4a21756dc7841a9eb2f342b61385ace4385b7dceff4f081: file exists
Save(<lock/4762fb4913>) returned error, retrying after 2.241728362s: OpenFile: open /net/backup/bri/restic/locks/4762fb49130a4806d4a21756dc7841a9eb2f342b61385ace4385b7dceff4f081: file exists
Save(<lock/4762fb4913>) returned error, retrying after 4.997256632s: OpenFile: open /net/backup/bri/restic/locks/4762fb49130a4806d4a21756dc7841a9eb2f342b61385ace4385b7dceff4f081: file exists
Save(<lock/4762fb4913>) returned error, retrying after 3.991724804s: OpenFile: open /net/backup/bri/restic/locks/4762fb49130a4806d4a21756dc7841a9eb2f342b61385ace4385b7dceff4f081: file exists
Save(<lock/4762fb4913>) returned error, retrying after 12.616242107s: OpenFile: open /net/backup/bri/restic/locks/4762fb49130a4806d4a21756dc7841a9eb2f342b61385ace4385b7dceff4f081: file exists
Save(<lock/4762fb4913>) returned error, retrying after 16.40090692s: OpenFile: open /net/backup/bri/restic/locks/4762fb49130a4806d4a21756dc7841a9eb2f342b61385ace4385b7dceff4f081: file exists
Save(<lock/4762fb4913>) returned error, retrying after 17.235408207s: OpenFile: open /net/backup/bri/restic/locks/4762fb49130a4806d4a21756dc7841a9eb2f342b61385ace4385b7dceff4f081: file exists
Fatal: unable to create lock in backend: OpenFile: open /net/backup/bri/restic/locks/4762fb49130a4806d4a21756dc7841a9eb2f342b61385ace4385b7dceff4f081: file exists
```

## What backend/server/service did you use to store the repository?

NFS mounted folder. However the NFS mount enforces somewhat strange permissions which i cannot change because it is a NFS export from a NetAapp storage.

```
bri@sarek:~$ ls -al /net/backup/bri/restic/
total 48
drwx------   7 bri  ngni        4096 Mai  2 16:46 .
drwx------   8 root 4294967294  4096 Mai  2 16:42 ..
-rwx------   1 bri  ngni         155 Mai  2 16:44 config
drwx------ 258 bri  ngni       20480 Mai  2 16:44 data
drwx------   2 bri  ngni        4096 Mai  2 17:10 index
drwx------   2 bri  ngni        4096 Mai  2 17:04 keys
drwx------   2 bri  ngni        4096 Mai  3 14:16 locks
drwx------   2 bri  ngni        4096 Mai  2 17:10 snapshots
```

## Expected behavior

Access to the repository: in this case the list of keys.

## Actual behavior

Restic fails when settings some rights on the lock created logfile. The lockfile is created sucesfully but not recognized by restic. 

However, using the rest-server on the same folder works.

## Steps to reproduce the behavior

Use a filesystem that enforces 0700 on all files. This can be reproduces by a samba mount with `gid=,uid=,file_mode=0700,arg,dir_mode=0700` mount options.

## Do you have an idea how to solve the issue?

Maybe add an option to ignore file modes on lockfiles.

### LINKED ISSUE #2157: Unable to create restic repo on exfat file system
Output of `restic version`
--------------------------
restic 0.9.4 compiled with go1.11.4 on linux/amd64

How did you run restic exactly?
-------------------------------
restic init --repo /media/usb2disk/restic-backups
Fatal: create key in repository at /media/usb2disk/restic-backups failed: chmod /media/usb2disk/restic-backups/keys/xxxxxxx129a57e88671f14799366326da40305693822a32de797a2591078e984: operation not permitted

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
local file on exfat filesystem:
lsblk -f | grep usb2disk
└─sdb1                exfat             6A4F-0A7F                              /media/usb2disk

Expected behavior
-----------------
Repository to be created without issues.

Actual behavior
---------------
Repository partially created, but not usable.

Steps to reproduce the behavior
-------------------------------
Create repo on exfat filesystem.

Do you have any idea what may have caused this?
-----------------------------------------------
exfat filesystem, I suspect, as it doesn't support chmod.

Do you have an idea how to solve the issue?
-------------------------------------------
No.

Did restic help you or made you happy in any way?
-------------------------------------------------
Using restic already with local repo (on ext4), and also backblaze b2. It's great!

### PR DESCRIPTION
**Pull request by MichaelEischer**
What does this PR change? What problem does it solve?
-----------------------------------------------------
Files stored by the local backend in a repository should be marked as readonly to prevent accidental modifications. However this was accidentally removed in #1258. This PR reintroduces this behavior. In addition permissions errors for the `chmod` calls are now ignored. These could cause problems with certain mounted filesystems, see #1756 and #2157.

Was the change discussed in an issue or in the forum before?
------------------------------------------------------------
closes #1756
closes #2157

Checklist
---------

- [x] I have read the [Contribution Guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches)
- [x] I have enabled [maintainer edits for this PR](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)
- [ ] I have added tests for all changes in this PR
- ~~[ ] I have added documentation for the changes (in the manual)~~
- [ ] There's a new file in `changelog/unreleased/` that describes the changes for our users (template [here](https://github.com/restic/restic/blob/master/changelog/TEMPLATE))
- [x] I have run `gofmt` on the code in all commits
- [x] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits)
- [x] I'm done, this Pull Request is ready for review

### CODE REVIEW

**Comment by greatroar** [comment]
LGTM. Looks like the Chmod originally masked off all the write bits, until it was changed to a no-op in 9842eff887f779152ec220d1eccf8e847ae0c14d.

File: internal/backend/local/local.go [hunk 1]
```diff
@@ -201,15 +197,7 @@ func (b *Local) Test(ctx context.Context, h restic.Handle) (bool, error) {
...
-	fn := b.Filename(h)
-
-	// reset read-only flag
-	err := fs.Chmod(fn, 0666)
-	if err != nil {
-		return errors.Wrap(err, "Chmod")
-	}
-
-	return fs.Remove(fn)
+	return fs.Remove(b.Filename(h))
```
Comment (greatroar) [inline internal/backend/local/local.go:200]: :smile:

**Comment by MichaelEischer** [comment]
After talking with @fd0, I've turned this PR upside down. Instead of removing the previously redundant chmod call it sets the readonly flag for data files, which was accidentally remove in #1258. The permission errors from #1756 and #2157 are now ignored for the chmod calls.

File: changelog/unreleased/issue-1756 [hunk 2]
```diff
@@ -0,0 +1,11 @@
+Bugfix: Mark repository files as readonly when using the local backend
+
+Files stored in a local repository are marked as readonly on non-Windows
+systems to prevent accidential file modifications. In addition, the handling
+of errors is improved which enables the local backend to work with certain
+filesystems and network mounts which do not permit modifications of file
+permissions.
```
Comment (rawtaz) [inline changelog/unreleased/issue-1756:7]: This paragraph is unclear. The present tense makes it unclear if you are talking about how it is after this bugfix is applied, or if you are talking about the state of things before the bugfix is applied.

I suggest writing it like this instead:

~~~
Description of the problem in past tense.

Decription of the solution implemented and how it works in present tense.
~~~

Wording like "is now" can be used to convey "after the bugfix".

File: changelog/unreleased/issue-1756 [hunk 3]
```diff
@@ -0,0 +1,11 @@
+Bugfix: Mark repository files as readonly when using the local backend
+
+Files stored in a local repository are marked as readonly on non-Windows
```
Comment (rawtaz) [inline changelog/unreleased/issue-1756:3]: Might perhaps be good to write "marked as read-only in the filesystem", so it's clear where/how it's being marked as read-only.

File: internal/backend/local/local_unix.go [hunk 4]
```diff
@@ -9,6 +9,6 @@ import (
 )
 
 // set file to readonly
-func setNewFileMode(f string, mode os.FileMode) error {
-	return fs.Chmod(f, mode)
+func setFileReadonly(f string, mode os.FileMode) error {
+	return fs.Chmod(f, mode&os.FileMode(^uint32(0222)))
```
Comment (greatroar) [inline internal/backend/local/local_unix.go:13]: More modern Go would be

     mode &^ 0222

File: internal/backend/local/local.go [hunk 5]
```diff
@@ -205,7 +213,7 @@ func (b *Local) Remove(ctx context.Context, h restic.Handle) error {
 
 	// reset read-only flag
 	err := fs.Chmod(fn, 0666)
```
Comment (greatroar) [inline internal/backend/local/local.go:215]: I really don't get this one, though, at least not on Unix. Why chmod a file that we're going to remove right after?

Comment (MichaelEischer) [reply internal/backend/local/local.go:215]: I agree that on Unix this `chmod` is pretty much useless. My idea here was to ensure that a Windows system can remove a file in a repository created on a Unix system (probably via a shared NTFS partition).

File: internal/backend/local/local_unix.go (hunk 4 above)
Comment (MichaelEischer) [reply internal/backend/local/local_unix.go]: I've changed it, That's indeed much more readable.

File: changelog/unreleased/issue-1756 (hunk 3 above)
Comment (MichaelEischer) [reply changelog/unreleased/issue-1756]: Is changed.

File: changelog/unreleased/issue-1756 (hunk 2 above)
Comment (MichaelEischer) [reply changelog/unreleased/issue-1756]: The before and after the bugfix should be much clearer now. I've added a remark that the modifications the readonly flag should help against are something external to restic. However, I'm not really happy with the wording `modifications outside of restic.` with which I ended up with.

File: changelog/unreleased/issue-1756 [hunk 6]
```diff
@@ -0,0 +1,15 @@
+Bugfix: Mark repository files as readonly when using the local backend
+
+Files stored in a local repository were marked as writeable on the
+filesystem for non-Windows systems, which did not prevent accidential file
```
Comment (greatroar) [inline changelog/unreleased/issue-1756:4]: accidental

Comment (MichaelEischer) [reply changelog/unreleased/issue-1756]: I've fixed the typo

**Review by fd0 — APPROVED** [review]
LGTM!
