### PR TITLE
Use character display width for table padding

### LINKED ISSUE #4834: Slight cosmetic snapshot listing bug
Output of `restic version`
--------------------------
restic 0.16.4 compiled with go1.21.6 on darwin/amd64

What backend/service did you use to store the repository?
---------------------------------------------------------
SharePoint

Problem description / Steps to reproduce
----------------------------------------

If a snapshot's host (possibly other fields) contains an `’` it will throw off column alignment.  Or at least I think that's what's happening.  It could be that having that character in tags or pathnames would also throw off alignment, but I did not test that.

Expected behavior
-----------------

Tags should be lined up in one column

Actual behavior
---------------

Tags do not line up, possibly because of the `’` in the host name?  This does not happen on standard `'` apostrophes.

Screenshot 2024-05-29 at 11 21 47 AM

Screenshot 2024-05-29 at 11 23 37 AM

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

🫶

### PR DESCRIPTION
**Pull request by fthoma**
What does this PR change? What problem does it solve?
-----------------------------------------------------
Using len(...) for table cell padding produced wrong results for unicode chracters leading to misaligned tables. Implementation changed to take the actual terminal display width into consideration. 
I chose to implement a simple helper function for the width calculation. There are libraries like  [go-runewidth](https://github.com/mattn/go-runewidth) that do a better job and take more edge cases into consideration. But i'm not sure its worth the dependency.

See before/after:
20240605_09h57m56s_grim

Was the change previously discussed in an issue or on the forum?
----------------------------------------------------------------
Closes #4834 

Checklist
---------

- [x] I have read the [contribution guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches).
- [x] I have [enabled maintainer edits](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [x] I have added tests for all code changes.
- [ ] I have added documentation for relevant changes (in the manual).
- [ ] There's a new file in `changelog/unreleased/` that describes the changes for our users (see [template](https://github.com/restic/restic/blob/master/changelog/TEMPLATE)).
- [x] I have run `gofmt` on the code in all commits.
- [x] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits).
- [x] I'm done! This pull request is ready for review.

### CODE REVIEW

File: internal/ui/format.go [hunk 1]
```diff
@@ -105,3 +107,24 @@ func ToJSONString(status interface{}) string {
...
+func TerminalDisplayWidth(s string) int {
+	width := 0
+	for _, r := range s {
+		width += terminalDisplayRuneWidth(r)
+	}
+
+	return width
+}
+
+func terminalDisplayRuneWidth(r rune) int {
```
Comment (MichaelEischer) [inline internal/ui/format.go:121]: I've tried to unify this with `wideRune` in `internal/ui/termstatus/status.go`. However, it turned out that the use cases are somewhat different. In status, it is better to overestimate the rune width if in doubt. So let's keep separate functions for now.

**Review by MichaelEischer — APPROVED** [review]
LGTM. Thanks!

I've added a small cleanup commit and a fix for a probably pretty old bug.
