### PR TITLE
Check for ENOSPC and remove broken files in SFTP

### LINKED ISSUE #3336: Write: sftp: "Failure" (SSH_FX_FAILURE) when the remote storage is full
Output of `restic version`
--------------------------
restic 0.12.0 compiled with go1.15.8 on linux/amd64

How did you run restic exactly?
-------------------------------
`restic -r sftp:root@<ip-adress-snipped>:/mnt/backup-docker/ --verbose prune --password-file=/root/.restic/backup-docker.pwd`

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
Scaleway root-server via SFTP

Expected behavior
-----------------

cleaning up / prune snapshots so the backup is working again

Actual behavior
---------------

`restic -r sftp:root@<ip-adress-snipped>:/mnt/backup-docker/ --verbose check --password-file=/root/.restic/backup-docker.pwd`
<details>

```
pack f399332c: not referenced in any index
[...]
A lot of not referenced index files
[...]
pack dfe443af: not referenced in any index
1585 additional files were found in the repo, which likely contain duplicate data.
You can run `restic prune` to correct this.
```

</details>

`restic -r sftp:root@<ip-adress-snipped>:/mnt/backup-docker/ --verbose prune --password-file=/root/.restic/backup-docker.pwd`

<details>

```
repository 92246e2a opened successfully, password is correct
counting files in repo
building new index for repo
[8:50] 100.00%  63722 / 63722 packs
incomplete pack file (will be removed): 17a852a13c08e04fd541e43a593bbe94feba8b77768953a405ccedacfc1648bb
incomplete pack file (will be removed): cf8895aa47d5e19072efeb07f57971bdb9ad929dda3af381d50bd1c14900a44c
[...]
A lot of incomplete pack files
[...]
repository contains 63681 packs (1347596 blobs) with 294.325 GiB
processed 1347596 blobs: 105577 duplicate blobs, 87.518 GiB duplicate
load all snapshots
find data that is still in use for 202 snapshots
[3:11] 18.81%  38 / 202 snapshots
[3:13] 19.31%  39 / 202 snapshots
[3:51] 60.89%  123 / 202 snapshots
[4:02] 96.04%  194 / 202 snapshots
[4:04] 100.00%  202 / 202 snapshots
found 934858 of 1347596 data blobs still in use, removing 412738 blobs
will remove 41 invalid files
will delete 35672 packs and rewrite 346 packs, this frees 255.849 GiB
Save(<data/9f6747a697>) returned error, retrying after 598.193345ms: Write: sftp: "Failure" (SSH_FX_FAILURE)
Save(<data/9f6747a697>) returned error, retrying after 850.463688ms: Write: sftp: "Failure" (SSH_FX_FAILURE)
Save(<data/9f6747a697>) returned error, retrying after 1.648746395s: Write: sftp: "Failure" (SSH_FX_FAILURE)
Save(<data/9f6747a697>) returned error, retrying after 1.81251255s: Write: sftp: "Failure" (SSH_FX_FAILURE)
Save(<data/9f6747a697>) returned error, retrying after 3.385001074s: Write: sftp: "Failure" (SSH_FX_FAILURE)
Save(<data/9f6747a697>) returned error, retrying after 2.114282783s: Write: sftp: "Failure" (SSH_FX_FAILURE)
Save(<data/9f6747a697>) returned error, retrying after 7.109876912s: Write: sftp: "Failure" (SSH_FX_FAILURE)
Save(<data/9f6747a697>) returned error, retrying after 5.809616247s: Write: sftp: "Failure" (SSH_FX_FAILURE)
Save(<data/9f6747a697>) returned error, retrying after 17.617471184s: Write: sftp: "Failure" (SSH_FX_FAILURE)
Save(<data/9f6747a697>) returned error, retrying after 12.153765673s: Write: sftp: "Failure" (SSH_FX_FAILURE)
sftp: "Failure" (SSH_FX_FAILURE)itten
Write
github.com/restic/restic/internal/backend/sftp.(*SFTP).Save
	github.com/restic/restic/internal/backend/sftp/sftp.go:326
github.com/restic/restic/internal/limiter.rateLimitedBackend.Save
	github.com/restic/restic/internal/limiter/limiter_backend.go:30
github.com/restic/restic/internal/backend.(*RetryBackend).Save.func1
	github.com/restic/restic/internal/backend/backend_retry.go:56
github.com/cenkalti/backoff.RetryNotify
	github.com/cenkalti/backoff/retry.go:37
github.com/restic/restic/internal/backend.(*RetryBackend).retry
	github.com/restic/restic/internal/backend/backend_retry.go:36
github.com/restic/restic/internal/backend.(*RetryBackend).Save
	github.com/restic/restic/internal/backend/backend_retry.go:50
github.com/restic/restic/internal/cache.(*Backend).Save
	github.com/restic/restic/internal/cache/backend.go:54
github.com/restic/restic/internal/repository.(*Repository).savePacker
	github.com/restic/restic/internal/repository/packer_manager.go:106
github.com/restic/restic/internal/repository.(*Repository).SaveAndEncrypt
	github.com/restic/restic/internal/repository/repository.go:270
github.com/restic/restic/internal/repository.(*Repository).SaveBlob
	github.com/restic/restic/internal/repository/repository.go:704
github.com/restic/restic/internal/repository.Repack
	github.com/restic/restic/internal/repository/repack.go:87
main.pruneRepository
	github.com/restic/restic/cmd/restic/cmd_prune.go:278
main.runPrune
	github.com/restic/restic/cmd/restic/cmd_prune.go:85
main.glob..func18
	github.com/restic/restic/cmd/restic/cmd_prune.go:25
github.com/spf13/cobra.(*Command).execute
	github.com/spf13/cobra/command.go:762
github.com/spf13/cobra.(*Command).ExecuteC
	github.com/spf13/cobra/command.go:850
github.com/spf13/cobra.(*Command).Execute
	github.com/spf13/cobra/command.go:800
main.main
	github.com/restic/restic/cmd/restic/main.go:86
runtime.main
	/usr/lib/go-1.12/src/runtime/proc.go:200
runtime.goexit
	/usr/lib/go-1.12/src/runtime/asm_amd64.s:1337

```
</details>

`restic -r sftp:root@<ip-address-snipped>:/mnt/backup-docker/ --verbose backup /var/lib/docker/ --password-file=/root/.restic/backup-docker.pwd
`
<details>

```
open repository
repository 92246e2a opened successfully, password is correct
lock repository
load index files
using parent snapshot f1a93c2b
start scan on [/var/lib/docker/]
start backup on [/var/lib/docker/]
Save(<data/f5e7222fc9>) returned error, retrying after 437.171317ms: Write: sftp: "Failure" (SSH_FX_FAILURE)
Save(<data/f73a49bbe2>) returned error, retrying after 423.030259ms: Write: sftp: "Failure" (SSH_FX_FAILURE)eb6e00c8ca55001e77eb36ffc99d5791a179e3cf780aa1c7-json.log
Save(<data/e8ea901191>) returned error, retrying after 412.66944ms: Write: sftp: "Failure" (SSH_FX_FAILURE)
Save(<data/f5e7222fc9>) returned error, retrying after 729.638889ms: Write: sftp: "Failure" (SSH_FX_FAILURE)
Save(<data/e8ea901191>) returned error, retrying after 554.948931ms: Write: sftp: "Failure" (SSH_FX_FAILURE)eb6e00c8ca55001e77eb36ffc99d5791a179e3cf780aa1c7-json.log
Save(<data/f73a49bbe2>) returned error, retrying after 1.091541757s: Write: sftp: "Failure" (SSH_FX_FAILURE)
Save(<data/e8ea901191>) returned error, retrying after 1.512941144s: Write: sftp: "Failure" (SSH_FX_FAILURE)
Save(<data/f5e7222fc9>) returned error, retrying after 725.284281ms: Write: sftp: "Failure" (SSH_FX_FAILURE)
Save(<data/f73a49bbe2>) returned error, retrying after 1.546249696s: Write: sftp: "Failure" (SSH_FX_FAILURE)
Save(<data/f5e7222fc9>) returned error, retrying after 2.217300829s: Write: sftp: "Failure" (SSH_FX_FAILURE)
Save(<data/152265f020>) returned error, retrying after 442.45257ms: Write: sftp: "Failure" (SSH_FX_FAILURE)937b15c2063eb34b23702c1f875e4b90d15e8ceb2aa8f60f1-json.log
Save(<data/e8ea901191>) returned error, retrying after 2.492482153s: Write: sftp: "Failure" (SSH_FX_FAILURE)
Save(<data/152265f020>) returned error, retrying after 752.170907ms: Write: sftp: "Failure" (SSH_FX_FAILURE)
Save(<data/f73a49bbe2>) returned error, retrying after 1.567900755s: Write: sftp: "Failure" (SSH_FX_FAILURE)
Save(<data/152265f020>) returned error, retrying after 866.326182ms: Write: sftp: "Failure" (SSH_FX_FAILURE)
Save(<data/f5e7222fc9>) returned error, retrying after 2.74188537s: Write: sftp: "Failure" (SSH_FX_FAILURE)
Save(<data/152265f020>) returned error, retrying after 1.140151404s: Write: sftp: "Failure" (SSH_FX_FAILURE)
Save(<data/f73a49bbe2>) returned error, retrying after 3.288696345s: Write: sftp: "Failure" (SSH_FX_FAILURE)
Save(<data/e8ea901191>) returned error, retrying after 2.406437136s: Write: sftp: "Failure" (SSH_FX_FAILURE)
Save(<data/152265f020>) returned error, retrying after 1.664638098s: Write: sftp: "Failure" (SSH_FX_FAILURE)
Save(<data/f5e7222fc9>) returned error, retrying after 2.51257952s: Write: sftp: "Failure" (SSH_FX_FAILURE)
Save(<data/152265f020>) returned error, retrying after 4.584168338s: Write: sftp: "Failure" (SSH_FX_FAILURE)
Save(<data/e8ea901191>) returned error, retrying after 4.291992227s: Write: sftp: "Failure" (SSH_FX_FAILURE)
Save(<data/f73a49bbe2>) returned error, retrying after 4.867318033s: Write: sftp: "Failure" (SSH_FX_FAILURE)
Save(<data/f5e7222fc9>) returned error, retrying after 5.731181313s: Write: sftp: "Failure" (SSH_FX_FAILURE)
Save(<data/e8ea901191>) returned error, retrying after 3.61222373s: Write: sftp: "Failure" (SSH_FX_FAILURE)
Save(<data/152265f020>) returned error, retrying after 6.138326764s: Write: sftp: "Failure" (SSH_FX_FAILURE)
Save(<data/f73a49bbe2>) returned error, retrying after 4.545179123s: Write: sftp: "Failure" (SSH_FX_FAILURE)
Save(<data/f5e7222fc9>) returned error, retrying after 7.009085549s: Write: sftp: "Failure" (SSH_FX_FAILURE)
Save(<data/e8ea901191>) returned error, retrying after 10.558950745s: Write: sftp: "Failure" (SSH_FX_FAILURE)
Save(<data/f73a49bbe2>) returned error, retrying after 7.730524827s: Write: sftp: "Failure" (SSH_FX_FAILURE)
Save(<data/152265f020>) returned error, retrying after 10.06168457s: Write: sftp: "Failure" (SSH_FX_FAILURE)
Save(<data/f5e7222fc9>) returned error, retrying after 17.136020774s: Write: sftp: "Failure" (SSH_FX_FAILURE)
Save(<data/f73a49bbe2>) returned error, retrying after 18.862930378s: Write: sftp: "Failure" (SSH_FX_FAILURE)
Save(<data/e8ea901191>) returned error, retrying after 11.0497682s: Write: sftp: "Failure" (SSH_FX_FAILURE)
Save(<data/152265f020>) returned error, retrying after 11.976267608s: Write: sftp: "Failure" (SSH_FX_FAILURE)
Save(<data/e8ea901191>) returned error, retrying after 20.965183681s: Write: sftp: "Failure" (SSH_FX_FAILURE)
Save(<data/f5e7222fc9>) returned error, retrying after 19.151448088s: Write: sftp: "Failure" (SSH_FX_FAILURE)
Save(<data/152265f020>) returned error, retrying after 17.99834434s: Write: sftp: "Failure" (SSH_FX_FAILURE)
Save(<data/f73a49bbe2>) returned error, retrying after 18.883270334s: Write: sftp: "Failure" (SSH_FX_FAILURE)
Fatal: unable to save snapshot: Write: sftp: "Failure" (SSH_FX_FAILURE)

```
</details>

Steps to reproduce the behavior
-------------------------------

unfortunately i can't provide any useful information :(

Do you have any idea what may have caused this?
-----------------------------------------------
no :(

Do you have an idea how to solve the issue?
-------------------------------------------
and an aditional "no" :)

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
I really, really love restic and its design principles.
Its an great software which helps me a lot. <3

### PR DESCRIPTION
**Pull request by greatroar**
What does this PR change? What problem does it solve?
-----------------------------------------------------

The SFTP backend now checks whether an error in Save is ENOSPC. It also does a Chmod earlier and tries to remove broken files when an error occurs. Tested by backing up into a tiny loopback device over SFTP:

```
$ mount | grep loop
/dev/loop121 on /mnt type ext4 (rw,relatime)
$ ./restic init -r /mnt/r
created restic repository 1b0bf898e0 at /mnt/r

Please note that knowledge of your password is required to access
the repository. Losing your password means that your data is
irrecoverably lost.
$ ./restic -r sftp://localhost//mnt/r backup .
repository 1b0bf898 opened successfully, password is correct
created new cache in /home/me/.cache/restic
no parent snapshot found, will read all files
Fatal: unable to save snapshot: sftp: no space left on device
```

Was the change discussed in an issue or in the forum before?
------------------------------------------------------------

Fixes #3336.

Checklist
---------

- [x] I have read the [Contribution Guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches)
- [x] I have enabled [maintainer edits for this PR](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)
- [ ] I have added tests for all changes in this PR
- [ ] I have added documentation for the changes (in the manual)
- [x] There's a new file in `changelog/unreleased/` that describes the changes for our users (template [here](https://github.com/restic/restic/blob/master/changelog/TEMPLATE))
- [x] I have run `gofmt` on the code in all commits
- [x] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits)
- [x] I'm done, this Pull Request is ready for review

### CODE REVIEW

File: internal/backend/sftp/sftp.go [hunk 1]
```diff
@@ -258,23 +258,40 @@ func (r *SFTP) Save(ctx context.Context, h restic.Handle, rd restic.RewindReader
 	}
 
 	filename := r.Filename(h)
+	dirname := r.Dirname(h)
 
-	// create new file
-	f, err := r.c.OpenFile(filename, os.O_CREATE|os.O_EXCL|os.O_WRONLY)
+	// Ensure that the containing directory exists.
+	if err := r.c.MkdirAll(dirname); err != nil {
```
Comment (MichaelEischer) [inline internal/backend/sftp/sftp.go:264]: When backing up to a remote SFTP server, this adds a full round-trip just to create a directory which usually already exists. I'd like to keep the old optimistic behavior of just opening the file and then creating the directory if that didn't work.

File: internal/backend/sftp/sftp.go [hunk 2]
```diff
@@ -258,23 +258,40 @@ func (r *SFTP) Save(ctx context.Context, h restic.Handle, rd restic.RewindReader
...
-			debug.Log("error creating dir %v: %v", r.Dirname(h), mkdirErr)
-		} else {
-			// try again
-			f, err = r.c.OpenFile(filename, os.O_CREATE|os.O_EXCL|os.O_WRONLY)
-		}
+	// Try and see if there is space left for this file.
+	// We do this because the OpenSSH sftp-server only returns
+	// a generic "failure" code when the filesystem is full,
+	// so detecting after the fact is impossible.
+	if err := r.checkSpace(dirname, rd.Length()); err != nil {
```
Comment (MichaelEischer) [inline internal/backend/sftp/sftp.go:273]: This has a similar performance problem as `MkdirAll`. `checkSpace` is expected to nearly always return that there is still enough free space. So why not try creating the file first and if that fails, just check whether we ran out of space?

File: internal/backend/sftp/sftp.go [hunk 3]
```diff
@@ -258,23 +258,40 @@ func (r *SFTP) Save(ctx context.Context, h restic.Handle, rd restic.RewindReader
...
+			return
+		}
+		err := r.c.Remove(f.Name())
+		if err != nil {
+			debug.Log("sftp failed to remove broken file %v: %v", filename, err)
+		}
+	}()
+
+	// pkg/sftp doesn't allow creating with a mode.
+	if err = f.Chmod(backend.Modes.File); err != nil {
```
Comment (MichaelEischer) [inline internal/backend/sftp/sftp.go:293]: What is the reason for changing the file permissions earlier on (just curious)?

**Review by MichaelEischer — CHANGES_REQUESTED** [review]

File: internal/backend/sftp/sftp.go (hunk 1 above)
Comment (greatroar) [reply internal/backend/sftp/sftp.go:264]: This was added because the directory has to exist for StatVFS. But if we check after the fact, it's not needed.

File: internal/backend/sftp/sftp.go (hunk 3 above)
Comment (greatroar) [reply internal/backend/sftp/sftp.go:293]: If we set them later, remote users may see what is written to the backup file while we're busy (depending on the remote umask).

File: internal/backend/sftp/sftp.go (hunk 2 above)
Comment (greatroar) [reply internal/backend/sftp/sftp.go]: Ok, did that instead.

**Comment by greatroar** [comment]
The new lint check is great. It actually caught an unused method that I left in the code.

**Review by MichaelEischer — APPROVED** [review]
LGTM. Thanks and sorry for the long review delay.
