### PR TITLE
Check for arguments before opening remote connection in cat command

### LINKED ISSUE #4416: `cat`: Parse arguments before doing remote connections
Output of `restic version`
--------------------------

```
restic 0.15.2 compiled with go1.20.3 on linux/amd64
```

How did you run restic exactly?
-------------------------------

```
restic cat locks 4e399071437898e7d419d41039d77b1aad719cdc9f5ebc0d7fd31fb979cc1b8b
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

Expected behavior
-----------------

```
"locks" is not a correct argument, select among
[pack|blob|snapshot|index|key|masterkey|config|lock]
```

Actual behavior
---------------

```
repository a72e6e8d opened (version 1)
Fatal: invalid type
```

Steps to reproduce the behavior
-------------------------------

Do you have any idea what may have caused this?
-----------------------------------------------

Do you have an idea how to solve the issue?
-------------------------------------------

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

### PR DESCRIPTION
**Pull request by 2000yeshu**
What does this PR change? What problem does it solve?
-----------------------------------------------------
Check for arguments to `cat` command befire opening the remote connection

Checking the allowed arguments from an array

Was the change previously discussed in an issue or on the forum?
----------------------------------------------------------------
#4416

Closes #4416 

Checklist
---------

- [ ] I have read the [contribution guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches).
- [ ] I have [enabled maintainer edits](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [ ] I have added tests for all code changes.
- [ ] I have added documentation for relevant changes (in the manual).
- [ ] There's a new file in `changelog/unreleased/` that describes the changes for our users (see [template](https://github.com/restic/restic/blob/master/changelog/TEMPLATE)).
- [x] I have run `gofmt` on the code in all commits.
- [x] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits).
- [x] I'm done! This pull request is ready for review.

### CODE REVIEW

File: cmd/restic/cmd_cat.go [hunk 1]
```diff
@@ -33,9 +33,35 @@ func init() {
...
+	}
+
+	var found bool
+	for _, v := range allowedTypes {
+		if v == args[0] {
+			found = true
+		}
+	}
+	if !found {
+		return errors.Fatalf("\"%s\" is not a correct argument, select among\n[%s]", args[0], getPipeSeperatedTypes(allowedTypes))
```
Comment (MichaelEischer) [inline cmd/restic/cmd_cat.go:60]: Please replace `getPipeSeperatedTypes()` with `strings.Join()`.
I'd also prefer a single line error message:
```
invalid type %q, must be one of [%s]
```

File: cmd/restic/cmd_cat.go [hunk 2]
```diff
@@ -33,9 +33,35 @@ func init() {
...
+		}
+		str += t
+	}
+	return
+}
+
 func runCat(ctx context.Context, gopts GlobalOptions, args []string) error {
-	if len(args) < 1 || (args[0] != "masterkey" && args[0] != "config" && len(args) != 2) {
-		return errors.Fatal("type or ID not specified")
+	allowedTypes := []string{"config", "index", "snapshot", "key", "masterkey", "lock", "pack", "blob", "tree"}
```
Comment (MichaelEischer) [inline cmd/restic/cmd_cat.go:47]: please extract the parameter validation into a separate function that's called by `runCat`.

**Review by MichaelEischer — CHANGES_REQUESTED** [review]
Thanks for working on this issue! The PR needs a few small improvements as described below.

**Review by MichaelEischer — APPROVED** [review]
LGTM.

I've extracted the full parameter validation and added a short test.
