### PR TITLE
Skip ExtendedAttribute processing in Windows for volumes that do not support EA

### LINKED ISSUE #4955: [Regression] restic 0.17.0 on Windows: cannot backup using network drive
Output of `restic version`
--------------------------
restic 0.17.0 compiled with go1.22.5 on windows/amd64

What backend/service did you use to store the repository?
---------------------------------------------------------
A network share mounted as drive H

Problem description / Steps to reproduce
----------------------------------------
On my employer's computer, I need to back up my data to a network drive, which is mounted locally as drive `H`. My `restic` command backs up files from both my local hard drive and the target drive itself. So, in addition to the backup, other data is also stored on the network drive. This worked flawlessly with `restic` up to version 0.16.x. However, since version 0.17.0, the following error message appears:

```
Fatal: unable to save snapshot: nodeFromFileInfo h:\: get EA failed for path h:\, with: get file EA failed with: Incorrect function.
``` 

My command:
```
restic --repo H:\Backup backup --exclude-caches --iexclude-file="c:\Users\xxx\backup-ignore.txt" --files-from="c:\Users\xxx\backup-resources.txt" --tag main --tag data --compression=auto --read-concurrency=6
```

The entire output looks like this:
```
pattern "c:\\Users\\xxx\\AppData\\Roaming\\Sublime Text 3\\Local\\" does not match any files, skipping
enter password for repository:
repository 6b02e3c8 opened (version 2, compression level auto)
found 1 old cache directories in C:\Users\xxx\AppData\Local\restic, run `restic cache --cleanup` to remove them
using parent snapshot 9e08dbd0
[0:00] 100.00%  13 / 13 index files loaded
Fatal: unable to save snapshot: nodeFromFileInfo h:\: get EA failed for path h:\, with: get file EA failed with: Incorrect function.
```

Expected behavior
-----------------
The backup to and from the network drive should work.

Actual behavior
---------------
No snapshot will be created, Instead, we got this error:
```
Fatal: unable to save snapshot: nodeFromFileInfo h:\: get EA failed for path h:\, with: get file EA failed with: Incorrect function.
``` 

Do you have any idea what may have caused this?
-----------------------------------------------
@MichaelEischer mentioned on the [forum](https://forum.restic.net/t/backing-up-data-on-windows-from-smb-share-to-local-drive/8095): `This looks like a potential bug in the new metadata collection changes in restic 0.17.0`

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
Restic makes me happy: Finally a reliable backup software I can rely on. It also runs on all my systems: Linux, Windows, and macOS. Thank you very much for your work and all the time you have invested in the software.

### PR DESCRIPTION
**Pull request by aneesh-n**
What does this PR change? What problem does it solve?
-----------------------------------------------------
Some windows paths like network drives do not support ExtendedAttributes. Either they return error codes like windows.E_NOT_SET or windows.ERROR_INVALID_FUNCTION or it results in slower backups.
This PR aims to skip processing the ExtendedAttributes after detecting if the volume does not support them.
It completely skips the attempt to fetch Extended Attributes instead of trying to handle errors after trying to fetch EA for files on such volumes.

Was the change previously discussed in an issue or on the forum?
----------------------------------------------------------------

May resolve https://github.com/restic/restic/issues/4955 and https://github.com/restic/restic/issues/4950

Checklist
---------

- [x] I have read the [contribution guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches).
- [x] I have [enabled maintainer edits](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [ ] I have added tests for all code changes.
- [ ] I have added documentation for relevant changes (in the manual).
- [x] There's a new file in `changelog/unreleased/` that describes the changes for our users (see [template](https://github.com/restic/restic/blob/master/changelog/TEMPLATE)).
- [x] I have run `gofmt` on the code in all commits.
- [x] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits).
- [x] I'm done! This pull request is ready for review.

### CODE REVIEW

File: internal/fs/ea_windows.go [hunk 1]
```diff
@@ -283,3 +292,34 @@ func setFileEA(handle windows.Handle, iosb *ioStatusBlock, buf *uint8, bufLen ui
...
+		uintptr(unsafe.Pointer(&maxComponentLen)),
+		uintptr(unsafe.Pointer(&fileSystemFlags)),
+		uintptr(unsafe.Pointer(&fsName[0])),
+		uintptr(len(fsName)),
+	)
+	if ret == 0 {
+		return false, err
+	}
+
+	supportsEAs := (fileSystemFlags & fileSupportsExtendedAttributes) != 0
```
Comment (aneesh-n) [inline internal/fs/ea_windows.go:323]: Need to confirm if this is the best way to check for extended attributes. Have tested positive and negative scenarios for this check.

Another option would be to check if the file system name is NTFS, which supports Extended Attributes
fsNameStr := syscall.UTF16ToString(fsName[:])
supportsEAs := fsNameStr == "NTFS"

File: internal/restic/node_windows.go [hunk 2]
```diff
@@ -358,7 +361,20 @@ func (node *Node) fillGenericAttributes(path string, fi os.FileInfo, stat *statT
 		// Also do not allow processing of extended attributes for ADS.
 		return false, nil
 	}
-	if !strings.HasSuffix(filepath.Clean(path), `\`) {
+	if strings.HasSuffix(filepath.Clean(path), `\`) {
```
Comment (MichaelEischer) [inline internal/restic/node_windows.go:364]: This approach won't work for backups using relative paths.
```
cd /D Z:   # some network share
restic backup local/file
```

File: internal/restic/node_windows.go [hunk 3]
```diff
@@ -32,6 +32,9 @@ var (
 	modAdvapi32     = syscall.NewLazyDLL("advapi32.dll")
 	procEncryptFile = modAdvapi32.NewProc("EncryptFileW")
 	procDecryptFile = modAdvapi32.NewProc("DecryptFileW")
+
+	// eaUnsupportedVolumesMap is a map of volumes that do not support extended attributes.
+	eaUnsupportedVolumesMap = map[string]bool{}
```
Comment (MichaelEischer) [inline internal/restic/node_windows.go:37]: I'm really no fan of introducing additional global state as it usually leads to problems sooner or later. However, until I've moved the NodeFromFileInfo and related code into the `internal/fs` package, I don't see a good  way to avoid it. Either way this map MUST be synchronized.

**Review by MichaelEischer — CHANGES_REQUESTED** [review]
I guess we can give this approach a try. I've found a few problems though, see below.

File: internal/fs/ea_windows.go [hunk 4]
```diff
@@ -53,6 +53,16 @@ var (
 	errInvalidEaBuffer = errors.New("invalid extended attribute buffer")
 	errEaNameTooLarge  = errors.New("extended attribute name too large")
 	errEaValueTooLarge = errors.New("extended attribute value too large")
+
+	kernel32dll = syscall.NewLazyDLL("kernel32.dll")
+
+	procGetVolumeInformationW = kernel32dll.NewProc("GetVolumeInformationW")
```
[the remark this answers is not in the document]
Comment (aneesh-n) [reply internal/fs/ea_windows.go]: Fixed

File: internal/fs/ea_windows.go [hunk 5]
```diff
@@ -53,6 +53,16 @@ var (
...
+)
+
+const (
+	// fileSupportsExtendedAttributes is a bitmask that indicates whether the file system supports extended attributes.
+	// https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/ntifs/ns-ntifs-_file_fs_attribute_information
+	fileSupportsExtendedAttributes = 0x00800000
```
[the remark this answers is not in the document]
Comment (aneesh-n) [reply internal/fs/ea_windows.go]: Fixed

File: internal/fs/ea_windows.go [hunk 6]
```diff
@@ -283,3 +293,34 @@ func setFileEA(handle windows.Handle, iosb *ioStatusBlock, buf *uint8, bufLen ui
...
+		maxComponentLen uint32
+		fileSystemFlags uint32
+	)
+	utf16Path, err := windows.UTF16PtrFromString(path)
+	if err != nil {
+		return false, err
+	}
+	ret, _, err := procGetVolumeInformationW.Call(
+		uintptr(unsafe.Pointer(utf16Path)),
+		uintptr(unsafe.Pointer(&volumeName[0])),
```
[the remark this answers is not in the document]
Comment (aneesh-n) [reply internal/fs/ea_windows.go]: Fixed

File: internal/restic/node_windows.go (hunk 3 above)
Comment (aneesh-n) [reply internal/restic/node_windows.go]: I agree. We can revisit later
Fixed using sync.Map

File: internal/restic/node_windows.go (hunk 2 above)
Comment (aneesh-n) [reply internal/restic/node_windows.go:372]: Thanks, I believe I've addressed this now.

File: internal/fs/ea_windows.go [hunk 7]
```diff
@@ -283,3 +283,18 @@ func setFileEA(handle windows.Handle, iosb *ioStatusBlock, buf *uint8, bufLen ui
...
+// PathSupportsExtendedAttributes returns true if the path supports extended attributes.
+func PathSupportsExtendedAttributes(path string) (supported bool, err error) {
+	var fileSystemFlags uint32
+	utf16Path, err := windows.UTF16PtrFromString(path)
+	if err != nil {
+		return false, err
+	}
+	err = windows.GetVolumeInformation(utf16Path, nil, 0, nil, nil, &fileSystemFlags, nil, 0)
+	if err != nil {
+		return false, err
```
Comment (aneesh-n) [inline internal/fs/ea_windows.go:296]: Should we just log this as a debug log and not return the err so that it falls back to skipping EA if any issue occurs?

Comment (MichaelEischer) [reply internal/fs/ea_windows.go:296]: Let's start with returning an error and see whether problems can show up.

File: internal/restic/node_windows.go [hunk 8]
```diff
@@ -351,32 +361,84 @@ func decryptFile(pathPointer *uint16) error {
...
+
+	var sd *[]byte
+	if node.Type == "file" || node.Type == "dir" {
+		// Check EA support and get security descriptor for file/dir only
+		allowExtended, err = checkAndStoreEASupport(path)
+		if err != nil {
+			return false, err
+		}
+		if sd, err = fs.GetSecurityDescriptor(path); err != nil {
+			return true, err
```
Comment (MichaelEischer) [inline internal/restic/node_windows.go:395]: Must return `allowExtended` here instead of `true`. Otherwise, extended attributes will always be read if reading the security descriptor fails.

File: internal/restic/node_windows.go [hunk 9]
```diff
@@ -351,32 +361,84 @@ func decryptFile(pathPointer *uint16) error {
...
+	}
+
+	var sd *[]byte
+	if node.Type == "file" || node.Type == "dir" {
+		// Check EA support and get security descriptor for file/dir only
+		allowExtended, err = checkAndStoreEASupport(path)
+		if err != nil {
+			return false, err
+		}
+		if sd, err = fs.GetSecurityDescriptor(path); err != nil {
```
Comment (MichaelEischer) [inline internal/restic/node_windows.go:394]: While testing this PR, I've noticed that `GetSecurityDescriptor` can return `ERROR_NOT_SUPPORTED`. This error should be filtered out in that method:
```diff
 			if err != nil {
 				return nil, fmt.Errorf("get low-level named security info failed with: %w", err)
 			}
+		} else if errors.Is(err, windows.ERROR_NOT_SUPPORTED) {
+			return nil, nil
 		} else {
 			return nil, fmt.Errorf("get named security info failed with: %w", err)
 		}
```

**Review by MichaelEischer — CHANGES_REQUESTED** [review]
This seems to almost work, see the comments for the remaining problems.

File: changelog/unreleased/pull-4980 [hunk 10]
```diff
@@ -0,0 +1,10 @@
+Bugfix: Skip EA processing in Windows for volumes that do not support EA
+
+Restic was failing to backup files on some windows paths like network
+drives because of errors while fetching ExtendedAttributes.
+Either they return error codes like windows.E_NOT_SET or
+windows.ERROR_INVALID_FUNCTION or it results in slower backups.
+Restic now completely skips the attempt to fetch Extended Attributes
+for such volumes where it is not supported.
+
+https://github.com/restic/restic/pull/4980
```
Comment (MichaelEischer) [inline changelog/unreleased/pull-4980:10]: Please link to both issues that are solved by this PR.

**Review by MichaelEischer — APPROVED** [review]
LGTM. Thanks!

File: internal/restic/node_windows.go [hunk 11]
```diff
@@ -351,32 +361,84 @@ func decryptFile(pathPointer *uint16) error {
...
+func checkAndStoreEASupport(path string) (isEASupportedVolume bool, err error) {
+	// Check if it's an extended length path
+	if strings.HasPrefix(path, uncPathPrefix) {
+		// Convert \\?\UNC\ extended path to standard path to get the volume name correctly
+		path = `\\` + path[len(uncPathPrefix):]
+	} else if strings.HasPrefix(path, extendedPathPrefix) {
+		//Extended length path prefix needs to be trimmed to get the volume name correctly
+		path = path[len(extendedPathPrefix):]
+	} else if strings.HasPrefix(path, globalRootPrefix) {
+		// EAs are not supported for \\?\GLOBALROOT i.e. VSS snapshots
```
Comment (aneesh-n) [inline internal/restic/node_windows.go:418]: I made a mistake here while fixing the test case errors. 
Extended attributes are in fact supported for VSS snapshots.
Instead of returning false, we should be handling the volume names for VSS snapshots correctly. Apologies, I can add a separate PR.

Comment (MichaelEischer) [reply internal/restic/node_windows.go:418]: > Instead of returning false, we should be handling the volume names for VSS snapshots correctly. Apologies, I can add a separate PR.

Does `GetVolumeInformation` support such paths or do we needs even more weird special case handling?

Comment (aneesh-n) [reply internal/restic/node_windows.go:418]: We need to get the 'volumeName' path like this - 
        
```
// Extract the VSS snapshot volume name eg. `\\?\GLOBALROOT\Device\HarddiskVolumeShadowCopyXX`
if parts := strings.SplitN(path, `\`, 7); len(parts) >= 6 {
	volumeName = strings.Join(parts[:6], `\`)
}
```
		
Rest of the code remains same-

fs.PathSupportsExtendedAttributes(volumeName + `\`) i.e. GetVolumeInformation works.

Comment (MichaelEischer) [reply internal/restic/node_windows.go:418]: Sigh, I'm not happy about all those Windows special case. But looks like we'd better add them. Can you open a PR for it?

Comment (aneesh-n) [reply internal/restic/node_windows.go:418]: Yeah, problem is filepath.VolumeName does not do any windows specific handling, it's just syntactical. 
We can probably get actual volumeName using windows.GetVolumeInformation itself, but it would mean we need to make the system call for every path. 
Right now, we are doing all that manual processing to avoid the system call.
