### PR TITLE
Fix: Correctly restore ACL inheritance state

### LINKED ISSUE #5427: Backup & Restore "IsInherited" Property on Windows
Output of `restic version`
--------------------------
```
PS C:\Program Files (x86)\restic> ./restic version
restic 0.18.0 compiled with go1.24.1 on windows/amd64
```

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

The addition of backing up SecurityDescriptors on Windows #4708 is fantastic, however I have noticed that restic does not restore the `IsInherited` property on files/directories.

Example:

**Output prior to backup**

```
PS C:\Windows\system32> $ACL = Get-Acl "E:\restic_test_root\level1\level2\level3"
$ACL.Access

FileSystemRights  : FullControl
AccessControlType : Allow
IdentityReference : BUILTIN\Administrators
IsInherited       : True
InheritanceFlags  : ContainerInherit, ObjectInherit
PropagationFlags  : None

FileSystemRights  : FullControl
AccessControlType : Allow
IdentityReference : NT AUTHORITY\SYSTEM
IsInherited       : True
InheritanceFlags  : ContainerInherit, ObjectInherit
PropagationFlags  : None

```
**Output after restore**

```
PS C:\Program Files (x86)\restic> $ACL = Get-Acl "E:\restic_test_root\level1\level2\level3"
$ACL.Access

FileSystemRights  : FullControl
AccessControlType : Allow
IdentityReference : BUILTIN\Administrators
IsInherited       : False
InheritanceFlags  : ContainerInherit, ObjectInherit
PropagationFlags  : None

FileSystemRights  : FullControl
AccessControlType : Allow
IdentityReference : NT AUTHORITY\SYSTEM
IsInherited       : False
InheritanceFlags  : ContainerInherit, ObjectInherit
PropagationFlags  : None


```

What are you trying to do? What problem would this solve?
---------------------------------------------------------

Having the original Inheritance properties is important when restoring, to retain the flow of permissions on child objects.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Always. Your hard work maintaining this excellent project is well appreciated!

### PR DESCRIPTION
**Pull request by aneesh-n**
What does this PR change? What problem does it solve?
-----------------------------------------------------

When restoring a file or directory on Windows, the `IsInherited` property of its Access Control Entries (ACEs) was always being set to `False`, even if the ACEs were inherited in the original backup.

This was caused by the restore process calling the `SetNamedSecurityInfo` API without providing context about the object's inheritance policy. By default, this API applies the provided Discretionary Access Control List (DACL) as an explicit set of permissions, thereby losing the original inheritance state.

This commit fixes the issue by inspecting the `Control` flags of the saved Security Descriptor during restore. Based on whether the `SE_DACL_PROTECTED` flag is present, the code now adds the appropriate `PROTECTED_DACL_SECURITY_INFORMATION` or `UNPROTECTED_DACL_SECURITY_INFORMATION` flag to the `SetNamedSecurityInfo` API call.

By providing this crucial inheritance context, the Windows API can now correctly reconstruct the ACL, ensuring the `IsInherited` status of each ACE is preserved as it was at the time of backup.

Was the change previously discussed in an issue or on the forum?
----------------------------------------------------------------

Closes https://github.com/restic/restic/issues/5427

Checklist
---------

- [x] I have added tests for all code changes.
- [ ] I have added documentation for relevant changes (in the manual).
- [x] There's a new file in `changelog/unreleased/` that describes the changes for our users (see [template](https://github.com/restic/restic/blob/master/changelog/TEMPLATE)).
- [x] I'm done! This pull request is ready for review.

### CODE REVIEW

File: internal/fs/sd_windows.go [hunk 1]
```diff
@@ -150,8 +157,31 @@ func getNamedSecurityInfoLow(filePath string) (*windows.SECURITY_DESCRIPTOR, err
...
 // setNamedSecurityInfoHigh sets the higher level SecurityDescriptor which requires admin permissions.
-func setNamedSecurityInfoHigh(filePath string, owner *windows.SID, group *windows.SID, dacl *windows.ACL, sacl *windows.ACL) error {
-	return windows.SetNamedSecurityInfo(fixpath(filePath), windows.SE_FILE_OBJECT, highSecurityFlags, owner, group, dacl, sacl)
+func setNamedSecurityInfoHigh(filePath string, owner *windows.SID, group *windows.SID, dacl *windows.ACL, sacl *windows.ACL, control windows.SECURITY_DESCRIPTOR_CONTROL) error {
+	securityInfo := highSecurityFlags
+
+	// Remove all protection flags first to ensure a clean state before adding the correct one.
+	// The highSecurityFlags variable contains all of them, which is fine for GET operations,
+	// but for SET operations, we must specify only one of PROTECTED or UNPROTECTED.
+	securityInfo &^= (windows.PROTECTED_DACL_SECURITY_INFORMATION | windows.UNPROTECTED_DACL_SECURITY_INFORMATION)
```
Comment (MichaelEischer) [inline internal/fs/sd_windows.go]: lowRestoreSecurityFlags also contains `PROTECTED_DACL_SECURITY_INFORMATION`. Do we need similar handling there?

File: internal/fs/sd_windows.go [hunk 2]
```diff
@@ -150,8 +157,31 @@ func getNamedSecurityInfoLow(filePath string) (*windows.SECURITY_DESCRIPTOR, err
 }
 
 // setNamedSecurityInfoHigh sets the higher level SecurityDescriptor which requires admin permissions.
-func setNamedSecurityInfoHigh(filePath string, owner *windows.SID, group *windows.SID, dacl *windows.ACL, sacl *windows.ACL) error {
-	return windows.SetNamedSecurityInfo(fixpath(filePath), windows.SE_FILE_OBJECT, highSecurityFlags, owner, group, dacl, sacl)
+func setNamedSecurityInfoHigh(filePath string, owner *windows.SID, group *windows.SID, dacl *windows.ACL, sacl *windows.ACL, control windows.SECURITY_DESCRIPTOR_CONTROL) error {
+	securityInfo := highSecurityFlags
```
Comment (MichaelEischer) [inline internal/fs/sd_windows.go]: What about splitting the `highSecurityFlags` into a backup and restore variant? Then we don't need to drop the flags below. The `highBackupSecurityFlags` would then be based just add those flags to the `highRestoreSecurityFlags`.

**Review by MichaelEischer — COMMENTED** [review]
Thanks! I just have two questions/suggestion below.

**Review by MichaelEischer — CHANGES_REQUESTED** [review]
@aneesh-n can you take a look at the two comments above? Feel free to just close those comments if they aren't relevant.

File: internal/fs/sd_windows.go (hunk 1 above)
Comment (aneesh-n) [reply internal/fs/sd_windows.go]: Thanks. Made the fix

File: internal/fs/sd_windows.go (hunk 2 above)
Comment (aneesh-n) [reply internal/fs/sd_windows.go]: Thanks, makes sense. Updated

**Review by MichaelEischer — APPROVED** [review]
LGTM. Thanks. I've rebased the PR to fix the merge conflict near

```
var lowerPrivileges atomic.Bool
```
