### PR TITLE
Fix #2688: Handle comma-separated list tags when using backup command

### LINKED ISSUE #2688: List snapshots with multiple filters tag and host filter not working ?
Output of `restic version`
-----------------
`restic 0.9.6 compiled with go1.13.4 on darwin/amd64`

How did you run restic exactly?
-----------------
```
~ ➜ restic snapshots                                       

repository 1a5af6f7 opened successfully, password is correct
ID        Time                 Host                   Tags              Paths
-----------------------------------------------------------------------------------------------------
313fa2a7  2020-04-11 14:40:22  kimsufi                minecraft,simon   /data/minecraft-server/simon
cf0b237f  2020-04-11 14:40:37  kimsufi                minecraft,survie  /data/minecraft-server/survie
8260b61a  2020-04-11 14:49:02  kimsufi                minecraft,simon   /data/minecraft-server/simon
c4db6d76  2020-04-11 14:49:18  kimsufi                minecraft,survie  /data/minecraft-server/survie
d12127dd  2020-04-11 14:55:38  kimsufi                minecraft,simon   /data/minecraft-server/simon
59104702  2020-04-11 14:55:54  kimsufi                minecraft,survie  /data/minecraft-server/survie
039abf77  2020-04-11 15:05:51  kimsufi                minecraft,simon   /data/minecraft-server/simon
4b6f9eb0  2020-04-11 15:06:06  kimsufi                minecraft,survie  /data/minecraft-server/survie
980e3bbf  2020-04-11 15:27:00  kimsufi                rancher           /rancher-database.sql
8bbdfd9a  2020-04-11 15:29:00  kimsufi                rancher           /rancher-database.sql
97ec3fab  2020-04-11 16:24:49  kimsufi                minecraft,simon   /data/minecraft-server/simon
0cfe2915  2020-04-11 16:25:06  kimsufi                minecraft,survie  /data/minecraft-server/survie
c18cae9e  2020-04-11 16:34:19  management.aloesia.fr  aloesia           /aloesia-database.sql
c2fa782d  2020-04-11 16:37:40  kimsufi                minecraft,simon   /data/minecraft-server/simon
0182cd9f  2020-04-11 16:37:56  kimsufi                minecraft,survie  /data/minecraft-server/survie
0bd84c34  2020-04-11 16:38:13  kimsufi                minecraft,config  /server.properties
-----------------------------------------------------------------------------------------------------
16 snapshots
~ ➜ restic snapshots --host kimsufi --tag "minecraft,simon"
repository 1a5af6f7 opened successfully, password is correct
```

What backend/server/service did you use to store the repository?
-----------------
`GCS`

Expected behavior
-----------------

```
~ ➜ restic snapshots --host kimsufi --tag "minecraft,simon"
repository 1a5af6f7 opened successfully, password is correct

ID        Time                 Host                   Tags              Paths
-----------------------------------------------------------------------------------------------------
313fa2a7  2020-04-11 14:40:22  kimsufi                minecraft,simon   /data/minecraft-server/simon
8260b61a  2020-04-11 14:49:02  kimsufi                minecraft,simon   /data/minecraft-server/simon
d12127dd  2020-04-11 14:55:38  kimsufi                minecraft,simon   /data/minecraft-server/simon
039abf77  2020-04-11 15:05:51  kimsufi                minecraft,simon   /data/minecraft-server/simon
97ec3fab  2020-04-11 16:24:49  kimsufi                minecraft,simon   /data/minecraft-server/simon
c2fa782d  2020-04-11 16:37:40  kimsufi                minecraft,simon   /data/minecraft-server/simon
-----------------------------------------------------------------------------------------------------
6 snapshots
```

Actual behavior
---------------

Not snapshots found, but no errors neither

Steps to reproduce the behavior
-------------------------------

1. Backup with a tag
2. List snapshots filtering by host and this tag

Do you have any idea what may have caused this?
-----------------------------------------------

Maybe is not supported ? But there is no errors

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Sure !!

### PR DESCRIPTION
**Pull request by SkYNewZ**
What is the purpose of this change? What does it change?
--------------------------------------------------------
Handle comma-separated list tags when using backup command

Was the change discussed in an issue or in the forum before?
------------------------------------------------------------
closes #2688 

Checklist
---------

- [x] I have read the [Contribution Guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches)
- [x] I have enabled [maintainer edits for this PR](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)
- [x] I have added tests for all changes in this PR
- [x] I have added documentation for the changes (in the manual)
- [x] There's a new file in `changelog/unreleased/` that describes the changes for our users (template [here](https://github.com/restic/restic/blob/master/changelog/TEMPLATE))
- [x] I have run `gofmt` on the code in all commits
- [x] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits)
- [x] I'm done, this Pull Request is ready for review

### CODE REVIEW

**Comment by SkYNewZ** [comment]
Screenshot 2020-04-13 at 04 24 18

File: changelog/unreleased/issue-2688 [hunk 1]
```diff
@@ -0,0 +1,8 @@
+Bugfix: Handle comma-separated list tags when using backup command
+
+Creating a backup by specifying comma-separated tags created a backup with this concatenated list as a tag.
+For example `restic backup --tag foo,bar` creates a new snapshot with one "foo,bar" tag instead of two tags, one "foo" and one "bar"?
+
+Simply type `[]string` to `restic.TagList` and use f.Var() to handle args. cobra did the rest!
```
Comment (MichaelEischer) [inline changelog/unreleased/issue-2688:6]: That explanation is too technical for most users. It should be enough to just state what the new behavior is, not how it's implemented.

File: changelog/unreleased/issue-2688 [hunk 2]
```diff
@@ -0,0 +1,8 @@
+Bugfix: Handle comma-separated list tags when using backup command
+
+Creating a backup by specifying comma-separated tags created a backup with this concatenated list as a tag.
+For example `restic backup --tag foo,bar` creates a new snapshot with one "foo,bar" tag instead of two tags, one "foo" and one "bar"?
```
Comment (MichaelEischer) [inline changelog/unreleased/issue-2688:4]: That example would be a good place to explain the differences between the old and new behavior.

File: cmd/restic/cmd_backup.go [hunk 3]
```diff
@@ -113,7 +113,7 @@ func init() {
 	f.BoolVar(&backupOptions.ExcludeCaches, "exclude-caches", false, `excludes cache directories that are marked with a CACHEDIR.TAG file. See http://bford.info/cachedir/spec.html for the Cache Directory Tagging Standard`)
 	f.BoolVar(&backupOptions.Stdin, "stdin", false, "read backup from stdin")
 	f.StringVar(&backupOptions.StdinFilename, "stdin-filename", "stdin", "`filename` to use when reading from stdin")
-	f.StringArrayVar(&backupOptions.Tags, "tag", nil, "add a `tag` for the new snapshot (can be specified multiple times)")
+	f.Var(&backupOptions.Tags, "tag", "add a `tag` for the new snapshot in the format `tag[,tag,...]` (can be specified multiple times)")
```
Comment (MichaelEischer) [inline cmd/restic/cmd_backup.go:116]: With this change you actually add tags to the new snapshot.

**Review by MichaelEischer — COMMENTED** [review]
Can you adjust the help text of the `snapshots` command to better match that of the `forget` command to make things more consistent?

Regarding consistency: The backup command merges its taglists while the forget / snapshots commands select snapshots that match any of the taglists. I'm not really sure whether that is clear from the help text.

The `doc/manual_rest.rst` file also needs updating.

File: cmd/restic/cmd_backup.go (hunk 3 above)
Comment (SkYNewZ) [reply cmd/restic/cmd_backup.go:116]: You mean just for the help message ? With a `s` ?

Comment (MichaelEischer) [reply cmd/restic/cmd_backup.go:116]: Yes. my idea was to replace "a \`tag\`" with \`tags\`

**Comment by MichaelEischer** [comment]
There's another command that operates with `[]string` for tags: the `tag` command.

**Comment by SkYNewZ** [comment]
Command `tag` the the right type no ? https://github.com/restic/restic/blob/master/cmd/restic/cmd_tag.go#L40

**Comment by MichaelEischer** [comment]
SetTags / AddTags / RemoveTags use raw lists, which means that they behave exactly like `backup` did.

**Comment by fd0** [comment]
Thanks for the contribution! In general I agree what's changed here, we just need to be a bit more explicit in the changelog about it:

Strictly speaking, this is a backwards-incompatible change: before, it was possible (but not sensible) to create tags for snapshots which contain commas, in the same way that you did in the issue. I suspect there are quite a few people who run `restic backup --tag foo,bar` in their scripts, so with this change this will create snapshots with two tags `["foo", "bar"]` instead of one (`["foo,bar"]`). While not a problem in itself, this will make `forget` consider the snapshots to be in different groups and will apply the retention policy to each group separately.

How about we add a section:

> Attention: If you have (maybe accidentally) run `restic backup --tag foo,bar`, you have created snapshots with a single tag containing a comma ("foo,bar"). Restic will now create snapshots with two tags ("foo" and "bar"), which may have unexpected results when using `restic forget`.

Thoughts?

**Comment by MichaelEischer** [comment]
@fd0 The change in behavior of `forget` would then be that it now is able to forget such snapshots, while that wasn't possible before? Would that qualify as "Change" in the changelog?

**Comment by SkYNewZ** [comment]
Can I do something more ? COVID19 steal my job so 🤷🏻‍♂️

**Comment by MichaelEischer** [comment]
@SkYNewZ Sorry for taking so long to further guide this PR, I've somehow lost track of it. Could you also change the `--set`, `--add` and `--remove` options of the `tag` command to also use `restic.TagLists` instead of `[]string`? These are from what I've seen the last places where a tag containing commas was not split. Fixing the broken tags is still possible using `tag --set ...`.

To simplify fixing multiple tags something like `restic snapshots --json --quiet | jq '.[] | select(contains({tags: ["test"]})) | .id'` would work to get a list of snapshot ids with a certain tag (“test” in the example query). Then use `restic tag --set cats --set dogs snapshotID [...]` to correct the tags.

**Comment by OJFord** [comment]
> before, it was possible (but not sensible) to create tags for snapshots which contain commas [...] Thoughts?

I think many more people will have inadvertently provided `--tag=a,b` than `--tag='Grammatical sentence, or something, deliberately containing commas'`; so I'd suggest it's worth re-evaluating existing comma-containing tags and splitting them, storing escaped commas going forwards if it's desirable to admit them still.

It's backwards-incompatible no matter what, but I think silently correcting those wrongs would be friendlier than breaking such users' inadvertently-working filtering, at the expense of breaking extremely few people's (if anyone's) deliberate commas.

That is, IMO, the break should be such that the warning is more like:
```
Attention: `backup --tag=` now takes comma-separated tags where it previously did not. If you have used this as a feature, for tags that (deliberately) contain commas, you must retag your snapshots to escape the comma before upgrading. For example: `restic snapshots --tag=foo,bar --json | jq -r '.[].id' | xargs restic tag --set='foo\\,bar'`.
```

**Comment by rawtaz** [comment]
@OJFord Not entirely sure if you're suggesting some automatic processing of "foo,bar" tags or not, but regardless, we're planning on making the backup and tag commands coherent with the rest of the commands, such that they do treat e.g. `--tag foo,bar` as two tags, `foo` and `bar`. We will write a changelog that clearly informs that this might affect current `forget` usage, and include info on how to rewrite the tags. Is this in line with what you meant?

**Comment by OJFord** [comment]
@rawtaz My suggestion is that this change not only going forward for new tags, but also retroactively for _existing_ `a,b` tags, operating under the assumption that they were always intended to be `a` & `b`, not `a\,b`.

This would of course break (without intervention) for people with deliberately-comma'd tags, but I expect they are far fewer.

**Comment by rawtaz** [comment]
Still not sure what you are suggesting, but we agree that `a,b` was in most cases likely indended as two separate tags rather than the user writing a sentence. I believe that our current goal is in line with what you're thinking.

File: changelog/unreleased/issue-2688 [hunk 4]
```diff
@@ -0,0 +1,6 @@
+Bugfix: Handle comma-separated list tags when using backup command
+
+Creating a backup by specifying comma-separated tags created a backup with this concatenated list as a tag.
+For example `restic backup --tag foo,bar` creates a new snapshot with one "foo,bar" tag instead of two tags, one "foo" and one "bar". Fixed now.
+
```
Comment (rawtaz) [inline changelog/unreleased/issue-2688:5]: Suggestion for an updated changelog entry:

~~~
Bugfix: Make backup and tag commands separate tags by comma

Running `restic backup --tag foo,bar` previously created snapshots with one
single tag containing a comma ("foo,bar") instead of two tags ("foo", "bar").
Similarly, the `tag` command's --set, --add and --remove options would treat
"foo,bar" as one tag instead of two tags. This was inconsistent with other
commands and often unexpected when one intended "foo,bar" to mean two tags.

To be consistent in all commands, restic now interprets "foo,bar" to mean two
separate tags ("foo" and "bar") instead of one tag ()"foo,bar") everywhere,
including in the `backup` and `tag` commands.

NOTE: This change might result in unexpected behavior in cases where you use
the `forget` command and filter on tags like "foo,bar". Snapshots previously
backed up with `--tag foo,bar` will still not match that filter, but snapshots
saved from now on will match that filter.

To replace "foo,bar" tags with "foo" and "bar" tags in old snapshots, you can
first generate a list of the relevant snapshots using a command like
`restic snapshots --json --quiet | jq '.[] | select(contains({tags: ["foo,bar"]})) | .id'
, and then use `restic tag --set foo --set bar snapshotID [...]` to set the new
tags. Please adjust the commands to real tag names and any additional tags.
~~~

**Comment by MichaelEischer** [comment]
@OJFord `restic snapshots --tag=foo,bar` already (that is without this PR) considers `foo` and `bar` to be separate tags. That is also the reason why my suggested command to fix the tags requires some `jq` magic. As one couldn't properly use tags with commas before, I don't think its worth the trouble and complexity to introduce escaping for commas.

Splitting the tag lists of existing snapshots on commas when loading them, would suddenly change grouping by tags in the forget command which seems to be quite problematic to me.

File: changelog/unreleased/issue-2688 [hunk 5]
```diff
@@ -0,0 +1,6 @@
...
+https://github.com/restic/restic/issues/2688
```
Comment (rawtaz) [inline changelog/unreleased/issue-2688:6]: Please update the entire changelog entry to the following :)

~~~
Bugfix: Make backup and tag commands separate tags by comma

Running `restic backup --tag foo,bar` previously created snapshots with one
single tag containing a comma ("foo,bar") instead of two tags ("foo", "bar").
Similarly, the `tag` command's --set, --add and --remove options would treat
"foo,bar" as one tag instead of two tags. This was inconsistent with other
commands and often unexpected when one intended "foo,bar" to mean two tags.

To be consistent in all commands, restic now interprets "foo,bar" to mean two
separate tags ("foo" and "bar") instead of one tag ("foo,bar") everywhere,
including in the `backup` and `tag` commands.

NOTE: This change might result in unexpected behavior in cases where you use
the `forget` command and filter on tags like "foo,bar". Snapshots previously
backed up with `--tag foo,bar` will still not match that filter, but snapshots
saved from now on will match that filter.

To replace "foo,bar" tags with "foo" and "bar" tags in old snapshots, you can
first generate a list of the relevant snapshots using a command like
`restic snapshots --json --quiet | jq '.[] | select(contains({tags: ["foo,bar"]})) | .id'`
, and then use `restic tag --set foo --set bar snapshotID [...]` to set the new
tags. Please adjust the commands to real tag names and any additional tags.

https://github.com/restic/restic/issues/2688
~~~

Comment (SkYNewZ) [reply changelog/unreleased/issue-2688:6]: Is this the only this you want ? 😄

Comment (rawtaz) [reply changelog/unreleased/issue-2688:6]: Yep, it is :D

Comment (OJFord) [reply changelog/unreleased/issue-2688:6]: @SkYNewZ *gentle ping* - I just popped back here to remind myself exactly what the problem is/whether fixed (i.e. checking that `backup --tag a --tag b` should work) - it'd be nice to have this in a release, thanks for your work on it :slightly_smiling_face:

Comment (SkYNewZ) [reply changelog/unreleased/issue-2688:6]: Yes, I'm sorry, I didn't take the time to make the changes in the changelog. I'll take care of it right now

Comment (SkYNewZ) [reply changelog/unreleased/issue-2688]: After rebasing my changes, I update the changelog entry as you asked to

**Comment by MichaelEischer** [comment]
@SkYNewZ Could you rebase again to the current master? That should hopefully fix the temperamental windows tests...

Right now the behavior of the `--set`, `--add` and `--remove` options of the `tag` command don't match the changelog ;-) . Please change the following lines to also use `restic.TagLists`

https://github.com/restic/restic/blob/8fca3e7a41f2bc3623a3953cbb681ef3a1f3eb51/cmd/restic/cmd_tag.go#L41-L43

**Comment by SkYNewZ** [comment]
Why `restic.TagLists` and no `restic.TagList` ?

File: cmd/restic/cmd_backup.go [hunk 6]
```diff
@@ -91,7 +91,7 @@ type BackupOptions struct {
 	ExcludeLargerThan       string
 	Stdin                   bool
 	StdinFilename           string
-	Tags                    []string
+	Tags                    restic.TagList
 	Host                    string
```
Comment (SkYNewZ) [inline cmd/restic/cmd_backup.go:95]: Because I'm using `restic.TagList` here

Comment (MichaelEischer) [reply cmd/restic/cmd_backup.go:95]: Oh, you're right it should be `restic.TagList`.

**Review by MichaelEischer — APPROVED** [review]
LGTM. Thanks for the cleanup :-)

I've add another commit to adjust the description of the  tag command options to be more in line with the other commands.
