### PR TITLE
backup: allow excluding online-only cloud files

### LINKED ISSUE #3697: Ignore Cloud files which are not synced locally
Output of `restic version`
--------------------------
restic 0.13.0 compiled with go1.18 on linux/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------

I am using the cloud every now and then, and when I am backing up my Windows machine, I get the following error if the file is not present locally:

```
{'during': 'archival',
'error': {'Err': 381,
'Op': 'read',
'Path': '\\\\?\\GLOBALROOT\\Device\\HarddiskVolumeShadowCopy11\\Users\\flo\\OneDrive\\Bilder\\xyz.jpg'},
'item': 'c:\\Users\\flo\\OneDrive\\Bilder\\xyz.jpg',
'message_type': 'error'}
```

Err 381 seems to be `ERROR_CLOUD_FILE_READ_ONLY_VOLUME`. As you can see, I am using VSS, so this error makes sense. Windows can not download and store this file on a shadow copy. I would go so far and say, Windows (triggered by restic) should never download those files - even if backing up without shadow copy.

Therefore I propose the following:
- Never try to backup files that are not locally present.
  I guess, at the moment, restic will trigger a download of all files which are not locally available during backup (if not using VSS).
  I think this is wrong behavior. A backup program should not make such large modifications to the state of the system being backed up.
- Maybe add a switch like `--force-download-cloud-files` which will activate this behavior explicitly,
  as of course there might be people that want to backup their cloud files, too. (Maybe even myself, but it should be done explicitly.)
- Abort with an error message if this switch and vss are used together.

  

What are you trying to do? What problem would this solve?
---------------------------------------------------------

Backing up cloud synced directories without errors.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
It helps me everyday since months!

### PR DESCRIPTION
**Pull request by m-wild**
What does this PR change? What problem does it solve?
-----------------------------------------------------

Allow excluding online-only cloud files (such as OneDrive Files On-Demand) with a switch `--exclude-cloud-files`

Assuming we have the following file `test.txt` in OneDrive, but not available on the device

image

image

Attempting to backup the file with the `--exclude-cloud-files` switch will not attempt to download the file locally, instead the file will be excluded.

```sh
restic -r test --verbose backup C:\Users\username\OneDrive\test.txt --exclude-cloud-files

open repository
repository e5f7dfde opened (version 2, compression level auto)
created new cache in C:\Users\username\AppData\Local\restic
no parent snapshot found, will read all files
load index files
[0:00]          0 index files loaded
start scan on [C:\Users\username\OneDrive\test.txt]
start backup on [C:\Users\username\OneDrive\test.txt]
scan finished in 0.003s: 0 files, 0 B

Files:           0 new,     0 changed,     0 unmodified
Dirs:            4 new,     0 changed,     0 unmodified
Data Blobs:      0 new
Tree Blobs:      5 new
Added to the repository: 2.425 KiB (1.841 KiB stored)

processed 0 files, 0 B in 0:00
snapshot 5ef1ff96 saved

```

```log
2024/08/08 22:39:41 archiver/tree.go:298	archiver.NewTree	1	result:
/C, root "C:\\", path "", meta "C:\\"
    /Users, root "", path "", meta "C:\\Users"
        /username, root "", path "", meta "C:\\Users\\username"
            /OneDrive, root "", path "", meta "C:\\Users\\username\\OneDrive"
                /test.txt, root "", path "C:\\Users\\username\\OneDrive\\test.txt", meta ""

...

2024/08/08 22:39:44 archiver/archiver.go:420	archiver.(*Archiver).save	40	/C/Users/username/OneDrive/test.txt target "C:\\Users\\username\\OneDrive\\test.txt", previous <nil>
2024/08/08 22:39:44 restic/exclude.go:404	main.collectRejectFuncs.rejectCloudFiles.func1	40	rejecting online-only cloud file C:\Users\username\OneDrive\test.txt
2024/08/08 22:39:44 archiver/archiver.go:443	archiver.(*Archiver).save	40	C:\Users\username\OneDrive\test.txt is excluded

```

Was the change previously discussed in an issue or on the forum?
----------------------------------------------------------------

Closes #3697

Checklist
---------

- [x] I have read the [contribution guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches).
- [x] I have [enabled maintainer edits](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [x] I have added tests for all code changes.
- [x] I have added documentation for relevant changes (in the manual).
- [x] There's a new file in `changelog/unreleased/` that describes the changes for our users (see [template](https://github.com/restic/restic/blob/master/changelog/TEMPLATE)).
- [x] I have run `gofmt` on the code in all commits.
- [x] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits).
- [x] I'm done! This pull request is ready for review.

### CODE REVIEW

File: cmd/restic/exclude.go [hunk 1]
```diff
@@ -385,6 +387,28 @@ func rejectBySize(maxSizeStr string) (RejectFunc, error) {
...
 
+// rejectCloudFiles returns a func which rejects files which are online-only cloud files
+func rejectCloudFiles() (RejectFunc, error) {
+	if runtime.GOOS != "windows" {
+		return nil, errors.Fatalf("exclude-cloud-files is only supported on Windows")
+	}
+
+	const (
+		FILE_ATTRIBUTE_UNPINNED              = 0x00100000
+		FILE_ATTRIBUTE_RECALL_ON_DATA_ACCESS = 0x00400000
```
Comment (m-wild) [inline cmd/restic/exclude.go:398]: Unfortunately these are [not defined in syscall](https://pkg.go.dev/syscall?GOOS=windows#pkg-constants), probably due to their uncommon usage.

They are documented by Microsoft here [File Attribute Constants (WinNT.h)](https://learn.microsoft.com/en-us/windows/win32/fileio/file-attribute-constants).

**Comment by m-wild** [comment]
@MichaelEischer I'm not really sure how to add tests for this one. It would require either manually setting the file attributes or somehow setting up OneDrive on Windows?

File: cmd/restic/exclude.go (hunk 1 above)
Comment (MichaelEischer) [reply cmd/restic/exclude.go:398]: The constants are available in https://pkg.go.dev/golang.org/x/sys/windows .

File: cmd/restic/cmd_backup.go [hunk 2]
```diff
@@ -348,6 +350,14 @@ func collectRejectFuncs(opts BackupOptions, targets []string) (fs []RejectFunc,
 		fs = append(fs, f)
 	}
 
+	if opts.ExcludeCloudFiles && !opts.Stdin {
```
Comment (MichaelEischer) [inline cmd/restic/cmd_backup.go:353]: Let's move the windows check here. That simplifies the error handling.

File: cmd/restic/exclude.go [hunk 3]
```diff
@@ -385,6 +387,33 @@ func rejectBySize(maxSizeStr string) (RejectFunc, error) {
...
+	)
+
+	return func(item string, fi os.FileInfo) bool {
+		attrs, ok := fi.Sys().(*syscall.Win32FileAttributeData)
```
Comment (MichaelEischer) [inline cmd/restic/exclude.go:402]: Please move the fs specific code into the `internal/fs` package (maybe `internal/fs/file_windows.go`) and add a minimal unit test there. I'd like to minimize new code in `cmd/restic` as much as reasonable.

**Review by MichaelEischer — CHANGES_REQUESTED** [review]

**Comment by deajan** [comment]
@m-wild I really love that PR. That's exactly what I'm searching for more than a year at #4155 
I'll happily make some tests with some beta builds if needed.

**Comment by greatroar** [comment]
There's already an option --one-file-system. Can this feature use that option, instead of introducing a new one? Or does it already have a meaning on Windows?

**Comment by MichaelEischer** [comment]
> There's already an option --one-file-system. Can this feature use that option, instead of introducing a new one? Or does it already have a meaning on Windows?

`--one-file-system` currently has no effect on Windows. However, Windows does support junctions which can be used to mount other filesystems within a filesystem. My expectation would be that `--one-file-system` once it has an effect, addresses exactly this scenario.

Cloud files feel somewhat different: they are placeholders for files that can basically show up everywhere in the filesystem. I wouldn't really expect that `--one-file-system` excludes those files.

File: cmd/restic/exclude.go (hunk 3 above)
Comment (MichaelEischer) [reply cmd/restic/exclude.go:402]: The unit test will probably have to use a bit of mocking to create an os.FileInfo that pretends to be a cloud file, but shouldn't be too complex to implement.

**Comment by deajan** [comment]
@m-wild Any news on this one perhaps ?

**Comment by MichaelEischer** [comment]
If someone is interested in taking over this PR, please just create a new PR, then I'll close this one.

**Comment by deajan** [comment]
@m-wild @MichaelEischer I'll happily sponsor whoever wants to pick this up ;)

**Comment by deajan** [comment]
@m-wild Do you still want to work on this ?

**Comment by m-wild** [comment]
> @m-wild Do you still want to work on this ?

Planning to pick it up over the Xmas break

File: cmd/restic/exclude.go (hunk 3 above)
Comment (m-wild) [reply cmd/restic/exclude.go]: I've given this a go, but I'm not 100% sure it's right, I've never done multi-targeting with go before.

I believe I had to create a stub implementation in `internal/fs/file_unix.go`, then the real implementation in `internal/fs/file_windows.go`.

I've added 3 tests
1. Test with a real temp file that the function doesn't err
2. Mock cloud file
3. Mock regular file

**Comment by m-wild** [comment]
Ho ho ho, it's a Christmas miracle, a PR ready to review.

**Comment by deajan** [comment]
> Ho ho ho, it's a Christmas miracle, a PR ready to review.

Ho ho ho, ping me whenever this is merged so I can sponsor you a bit ;)

**Comment by m-wild** [comment]
Have just fixed the lint issues.

File: internal/fs/file_windows.go [hunk 4]
```diff
@@ -134,3 +136,20 @@ func openHandleForEA(nodeType restic.NodeType, path string, writeAccess bool) (h
 	}
 	return handle, err
 }
+
+// RecallOnDataAccess checks if a file is available locally on the disk or if the file is
+// just a placeholder which must be downloaded from a remote server. This is typically used
+// in cloud syncing services (e.g. OneDrive) to prevent downloading files from cloud storage
+// until they are accessed.
+func RecallOnDataAccess(fi *ExtendedFileInfo) (bool, error) {
```
Comment (MichaelEischer) [inline internal/fs/file_windows.go:144]: Please move that function to the `stat_*.go` files and change its signature to `func (fi *ExtendedFileInfo) RecallOnDataAccess() (bool, error)`.

File: internal/fs/file_windows_test.go [hunk 5]
```diff
@@ -33,3 +38,72 @@ func TestTempFile(t *testing.T) {
 	_, err = os.Stat(fn2)
 	rtest.Assert(t, errors.Is(err, os.ErrNotExist), "err %s", err)
 }
+
+func TestRecallOnDataAccessRealFile(t *testing.T) {
+	// create a temp file for testing
+	tempdir := rtest.TempDir(t)
+	filename := filepath.Join(tempdir, "regular-file")
+	err := os.WriteFile(filename, []byte("foobar"), 0640)
+	if err != nil {
```
Comment (MichaelEischer) [inline internal/fs/file_windows_test.go:47]: Please use `rtest.OK(err)` here

File: changelog/unreleased/issue-3697 [hunk 6]
```diff
@@ -0,0 +1,11 @@
...
+
+Restic treated OneDrive Files On-Demand as though they were regular files
+for the purpose of backup which caused issues with VSS, could make backup
+incredibly slow (as OneDrive attempted to download files), or could fill
+the source disk (e.g. 1TB of files in OneDrive on a 500GB disk).
+Restic now allows the user to exclude these files when backing up with
+the `--exclude-cloud-files` switch.
+
+https://github.com/restic/restic/issues/3697
+https://github.com/restic/restic/issues/4935
```
Comment (MichaelEischer) [inline changelog/unreleased/issue-3697:11]: Add a link to this PR here

**Review by MichaelEischer — CHANGES_REQUESTED** [review]
Thanks for updating the PR! I'm mostly happy with it except for a few nits.

File: internal/fs/file_windows.go (hunk 4 above)
Comment (MichaelEischer) [reply internal/fs/file_windows.go:144]: (This will require duplicating the RecallOnDataAccess placeholder for both `stat_unix` and `stat_bsd`)

**Review by MichaelEischer — APPROVED** [review]
LGTM.

**Comment by MichaelEischer** [comment]
(Force pushed to fix the linter warning)

**Comment by deajan** [comment]
Can confirm that the  new option `--exclude-cloud-files` works great with a test nextcloud setup using current restic beta binary.
Thank you for that great work.

@m-wild As I suggested earlier, I'd like to sponsor you a bit. Do you have any donation system setup perhaps ?

**Comment by m-wild** [comment]
@deajan thanks for testing the beta :) I have GitHub sponsorship enabled.

**Comment by deajan** [comment]
@m-wild Done ;) Thank you again.
