### PR TITLE
cmd, restic: Refactor and fix snapshot filtering

### LINKED ISSUE #4211: restic dump latest has a bug with the arguments
Sorry for not following the process. 

```
restic version                                                                             
restic 0.15.1 compiled with go1.19.5 on darwin/amd64
```

Arguments in `restic dump` subcommand are mixed:
```
restic -r "..." dump --quiet latest --host "host-0" --path /export.dat /export.dat
enter password for repository: 
Fatal: failed to find snapshot: snapshot filter (Paths:[host-0] Tags:[] Hosts:[/export.dat]): no snapshot found
```

[Method definition](https://github.com/restic/restic/blob/f137be42fea928d6682445304e9c15fe4754850e/internal/restic/snapshot_find.go#L89):

```
func FindFilteredSnapshot(ctx context.Context, be Lister, loader LoaderUnpacked, hosts []string, tags []TagList, paths []string, timeStampLimit *time.Time, snapshotID string) (*Snapshot, error)
```

[Actual use](https://github.com/restic/restic/blob/f137be42fea928d6682445304e9c15fe4754850e/cmd/restic/cmd_dump.go#L142):

```
sn, err := restic.FindFilteredSnapshot(ctx, repo.Backend(), repo, opts.Paths, opts.Tags, opts.Hosts, nil, snapshotIDString)
```

### PR DESCRIPTION
**Pull request by greatroar**
What does this PR change? What problem does it solve?
-----------------------------------------------------

This turns snapshotFilterOptions from cmd into a restic.SnapshotFilter type and makes restic.FindFilteredSnapshot and FindFilteredSnapshots methods on that type. This fixes #4211 by ensuring that hosts and paths are named struct fields instead of unnamed function arguments in long lists of such.

Timestamp limits are also included in the new type. To avoid too much pointer handling, the convention is that time zero means no limit. That's January 1st, year 1, 00:00 UTC, which is so unlikely a date that we can sacrifice it for simpler code.

Was the change previously discussed in an issue or on the forum?
----------------------------------------------------------------

Fixes #4211.

Checklist
---------

- [x] I have read the [contribution guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches).
- [x] I have [enabled maintainer edits](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [ ] I have added tests for all code changes.
- [ ] I have added documentation for relevant changes (in the manual).
- [ ] There's a new file in `changelog/unreleased/` that describes the changes for our users (see [template](https://github.com/restic/restic/blob/master/changelog/TEMPLATE)).
- [x] I have run `gofmt` on the code in all commits.
- [x] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits).
- [x] I'm done! This pull request is ready for review.

### CODE REVIEW

File: internal/restic/snapshot_find.go [hunk 1]
```diff
@@ -12,13 +12,32 @@ import (
 // ErrNoSnapshotFound is returned when no snapshot for the given criteria could be found.
 var ErrNoSnapshotFound = errors.New("no snapshot found")
 
-// findLatestSnapshot finds latest snapshot with optional target/directory, tags, hostname, and timestamp filters.
-func findLatestSnapshot(ctx context.Context, be Lister, loader LoaderUnpacked, hosts []string,
-	tags []TagList, paths []string, timeStampLimit *time.Time) (*Snapshot, error) {
+// A SnapshotFilter denotes a set of snapshots based on hosts, tags and paths.
+type SnapshotFilter struct {
```
Comment (MichaelEischer) [inline internal/restic/snapshot_find.go:16]: (Just a question, not a request to change the code) I'm curious why `FindLatest` and `FindAll` are methods of `SnapshotFilter` instead of passing a `SnapshotFilter` option struct to those methods. That is what is the benefit compared to a signature like `func FindLatest(ctx context.Context, be Lister, loader LoaderUnpacked, snapshotID string, opts *SnapshotFilter) (*Snapshot, error)`?

**Review by MichaelEischer — APPROVED** [review]
Please add a small changelog to describe the fixed bug. Besides that LGTM. And thanks a lot for fixing the issue!

File: internal/restic/snapshot_find.go (hunk 1 above)
Comment (greatroar) [reply internal/restic/snapshot_find.go:16]: Mainly because FindLatest and FindAll are too general as names for snapshot finding functions in package restic, but I found the old names too long and not descriptive enough. In other words, the type is used as a namespacing device.

**Comment by greatroar** [comment]
Added the changelog entry.

File: internal/restic/snapshot_find.go (hunk 1 above)
Comment (MichaelEischer) [reply internal/restic/snapshot_find.go:16]: Thanks for the explanation.
