### PR TITLE
do not require gs bucket permissions to init repository

### LINKED ISSUE #3100: error on init repo for google cloud storage on restic 11 but works in restic 10
restic version
--------------------------
restic 0.11.0 compiled with go1.15.3 on linux/amd64                                                      

How did you run restic exactly?
-------------------------------

`restic -r gs:bucket/folder init`

Expected behavior
-----------------

repo is initialized on restic 11.0 and 10.0

Actual behavior
---------------

Fatal: create repository at gs:bucket:/folder failed: service.Buckets.Get: googleapi: Error 403: xyz@cloud-id.iam.gserviceaccount.com does not have storage.buckets.get access to the Google Cloud Storage bucket., forbidden 

but on 10.0 it works

### PR DESCRIPTION
**Pull request by eleith**
What does this PR change? What problem does it solve?
-----------------------------------------------------

a gs service account may only have object permissions on an existing
bucket but no bucket create/get permissions.

these service accounts currently are blocked from initializing a
restic repository because restic can not determine if the bucket exists.

this PR updates the logic to assume the bucket exists when the bucket
attribute request results in a permissions denied error.

this way, restic can still initialize a repository if the service
account does have object permissions

Was the change discussed in an issue or in the forum before?
------------------------------------------------------------

fixes: https://github.com/restic/restic/issues/3100

Checklist
---------

- [x] I have read the [Contribution Guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches)
- [x] I have enabled [maintainer edits for this PR](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)
- [x] There's a new file in `changelog/unreleased/` that describes the changes for our users (template [here](https://github.com/restic/restic/blob/master/changelog/TEMPLATE))
- [x] I have run `gofmt` on the code in all commits
- [x] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits)
- [x] I'm done, this Pull Request is ready for review

### CODE REVIEW

**Comment by eleith** [comment]
can i get some direction on how to add tests for this specific backend logic?

in my quick review of the backend tests, they seem to be a generic test suite meant to test all backends, but this PR adds specific logic for one backend, and it's unclear to me how to add unit tests for this.

cc @fd0 / @MichaelEischer

**Comment by fd0** [comment]
Thanks for giving this a try! I don't think we can even add such a test. The backend tests for Google Cloud Storage run with a service account provided by a sponsor, I don't have an easy way to create a service account necessary to produce the error.

So we'll just go without.

File: internal/backend/gs/gs.go [hunk 1]
```diff
@@ -136,7 +136,14 @@ func Create(cfg Config, rt http.RoundTripper) (restic.Backend, error) {
 	ctx := context.Background()
 	exists, err := be.bucketExists(ctx, be.bucket)
 	if err != nil {
-		return nil, errors.Wrap(err, "service.Buckets.Get")
+		switch err.(type) {
```
Comment (fd0) [inline internal/backend/gs/gs.go:139]: You almost got it! You could use a check similar to the following, this checks the type as well as the status code:

https://github.com/googleapis/google-cloud-go/blob/91b992b32bb3488a927338e7fd3203d9b43036eb/storage/bucket.go#L168-L170

Comment (eleith) [reply internal/backend/gs/gs.go]: doh. forgot the status check. done.

**Review by fd0 — APPROVED** [review]
LGTM, t hanks!
