### PR TITLE
internal/restic: Return summary from BlobSet.String

### LINKED ISSUE #4449: prune: `Data seems to be missing`-Error is too verbose
Output of `restic version`
restic 0.15.2 compiled with go1.20.4 on linux/amd64

How did you run restic exactly?

The command was

restic -r /backup2/restic  "forget" "--prune" "--keep-daily=7" "--keep-weekly=4" "--keep-monthly=12" "--keep-yearly=10"

It is running as part of a small backup automation program I wrote.

The error is so big it overflows my log, so I can only say that it includes a lot of:

 <tree/6fb71510> <data/6fb71826> <data/6fb71f64> <data/6fb7203b> <data/6fb7281a> <data/6fb729e9> <data/6fb72f2a> <data/6fb73415> <data/6fb73a12> <data/6fb73bd9> <data/6fb740f9> <data/6fb74459> <data/6fb74780> <data/6fb75303> <data/6fb75719> <data/6fb75abb> <data/6fb76213> <tree/6fb76388> <data/6fb76400> <data/6fb7647c> <data/6fb76572> <tree/6fb76bf6> <data/6fb76d1b> <tree/6fb76ed7> <data/6fb771b2> <data/6fb77b04> <data/6fb78396> <data/6fb790c5> <tree/6fb79583> <data/6fb795cc> <data/6fb7963f> <data/6fb798e3> <tree/6fb79e9f> <data/6fb7a2fa> <data/6fb7a4c5> <tree/6fb7a75b> <data/6fb7a809> <data/6fb7b0e5> <tree/6fb7b394> ....

Aug 16 08:54:29 desktop kern.info ./backupd[24509]: forget /backup2/restic: Integrity check failed: Data seems to be missing.
Aug 16 08:54:29 desktop kern.info ./backupd[24509]: forget /backup2/restic: Will not start prune to prevent (additional) data loss!
Aug 16 08:54:29 desktop kern.info ./backupd[24509]: forget /backup2/restic: Please report this error (along with the output of the 'prune' run) at
Aug 16 08:54:29 desktop kern.info ./backupd[24509]: forget /backup2/restic: https://github.com/restic/restic/issues/new/choose
Aug 16 08:54:29 desktop kern.info ./backupd[24509]: forget /backup2/restic: Fatal: index is not complete

Running the command again produces no errors. Running

ras-mc-ctl  --summary

reports no disk or ECC errors. Just before forget the backup program also ran:

restic check --read-data -r /backup2/restic

and that reported no errors.

I suspect a bug in restic's forget command, but it is hard to say with the start of the log truncated. For this reason I am reporting this bug only on the size of the error message.

### PR DESCRIPTION
**Pull request by greatroar**
What does this PR change? What problem does it solve?
-----------------------------------------------------

Makes BlobSet.String return a summary when the number of blobs in the set is large (defined as >10).

Was the change previously discussed in an issue or on the forum?
----------------------------------------------------------------

Fixes #4449.

Checklist
---------

- [x] I have read the [contribution guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches).
- [x] I have [enabled maintainer edits](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [x] I have added tests for all code changes.
- [ ] I have added documentation for relevant changes (in the manual).
- [ ] There's a new file in `changelog/unreleased/` that describes the changes for our users (see [template](https://github.com/restic/restic/blob/master/changelog/TEMPLATE)).
- [x] I have run `gofmt` on the code in all commits.
- [x] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits).
- [x] I'm done! This pull request is ready for review.

### CODE REVIEW

**Comment by espindola** [comment]
Thanks, I have built from this branch and I am testing it.

File: internal/restic/blob_set.go [hunk 1]
```diff
@@ -103,11 +107,27 @@ func (s BlobSet) List() BlobHandles {
...
 func (s BlobSet) String() string {
-	str := s.List().String()
-	if len(str) < 2 {
-		return "{}"
+	const maxelems = 10
+
+	sb := new(strings.Builder)
+	sb.WriteByte('{')
+	n := 0
+	for k := range s {
```
Comment (espindola) [inline internal/restic/blob_set.go:119]: This order is not stable, right? Maybe we should iterate over List()?

Comment (MichaelEischer) [reply internal/restic/blob_set.go:119]: I don't think it's necessary to sort the blobs. Sorting the blobs even causes the problem that the formatted string would include a non representative subset of ids. For example it might only include ids that start with `0` and hide that blobs with other prefixes are missing.

**Review by MichaelEischer — APPROVED** [review]
LGTM. Thanks!
