### PR TITLE
Fix windows terminal output for mintty

### LINKED ISSUE #3111: Log file on Windows contains progress status text, escape characters and extra line breaks
Hello,

The log file on Windows contains progress status text, escape characters and extra line breaks. 
This does not happen on Linux. (https://forum.restic.net/t/different-log-file-in-windows-and-linux/3273)

Please fix, thanks!

Output of `restic version`
--------------------------

Windows
`restic 0.11.0 compiled with go1.15.3 on windows/amd64`
Linux
`restic 0.11.0 compiled with go1.15.3 on linux/amd64`

How did you run restic exactly?
-------------------------------

Windows
`restic backup --repo C:\Backup C:\Users --cleanup-cache --verbose --verbose >> C:\restic.log 2>&1`
Linux
`restic backup --repo /backup /source --cleanup-cache --verbose --verbose >> /restic.log 2>&1`

Expected behavior
-----------------

log files are the same on Windows and Linux

Linux

```
open repository
lock repository
load index files
using parent snapshot 5f9668c4
start scan on [/source]
start backup on [/source]
new       /source/file.txt, saved in 0.044s (100 B added)
unchanged /source/file.jpg
...
```

Actual behavior
---------------

Windows

```
open repository

e[2Klock repository

e[2Kload index files

e[2Kusing parent snapshot cf8362f4

e[2Kstart scan on [C:\Users]

e[2Kstart backup on [C:\Users]

e[2K[0:00] 0 files, 0 B, 0 errors

e[2Kunchanged /C/Users/MyUser/Config.xml

e[2K[0:00] 0 files, 0 B, 0 errors

e[2Kunchanged /C/Users/MyUser/test.html
...
```

(e[ = Escape character)

Do you have an idea how to solve the issue?
-------------------------------------------

This did not happen in older versions <= 0.9.5

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

I'm happy that Restic also works on Windows

### PR DESCRIPTION
**Pull request by MichaelEischer**
What does this PR change? What problem does it solve?
-----------------------------------------------------
Redirecting the output of restic to a file when using powershell currently results in terminal control characters being printed.

restic tries to detect whether mintty is used on windows and switches to posix terminal control characters. This check was done by testing whether stdout is a pipe. However, the latter is also the case when piping the output of restic between commands or on powershell when redirecting the output to a file. This PR makes the mintty terminal detection more robust by checking the filename of the connected pipe which must match `\\(cygwin-|msys-).+-pty.+-master`. This avoids false positives and ensures that piping the output to another command also works as expected.

In addition the interactive terminal output on mintty is repaired: Since #3199 restic only shows progress output for the backup command and all others on regular terminals, which does not include the mintty special case. This is fixed by introducing `stdoutCanUpdateStatus` which uses the same logic also used for the terminal type detection by the backup command. `stdoutIsTerminal` is extended to also return true for mintty terminals.

Was the change discussed in an issue or in the forum before?
------------------------------------------------------------
fixes #3111
Alternative to #3301

Checklist
---------

- [x] I have read the [Contribution Guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches)
- [x] I have enabled [maintainer edits for this PR](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)
- [ ] I have added tests for all changes in this PR
- ~~[ ] I have added documentation for the changes (in the manual)~~
- [x] There's a new file in `changelog/unreleased/` that describes the changes for our users (template [here](https://github.com/restic/restic/blob/master/changelog/TEMPLATE))
- [x] I have run `gofmt` on the code in all commits
- [x] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits)
- [x] I'm done, this Pull Request is ready for review

### CODE REVIEW

**Comment by kmwoley** [comment]
@MichaelEischer I gave this a quick test. It doesn't solve the Windows issues. Here's my output from PowerShell.

On PowerShell, when not piped things look okay:
```
PS C:\restic> C:\resticcode\MichaelEischer\restic.exe backup -r repo C:\Users\Kevin\Documents\
repository bde54756 opened successfully, password is correct
created new cache in C:\Users\Kevin\AppData\Local\restic
no parent snapshot found, will read all files

Files:       12119 new,     0 changed,     0 unmodified
Dirs:         1087 new,     0 changed,     0 unmodified

processed 12119 files, 2.378 GiB in 2:30
snapshot 3baea7f4 saved
```

When piped, the escape characters are produced:
```
PS C:\restic> C:\resticcode\MichaelEischer\restic.exe backup -r repo C:\Users\Kevin\Documents\ | Tee-Object test.log

using parent snapshot 3baea7f4







Files:           0 new,     0 changed, 12119 unmodified



Dirs:            0 new,     5 changed,  1082 unmodified



Added to the repo: 52.905 KiB







processed 12119 files, 2.378 GiB in 0:02



snapshot 4b5f9a47 saved





PS C:\restic>
```

The contents of `test.log` show the escape characters:
image

**Comment by kmwoley** [comment]
BTW, the reason this doesn't fix #3111 is because you haven't updated `moveCursorUp` and `clearCurrentLine` for the case where it's a Window's environment with piped output. 

From #3301 - 
```
// isWindowsTerminal return true if the file descriptor is a windows terminal (cmd, psh, mintty).
func isWindowsTerminal(fd uintptr) bool {
	// IsTerminal does not return true if the output is piped to a file or other command
	return terminal.IsTerminal(int(fd))
}
```

If the output is piped, `isWindowsTerminal` returns false in all 3 shells (cmd, psh, mintty).

**Comment by MichaelEischer** [comment]
> BTW, the reason this doesn't fix #3111 is because you haven't updated `moveCursorUp` and `clearCurrentLine` for the case where it's a Window's environment with piped output.

Are you sure you've tested the correct branch? I cannot reproduce the problem with your example command line.

Only iff `CanUpdateStatus` returns true, then restic calls `moveCursorUp` and `clearCurrentLine`. In case of piped output in PowerShell `CanUpdateStatus` should now return false and thus restic no longer prints any posix escape characters. In that case it doesn't matter how `moveCursorUp` and `clearCurrentLine` are implemented as these functions are not called.

https://github.com/restic/restic/blob/c9b4fadd91d9e794e0294c234c99bff0cb50a69e/internal/ui/termstatus/status.go#L70-L76

> Have you tested my PR to see if it works in all your cases?

I've tested it and in respect to not mangling the log file output it works. However, the interactive output of restic on mintty doesn't work for me.

For me mintty does by default not use the modern conpty feature of windows 10. Apparently it was disabled again by default in the latest msys-/cygwin-Release: https://github.com/msys2/msys2-runtime/commit/69451787ebe62d81ea4a848a548e2b87e0211ae3 . So for now it's probably better to keep the explicit mintty support and remove it at some later point.

File: internal/ui/termstatus/terminal_windows.go [hunk 1]
```diff
@@ -80,19 +81,47 @@ func isPipe(fd uintptr) bool {
...
+		return false
+	}
+
+	// inspired by https://github.com/RyanGlScott/mintty/blob/master/src/System/Console/MinTTY/Win32.hsc
+	// terminal: \msys-dd50a72ab4668b33-pty0-to-master
+	// pipe to cat: \msys-dd50a72ab4668b33-13244-pipe-0x16
+	if (strings.HasPrefix(fn, "\\cygwin-") || strings.HasPrefix(fn, "\\msys-")) &&
+		strings.Contains(fn, "-pty") && strings.HasSuffix(fn, "-master") {
+		return true
+	}
```
Comment (greatroar) [inline internal/ui/termstatus/terminal_windows.go:124]: Maybe add a unit test that asserts that `CanUpdateStatus("\\msys-dd50a72ab4668b33-pty0-to-master")`?

Comment (MichaelEischer) [reply internal/ui/termstatus/terminal_windows.go:124]: I've added a basic test.

**Comment by kmwoley** [comment]
@MichaelEischer - you can ignore my previous testing results; it was user error.
I've retested this latest branch with `cmd`, `psh`, and the Git Bash (`mintty`) that comes with Git for Windows.
Both piped and unpiped output works correctly in all 3 shells I tested.
Sorry for the hassle/confusion there!

**Review by fd0 — APPROVED** [review]
LGTM! thanks for taking the time to debug this!
