### PR TITLE
ls: Print names with percent correctly

### LINKED ISSUE #1017: restic ls shows MISSING files
## Output of `restic version`
restic 0.6.1
compiled with go1.8.3 on linux/amd64

## How did you start restic exactly? (Include the complete command line)
restic -r /mnt/media/restictest ls latest | grep MISSING

## What backend/server/service did you use?
local

## Expected behavior
the output from ls should match what is on the filesystem, excluding excludes

## Actual behavior
weirdly named files e.g. `./.config/gconf/desktop/gnome/interface/%!g(MISSING)conf.xml`

## Steps to reproduce the behavior
```
$ restic -r /mnt/media/restictest ls latest | grep MISSING
./.config/gconf/apps/%!g(MISSING)conf.xml
./.config/gconf/apps/GnomeBaker/%!g(MISSING)conf.xml
./.config/gconf/apps/GnomeBaker/Devices/%!g(MISSING)conf.xml
```
So `./.config/gconf/apps/GnomeBaker/%gconf.xml` becomes `./.config/gconf/apps/GnomeBaker/%!g(MISSING)conf.xml`

## Do you have any idea what may have caused this?
Maybe restic is mishandling the `%` character.

### PR DESCRIPTION
**Pull request by fd0**
Closes #1017

### CODE REVIEW

File: src/cmds/restic/cmd_ls.go [hunk 1]
```diff
@@ -52,7 +52,7 @@ func printTree(repo *repository.Repository, id *restic.ID, prefix string) error
 	}
 
 	for _, entry := range tree.Nodes {
-		Printf(formatNode(prefix, entry, lsOptions.ListLong) + "\n")
+		Printf("%s\n", formatNode(prefix, entry, lsOptions.ListLong))
```
Comment (middelink) [inline src/cmds/restic/cmd_ls.go]: Wow, I cannot believe not one of the lint, vet or other obnoxious tools let that slip. Using format strings with user supplied strings is bad.... (and yes, pointing finger at self here...)

Comment (fd0) [inline src/cmds/restic/cmd_ls.go]: Happens to the best :)
