### PR TITLE
Don't require `self-update --output` placeholder file

### LINKED ISSUE #2491: "self-update --output" fails to create a new file on Windows
Output of `restic version`
--------------------------
restic 0.9.6 compiled with go1.13.4 on windows/amd64

How did you run restic exactly? (/Actual behavior/Steps to reproduce the behavior)
-------------------------------
Got the following error when running restic self-update:
```
$ restic self-update --output restic-new.exe
CreateFile restic-new.exe: The system cannot find the file specified.
```

If I create an empty file named `restic-new.exe` on the current directory, the command runs successfully:

```
$ touch restic-new.exe

$ restic self-update --output restic-new.exe
writing restic to restic-new.exe
find latest release of restic at GitHub
restic is up to date
```

I was able to update from 0.9.4 by creating such empty file.

Expected behavior
-----------------
Restic should check for new version even when the output file doesn't exist.

Related Issues
---------------
On #2248 (self-update doesn't work on Windows), the suggested workaround is to use "--output". 

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
It's the best backup solution I could find!

### PR DESCRIPTION
**Pull request by andreaso**
What does this PR change? What problem does it solve?
-----------------------------------------------------

This removes the requirement on `restic self-update --output` to point
to a path of an existing file, to overwrite. In case the specified
path does exist we still want to verify that it's a regular file,
rather than a directory or a device, which gets overwritten.

We also want to verify that a path to a new file exists within an
existing directory. The alternative being running into that issue
after the actual download, etc has completed.

Was the change discussed in an issue or in the forum before?
------------------------------------------------------------

Resolves #2491

Checklist
---------

- [x] I have read the [Contribution Guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches)
- [x] I have enabled [maintainer edits for this PR](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)
- [ ] I have added tests for all changes in this PR
- [ ] I have added documentation for the changes (in the manual)
- [x] There's a new file in `changelog/unreleased/` that describes the changes for our users (template [here](https://github.com/restic/restic/blob/master/changelog/TEMPLATE))
- [x] I have run `gofmt` on the code in all commits
- [x] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits)
- [x] I'm done, this Pull Request is ready for review

### CODE REVIEW

File: cmd/restic/cmd_self_update.go [hunk 1]
```diff
@@ -56,11 +57,18 @@ func runSelfUpdate(opts SelfUpdateOptions, gopts GlobalOptions, args []string) e
...
-
-	if !fi.Mode().IsRegular() {
-		return errors.Errorf("output file %v is not a normal file, use --output to specify a different file", opts.Output)
+		dirname := filepath.Dir(opts.Output)
+		di, err := os.Lstat(dirname)
+		if err != nil {
+			return err
+		}
+		if !di.Mode().IsDir() {
+			return errors.Errorf("output parent path %v is not a directory, use --output to specify a different file path", dirname)
```
Comment (MichaelEischer) [inline cmd/restic/cmd_self_update.go:66]: Please use `errors.Fatalf` to create the error, otherwise the error looks like restic just exploded ;-)

**Review by MichaelEischer — DISMISSED** [review]
The implementation works for me, only the error reporting needs a small change.

File: cmd/restic/cmd_self_update.go (hunk 1 above)
Comment (andreaso) [reply cmd/restic/cmd_self_update.go:66]: What about the fact that the corresponding error message I'm replacing uses `errors.Errorf`?

Comment (MichaelEischer) [reply cmd/restic/cmd_self_update.go:66]: An error message should not look like this:
```
output path tmp is not a normal file, use --output to specify a different file path
main.runSelfUpdate
	restic/restic/cmd/restic/cmd_self_update.go:70
main.glob..func23
	restic/restic/cmd/restic/cmd_self_update.go:30
github.com/spf13/cobra.(*Command).execute
	go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842
github.com/spf13/cobra.(*Command).ExecuteC
	go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950
github.com/spf13/cobra.(*Command).Execute
	go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main
	restic/restic/cmd/restic/main.go:86
runtime.main
	go/1.15.2/libexec/src/runtime/proc.go:204
runtime.goexit
	go/1.15.2/libexec/src/runtime/asm_amd64.s:1374
```
The following is much nicer:
`Fatal: output path tmp is not a normal file, use --output to specify a different file path`
So the current behavior needs fixing. If you take a look at line 78, there `errors.Fatalf` is already used.

Comment (andreaso) [reply cmd/restic/cmd_self_update.go]: Ack.

I have now (force) pushed a new commit, replacing `errors.Errorf` with `errors.Fatalf`.

**Review by fd0 — APPROVED** [review]
Awesome, thanks!

File: changelog/unreleased/issue-2491 [hunk 2]
```diff
@@ -0,0 +1,9 @@
+Bugfix: Don't require `self-update --output` placeholder file
+
+`restic self-update --output /path/to/new-restic` used to require that
+_new-restic_ was an existing file, to be overwritten. Now it's
```
Comment (rawtaz) [inline changelog/unreleased/issue-2491:4]: Please remove the _ around new-restic as the changelog isn't Markdown. It's perfectly fine to put commands in some kind of delimiter though, so we don't need to change that.

**Review by MichaelEischer — COMMENTED** [review]
I'm fine with the code changes. Please adjust the changelog, then this PR is ready for merging.

File: changelog/unreleased/issue-2491 (hunk 2 above)
Comment (andreaso) [reply changelog/unreleased/issue-2491]: Done.

**Review by rawtaz — APPROVED** [review]
Awesome, thanks for the fix!
