### PR TITLE
Minimal set of patches to get restic working on Solaris

### LINKED ISSUE #1576: support for Illumos/Solaris
## Output of `restic version`

I was trying to build latest stable release, 0.8.1.

## How did you run restic exactly?

I didn't run it, I was only trying to build it.

## What backend/server/service did you use to store the repository?

macOS, build was done with reproducible builder via docker image.

## Expected behavior

I would love to see restic building properly on Illumos/Solaris OS.

## Actual behavior

It fails with the following error messages:

```
docker run --rm --volume $PWD:/home/build restic/builder v0.8.1.tar.gz
Go version is go version go1.9.2 linux/amd64
path is /tmp/restic-release-JzlHL4
version is 0.8.1
outputdir is /home/build/restic-0.8.1-20180124-104215
restic_0.8.1_solaris_amd64
# github.com/restic/restic/vendor/bazil.org/fuse
github.com/restic/restic/vendor/bazil.org/fuse/error_std.go:27:20: undefined: errNoXattr
github.com/restic/restic/vendor/bazil.org/fuse/fuse.go:1345:26: undefined: attr
github.com/restic/restic/vendor/bazil.org/fuse/fuse_kernel.go:166:28: undefined: syscall.O_DIRECTORY
github.com/restic/restic/vendor/bazil.org/fuse/fuse_kernel.go:404:17: undefined: attr
# github.com/restic/restic/internal/restic
github.com/restic/restic/internal/restic/node.go:231:14: node.restoreSymlinkTimestamps undefined (type Node has no field or method restoreSymlinkTimestamps)
github.com/restic/restic/internal/restic/node_unix.go:21:18: cannot use statUnix(*s) (type statUnix) as type statT in return argument:
        statUnix does not implement statT (missing atim method)
github.com/restic/restic/internal/restic/node_xattr.go:16:10: undefined: xattr.Get
github.com/restic/restic/internal/restic/node_xattr.go:26:10: undefined: xattr.List
github.com/restic/restic/internal/restic/node_xattr.go:35:7: undefined: xattr.Set
build failed: exit status 2
exit status 1
```

## Steps to reproduce the behavior

Try to build restic for solaris/amd64 platform via https://github.com/restic/builder

## Do you have any idea what may have caused this?

Likely lack of support for Solaris platform.

## Do you have an idea how to solve the issue?

No, but I would hope having OpenBSD and FreeBSD support in place already, that it won't prove super difficult to include one more. Especially knowing that rest-server does support it.

## Did restic help you or made you happy in any way?

I honestly think it's the best backup solution out there and I would love to have it running on my SmartOS machines.

### PR DESCRIPTION
**Pull request by jasperla**
This effectively disables the xattr/fuse support. Also the sftp backend is disabled due to lack of `syscall.SYS_IOCTL` support in Go for Solaris.

### What is the purpose of this change? What does it change?

Allow restic to be built on the golang 'solaris' target. It was built and tested on SmartOS with `go version go1.9.3 solaris/amd64`

### Was the change discussed in an issue or in the forum before?

Closes #1576 

### Checklist

- [x] I have read the [Contribution Guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches)
- [x] ~I have added tests for all changes in this PR~ (not needed?)
- [x] I have added documentation for the changes (in the manual)
- [x] There's a new file in a subdir of `changelog/x.y.z` that describe the changes for our users (template [here](https://github.com/restic/restic/blob/master/changelog/changelog-entry.tmpl))
- [x] I have run `gofmt` on the code in all commits
- [x] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits)
- [x] I'm done, this Pull Request is ready for review

### CODE REVIEW

File: internal/backend/sftp/foreground_solaris.go [hunk 1]
```diff
@@ -0,0 +1,15 @@
+// +build !windows
```
Comment (fawick) [inline internal/backend/sftp/foreground_solaris.go]: `node_solaris.go` below doesn't have this constraint, why is it needed here?

Comment (jasperla) [reply internal/backend/sftp/foreground_solaris.go]: Good point; it's not needed. I've pushed a fixed file.

File: internal/backend/sftp/foreground_solaris.go [hunk 2]
```diff
@@ -0,0 +1,13 @@
...
+import (
+	"os/exec"
+
+	"github.com/restic/restic/internal/errors"
+)
+
+// golang on Solaris lacks SYS_IOCTL. It should be possible to workaround
+// that, however for turn these functions into no-ops.
+func startForeground(cmd *exec.Cmd) (bg func() error, err error) {
+	return nil, errors.New("sftp disabled on Solaris")
```
Comment (fd0) [inline internal/backend/sftp/foreground_solaris.go]: It should be possible to use the sftp backend on solaris just fine, just without the magic that on Linux allows us to query for a password interactively and being able to tear down nicely at the same time.

Something like this should work:
```go
// run the command in its own process group
// so that SIGINT is not sent to it
cmd.SysProcAttr = &syscall.SysProcAttr{
    Setpgid: true,
}

// start the process
err = cmd.Start()
if err != nil {
    return nil, errors.Wrap(err, "cmd.Start")
}

bg = func() error { return nil }
return bg, nil
```

**Review by fd0 — CHANGES_REQUESTED** [review]
Hey, thanks for taking a stab at this!

We need to fix the sftp backend before this can be merged (including the comments in the docs).

What's still missing (apart from sftp) is adding `solaris` to the integration tests, so we see when it breaks:

https://github.com/restic/restic/blob/6edf28d1e187a2f94fbfeef4e91fbe5c893d2f10/run_integration_tests.go#L125

**Review by fd0 — APPROVED** [review]
