### PR TITLE
cmd/mount: honour --no-lock flag

### LINKED ISSUE #1597: mount repository on read-only filesystems with --no-lock fails
## Output of `restic version`
```
restic 0.8.1 (v0.8.1-121-g94ec55f)
compiled with go1.9.2 on linux/amd64
```

## How did you run restic exactly?
```
(/data type ext4 (ro,relatime,errors=remount-ro,data=ordered))
```

```
/usr/local/bin/restic mount --no-cache --no-lock -p /tmp/secret.pw -r /data/somefolder1/somerepo4567 /mnt/somerepo4567

Save(<lock/5e59d1c2e1>) returned error, retrying after 434.695773ms: OpenFile: open /data/somefolder1/somerepo4567/locks/5e59d1c2e168d883167983d8ed6961dcc807be6ef860243abf372049a7f01d21: read-only file system
unable to create lock in backend: OpenFile: open /data/somefolder1/somerepo4567/locks/5e59d1c2e168d883167983d8ed6961dcc807be6ef860243abf372049a7f01d21: read-only file system
unable to umount (maybe already umounted?): exit status 1: fusermount: failed to unmount /mnt/somerepo4567: No such file or directory
```

## What backend/server/service did you use to store the repository?
local/restic

## Expected behavior
Mount repo read-only without trying to access/write/read a lock file inside the read-only repo folder

## Actual behavior
Fails while accessing/writing to lock folder inside the read-only repo folder

## Steps to reproduce the behavior
See above

## Do you have any idea what may have caused this?
Bad implementation of --no-lock arg

## Do you have an idea how to solve the issue?
Don't try to access lock folder inside read-only repository on read-only filesystem when --no-lock is provided

## Did restic help you or made you happy in any way?
Not fully yet

### PR DESCRIPTION
**Pull request by renard**
Do not lock the repository if --no-lock flag is set. This allows to
mount repositories which are archived on a read only system.

Signed-off-by: Sébastien Gross <seb•ɑƬ•chezwam•ɖɵʈ•org>

What is the purpose of this change? What does it change?
--------------------------------------------------------

If remote repository is on a read-only partition no lock can be acquired making the repo un-mountable.

This small patch fixes this by honouring the `--no-lock` global flag.

Was the change discussed in an issue or in the forum before?
------------------------------------------------------------

https://forum.restic.net/t/mount-without-locking/2887

Fixes #1597

Checklist
---------

- [X] I have read the [Contribution Guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches)
- [X] I have enabled [maintainer edits for this PR](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)
- [ ] I have added tests for all changes in this PR
- [ ] I have added documentation for the changes (in the manual)
- [ ] There's a new file in `changelog/unreleased/` that describes the changes for our users (template [here](https://github.com/restic/restic/blob/master/changelog/TEMPLATE))
- [X] I have run `gofmt` on the code in all commits
- [X] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits)
- [X] I'm done, this Pull Request is ready for review

### CODE REVIEW

File: cmd/restic/cmd_mount.go [hunk 1]
```diff
@@ -90,10 +90,13 @@ func mount(opts MountOptions, gopts GlobalOptions, mountpoint string) error {
 		return err
 	}
 
-	lock, err := lockRepo(repo)
-	defer unlockRepo(lock)
-	if err != nil {
-		return err
+	if !gopts.NoLock {
+		Verbosef("create lock for repository\n")
```
Comment (aawsome) [inline cmd/restic/cmd_mount.go:94]: Instead of printing out in info when the repo is locked, I would print out a warning when the repo is *not* locked.

Comment (renard) [reply cmd/restic/cmd_mount.go]: Commit updated. Thanks.

**Review by aawsome — APPROVED** [review]
Looks good to me!

**Comment by greatroar** [comment]
I'm not sure why mount should print a warning when no other command does that, but LGTM too.

**Comment by aawsome** [comment]
> I'm not sure why mount should print a warning when no other command does that, but LGTM too.

I think that that other commands should warn as well. :wink: 
IMO for mount this is even more important as the mount command only quits when the user cancels it - that might be quite a long time. However, not too much to worry as mount is a read-only command.

**Comment by greatroar** [comment]
Fine with me, let's see what the maintainers think.

File: cmd/restic/cmd_mount.go [hunk 2]
```diff
@@ -90,10 +90,14 @@ func mount(opts MountOptions, gopts GlobalOptions, mountpoint string) error {
 		return err
 	}
 
-	lock, err := lockRepo(repo)
-	defer unlockRepo(lock)
-	if err != nil {
-		return err
+	if gopts.NoLock {
+		Warnf("not locking the repository\n")
```
Comment (MichaelEischer) [inline cmd/restic/cmd_mount.go:94]: I don't think there's a need to print this warning. A user hopefully still remembers that they passed the `--no-lock` flag. So let's keep this consistent with the other commands which respect `--no-lock` and remove the warning.

**Review by MichaelEischer — COMMENTED** [review]
This PR would also fix #1597, for some reason Github doesn't let me link this issue to the PR.

**Review by MichaelEischer — COMMENTED** [review]
Please also add a short changelog entry file to this PR. After this and the warning message are fixed, this PR is ready for merging.

File: cmd/restic/cmd_mount.go (hunk 2 above)
Comment (renard) [reply cmd/restic/cmd_mount.go]: @MichaelEischer done in commit a6c94ac.

Let me know if this is good for you.

File: changelog/unreleased/pull-2821 [hunk 3]
```diff
@@ -0,0 +1,6 @@
+cmd/mount: honour --no-lock flag
+
+Do not lock the repository if --no-lock global flag is set. This allows
+to mount repositories which are archived on a read only system.
+
+https://github.com/restic/restic/pull/2821
```
Comment (rawtaz) [inline changelog/unreleased/pull-2821:6]: Please add https://github.com/restic/restic/issues/1597 below this line.

Comment (renard) [reply changelog/unreleased/pull-2821:6]: Done in 02c2ba9.

**Review by rawtaz — CHANGES_REQUESTED** [review]
@renard I guess GitHub is acting up and you haven't seen the two remaining comments I made on the changelog file. Please check the "Files changed" tab to see them :)

File: changelog/unreleased/pull-2821 [hunk 4]
```diff
@@ -0,0 +1,7 @@
+cmd/mount: honour --no-lock flag
+
+Do not lock the repository if --no-lock global flag is set. This allows
+to mount repositories which are archived on a read only system.
```
[the remark this answers is not in the document]
Comment (renard) [reply changelog/unreleased/pull-2821]: Sorry for that.

Updated in c388d10

**Comment by rawtaz** [comment]
The subject in the changelog is still not changed.

**Review by rawtaz — APPROVED** [review]
Thank you very much!

**Comment by ATLief** [comment]
This is a really interesting addition. Would it be possible to modify the repository via another process while it’s mounted with the —no-lock option? If so what would happen?

I’m thinking that this could be useful to continue backup my system while I restore or read a backup of a file, but I also see the potential for this to have unintended side-effects; for example, what would happen if the snapshot where a file was being accessed was forgotten or pruned?

**Comment by aawsome** [comment]
@ATLief as long as you just want to backup while having your repo mounted, there is not need to use the `--no-lock` option: It already works as expected without this option. Mount will even update the directory structure after a short delay and includes the newly added snapshots.
However, I would not recommend using `mount --no-lock` with commands that delete things from the repository. This won't break your repo as `mount` does only read, but may give errors or even may crash.

This option is IMO only interesting for the use case that you can no longer write to your repopository but still want to access it.
