### PR TITLE
Remove existing path before restoring a symlink

### LINKED ISSUE #2578: Restore of a existing symlink(with same content) fails
Output of `restic version`
--------------------------
restic 0.9.6 compiled with go1.13.4 on linux/amd64
restic/restic                            latest              66a76c4e92a6        2 months ago        30.7MB

How did you run restic exactly?
-------------------------------

# First time, not existing:

docker run --rm -ti -e RESTIC_PASSWORD -e RESTIC_REPOSITORY -v restic-cache:/root/.cache/restic -v /srv/docker/restic:/srv/restic -v /srv/docker/clients/$site_id:/srv/app/$site_id:ro -v /srv/docker/clients/$site_id/restores/39e1d807:/srv/app/$site_id/restores/39e1d807:rw restic/restic restore --host $site_id --target /srv/app/$site_id/restores/39e1d807 39e1d807 --include /old/usr/share/zoneinfo/right/Turkey
repository 22780ffb opened successfully, password is correct
restoring <Snapshot 39e1d807 of [/srv/app/$site_id] at 2020-02-13 19:42:52 +0000 UTC by root@$site_id> to /srv/app/$site_id/restores/39e1d807
+ exit 0

# Second time, *immediately following*, exists:
docker run --rm -ti -e RESTIC_PASSWORD -e RESTIC_REPOSITORY -v restic-cache:/root/.cache/restic -v /srv/docker/restic:/srv/restic -v /srv/docker/clients/$site_id:/srv/app/$site_id:ro -v /srv/docker/clients/$site_id/restores/39e1d807:/srv/app/$site_id/restores/39e1d807:rw restic/restic restore --host $site_id --target /srv/app/$site_id/restores/39e1d807 39e1d807 --include /old/usr/share/zoneinfo/right/Turkey
repository 22780ffb opened successfully, password is correct
restoring <Snapshot 39e1d807 of [/srv/app/$site_id] at 2020-02-13 19:42:52 +0000 UTC by root@$site_id> to /srv/app/$site_id/restores/39e1d807
ignoring error for /old/usr/share/zoneinfo/right/Turkey: Symlink: symlink Asia/Istanbul /srv/app/$site_id/restores/39e1d807/old/usr/share/zoneinfo/right/Turkey: file exists
There were 1 errors

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
Local volume-mounted repo, via docker.

Expected behavior
-----------------

All other content files in the repo were restored during the second call, but any symlinks that already existed have errors printed, even if their targets are the same.  And, even if they were *different*, it shouldn't error, unless --verify exists(or some such).

No such error/warning was printed on the already existing regular files, so why does it do so on symlinks?

Actual behavior
---------------

Steps to reproduce the behavior
-------------------------------

Backup a symlink, restore it twice.

Do you have any idea what may have caused this?
-----------------------------------------------

Do you have an idea how to solve the issue?
-------------------------------------------

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

### PR DESCRIPTION
**Pull request by jkmw**
Bugfix: Make sure that symlinks can be created during recovery

When restoring a symlink, restic reported an error if the target path already existed.
With this change, the potentially existing target path is first removed before the symlink is recreated.

https://github.com/restic/restic/issues/2578

What does this PR change? What problem does it solve?
-----------------------------------------------------

At the moment restic overwrites existing data in the restore target, unless it is a symlink, in which case an error is thrown.

From my point of view, restic should behave with symlinks in the same way as with all other file types and "overwrite" already existing paths.

This change causes restic to "overwrite" existing data (by delete and create) even if a symlink is to be restored.

See #2578 for more details.

Was the change previously discussed in an issue or on the forum?
----------------------------------------------------------------

Closes #2578

Checklist
---------

- [ x ] I have [enabled maintainer edits](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [ x ] I'm done! This pull request is ready for review.

### CODE REVIEW

File: internal/restic/node.go [hunk 1]
```diff
@@ -299,8 +299,12 @@ func (node Node) createSymlinkAt(path string) error {
 	if runtime.GOOS == "windows" {
 		return nil
 	}
-	err := fs.Symlink(node.LinkTarget, path)
-	if err != nil {
+
+	if err := os.RemoveAll(path); err != nil && !errors.Is(err, os.ErrNotExist) {
```
Comment (MichaelEischer) [inline internal/restic/node.go:303]: Wouldn't it be sufficient to use `Remove` in most cases? I'm not sure whether someone would expect restic to wipe a directory just to restore a directory in its place?

**Comment by MichaelEischer** [comment]
Also please add a short changelog entry using the template at https://github.com/restic/restic/blob/master/changelog/TEMPLATE

File: internal/restic/node.go (hunk 1 above)
Comment (jkmw) [reply internal/restic/node.go:303]: My intention here was that I would expect to have the exact same state after a restore as I had at the time of the backup. Personally, I would be surprised if I had a symlink and after the restore there is still a directory instead of the sysmlink.
I would also be surprised if restic aborted with an error just because there was a directory in the restore destination that was a symlink at the time of the backup :shrug:.

Comment (MichaelEischer) [reply internal/restic/node.go:303]: I'd prefer to play it safe, return an error in case there is a directory here and let the user sort it out.

**Comment by MichaelEischer** [comment]
I guess I haven't been explicitly enough in my previous comment: replacing `os.RemoveAll` with `os.Remove` was not a suggestion, but rather a request. The other parts of the restorer do not wipe out entire directory trees if these are standing in the way, thus restoring a symlink must behave just the same.

**Review by MichaelEischer — APPROVED** [review]
LGTM. Thanks!
