### PR TITLE
Fix shutdown hang when restic is started as background job

### LINKED ISSUE #2298: Restic mount hangs in the background after mount/unmount
Output of `restic version`
--------------------------
restic 0.9.5 compiled with go1.12.4 on linux/amd64

How did you run restic exactly?
-------------------------------
```
# export RESTIC_PASSWORD=xxx
# restic -r /mnt/backup/restic/root mount /mnt/temp/ &
repository 2fc17b90 opened successfully, password is correct
Now serving the repository at /mnt/temp/
When finished, quit with Ctrl-c or umount the mountpoint.
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

CIFS network mount or local ZFS dataset (both exhibit the issue)

Expected behavior
-----------------

The command mounts the repo at /mnt/temp and at unmount, exits. The repo is fine, no problems accessing snapshots under the mount, etc. Note that the command is run in the background using `&`.

Actual behavior
---------------

When I unmount the repo using `umount /mnt/temp`, it's succesfully unmounted, but restic doesn't quit, it stays as a hung process in the background.

Steps to reproduce the behavior
-------------------------------

See the command issued for mounting.

Do you have any idea what may have caused this?
-----------------------------------------------

Nope.

Do you have an idea how to solve the issue?
-------------------------------------------

Nope.

Did restic help you or made you happy in any way?
-------------------------------------------------

Don't know yet, as I've just started using it for daily workloads.

### PR DESCRIPTION
**Pull request by MichaelEischer**
What is the purpose of this change? What does it change?
--------------------------------------------------------
restic uses a cleanup hook to ensure that it restores the terminal configuration to a sane state, when restic is interrupted while reading a password from the terminal. However, this causes a problem, when restic runs in a background job, as reconfiguring a terminal will cause a `SIGTTOU` to be sent to restic pausing it. Therefore, restic seems to hang on shutdown when it was running in the background.

This commit changes the behavior to only restore the terminal configuration if restic was interrupted while reading a password from the terminal. As reading a password from the terminal requires that restic is in the foreground, this should avoid restic getting stopped.

See #2298 for further details on the problem. The background hang could also be addressed by another solution: `readPasswordTerminal` could temporarily register a cleanup hook and remove it afterwards. That would yield a slightly cleaner implementation, but would require much more extensive changes.

This change will result in a merge conflict with #2593, however, merging shouldn't be too complex as that PR just moves the code lines around which are modified by this PR.

Was the change discussed in an issue or in the forum before?
------------------------------------------------------------
The solution implemented by the PR was not discussed yet.

Closes #2298
Issue introduced in #402

Checklist
---------

- [x] I have read the [Contribution Guidelines](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#providing-patches)
- [x] I have enabled [maintainer edits for this PR](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)
- ~~[ ] I have added tests for all changes in this PR~~ I've no clue how a proper test for that would look like.
- ~~[ ] I have added documentation for the changes (in the manual)~~ No new feature.
- [x] There's a new file in `changelog/unreleased/` that describes the changes for our users (template [here](https://github.com/restic/restic/blob/master/changelog/TEMPLATE))
- [x] I have run `gofmt` on the code in all commits
- [x] All commit messages are formatted in the same style as [the other commits in the repo](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#git-commits)
- [x] I'm done, this Pull Request is ready for review

### CODE REVIEW

File: cmd/restic/global.go [hunk 1]
```diff
@@ -160,9 +162,14 @@ func restoreTerminal() {
 	}
 
 	AddCleanupHandler(func() error {
+		// only restore the terminal settings when they were modified
```
Comment (rawtaz) [inline cmd/restic/global.go:165]: I find this comment hard to understand easily. It talks about terminal settings being modified, but the flag that's checked is about whether or not password reading is active. They seem like two different things. For readability, can this comment be rephrased?

Comment (MichaelEischer) [reply cmd/restic/global.go]: I've adapted the comment to better match the following check. Right now the comment and the check afterwards yield the same result, but I agree that it was a bit confusing.

File: changelog/unreleased/issue-2298 [hunk 2]
```diff
@@ -0,0 +1,10 @@
+Bugfix: Do not hang when run as a background job
+
+Restic did hang on exit when it was started as a background jobs, for example
```
Comment (rawtaz) [inline changelog/unreleased/issue-2298:3]: s/jobs/job/

File: changelog/unreleased/issue-2298 [hunk 3]
```diff
@@ -0,0 +1,10 @@
...
+using `restic ... &`. restic was stopped when trying to restore the terminal
```
Comment (rawtaz) [inline changelog/unreleased/issue-2298:4]: Big R after the dot.

File: changelog/unreleased/issue-2298 (hunk 2 above)
Comment (MichaelEischer) [reply changelog/unreleased/issue-2298]: Fixed

File: changelog/unreleased/issue-2298 (hunk 3 above)
Comment (MichaelEischer) [reply changelog/unreleased/issue-2298]: Thanks for proof reading!

File: changelog/unreleased/issue-2298 [hunk 4]
```diff
@@ -0,0 +1,10 @@
+Bugfix: Do not hang when run as a background job
+
+Restic did hang on exit when it was started as a background job, for example
+using `restic ... &`. Restic was stopped when trying to restore the terminal
+configuration on exit to ensure that reading a password from the terminal
+cannot leave the user with a misconfigured terminal. We have changed the
+behavior to only restore the terminal configuration when restic is interrupted
+while reading a password from the terminal.
```
Comment (rawtaz) [inline changelog/unreleased/issue-2298:8]: With the risk of being picky, I think this is too technical for the average user. If they want to deep dive they can check the discussions here on GitHub. What do you think about:

Restic used to hang on exit when it was started as a background job, for example
using `restic ... &`. This has been fixed by now only trying to restore the terminal
when restic is being interrupted while reading a password from the terminal.

Comment (MichaelEischer) [reply changelog/unreleased/issue-2298]: My changelog text felt too long while writing it, I think its in fact better to leave the technical details. I've changed it to your proposal and added a remark that the hang was caused by the terminal reconfiguration. Otherwise its not really clear how the two sentences relate to each other.

File: cmd/restic/global.go [hunk 5]
```diff
@@ -160,9 +162,14 @@ func restoreTerminal() {
 	}
 
 	AddCleanupHandler(func() error {
+		// only restore the terminal settings when reading a password
+		if !isReadingPassword {
```
Comment (rawtaz) [inline cmd/restic/global.go:166]: Can this be expanded to give a short explanation as to why we need to do this?

One should be able to read the code and understand why this is done, and it's not really clear now.

File: changelog/unreleased/issue-2298 (hunk 4 above)
Comment (rawtaz) [reply changelog/unreleased/issue-2298]: I'm not seeing the remark, where did you add that?

Comment (MichaelEischer) [reply changelog/unreleased/issue-2298]: I've sneaked it into the first sentence: `hang on exit while restoring the terminal configuration when`.

**Review by rawtaz — APPROVED** [review]
